### ISSUE TITLE
[Proposal] Adding nodes. RMB instead of Space Button.

### ISSUE THREAD

**Issue by Shohrukh1999** [RodZill4/material-maker#103]
Hello! I would like to suggest adding nodes via RMB, and the Space button to move the view. (In Material Maker, you can also move the view via the Space button, but first a window for adding nodes appears, which is not very convenient).
But adding nodes via RMB needs to be made more convenient than now, which is via the Space button.
![IMG_20200404_205027](https://user-images.githubusercontent.com/46423713/78457722-b37a6800-76c5-11ea-8126-354e162bd329.png)
This approach is used by all operating systems. For example, Windows.
![jQ_xIJnh71-v_UbrsyfO7a-ZF0-eE2ZdSiP3L2lZ-IMCYeN5hii2NctXPmNUXmxV0r0gidERi7Yw1A0o7zxWiewKKCN3OISoEEuouEHWDduwY8vzZ5Qt-kb5kobLOgepcabC8ImFkL5Ya7a3ch-JtYojaA](https://user-images.githubusercontent.com/46423713/78457734-c8ef9200-76c5-11ea-886c-c9a694904c9a.jpg)
I think this approach is more accessible and easy for users. I hope you will like it.
P.S. Google Translator.

**Comment by RodZill4** [comment]
You can currently move the view using the middle mouse button, there is no point using the keyboard for that. The hierarchical menu you suggest would be very inefficient once you know the node names.

**Comment by PopeRigby** [comment]
I agree that the add node menu should be bound to RMB, it's more intuitive. MMB for panning is just fine.
