### ISSUE TITLE
Unity export keeps generating the same UUIDs from multiple .ptex files

### ISSUE THREAD

**Issue by luggage66** [RodZill4/material-maker#104]
Separate .ptex files are generating textures with the same guid during a unity export.

For example, say I have 

* `bricks.ptex`, which I export to `bricks.mat` and `bricks_albedo.png`
* `grass.ptex`, which I export to `grass.mat` and `grass_albedo.png`

I may get the same guid in `bricks_albedo.png.meta` and `grass_albedo.png.meta` causing issues when importing into Unity.

v0.9 - Windows

**Comment by RodZill4** [comment]
Oops, this one should be fixed easily, thanks for reporting the problem. I think you can workaround the problem with current releases by opening all materials at the same time and export them from the same Material Maker.

**Comment by RodZill4** [comment]
@luggage66 It should be fixed on master if you feel like using a development version.

**Comment by luggage66** [comment]
Excellent, thanks!
