### ISSUE TITLE
Material Maker Discord / Reddit

### ISSUE THREAD

**Issue by Jummit** [RodZill4/material-maker#105]
I think a place to share tips, materials and just chat about material maker would be cool. It would be a time investment and I'm not sure if anyone is up for it, but I'm just making this suggestion to see if there are others who also want this.

- [x] Reddit
- [ ] Discord

**Comment by nonunknown** [comment]
I think its a excellent idea, people can share experience and tips with each other.

**Comment by RodZill4** [comment]
@Jummit @nonunknown I started a subreddit but I have no friend: https://www.reddit.com/r/MaterialMaker/
Any feedback before I advertize it?

**Comment by Jummit** [comment]
> Any feedback before I advertize it?

lgtm
