### ISSUE TITLE
Library is broken

### ISSUE THREAD

**Issue by Jummit** [RodZill4/material-maker#111]
The library tab is broken as of 4b5d6d7a0850f10cf8e311c0ce6d5350bf539935

**Comment by RodZill4** [comment]
Are you up to date with master ? I fixed it.

**Comment by Jummit** [comment]
> Are you up to date with master ? I fixed it. [0a13e50](https://github.com/RodZill4/material-maker/commit/0a13e505e6474bec8198b2be1a695b0bba7b387d)

Oops, my bad. I only tested my branch.
