### ISSUE TITLE
Crash when resizing window

### ISSUE THREAD

**Issue by zauberparacelsus** [RodZill4/material-maker#112]
Resizing the window caused the program to freeze for 5-10 seconds, and then afterwards it crashed.

**Comment by RodZill4** [comment]
Hmm on which realease did it happen? Do you have a scenario to repeat this problem?

**Comment by zauberparacelsus** [comment]
I was assuming the latest, but apparently 0.8 got installed, rather than the current 0.9?  After uninstalling and doing a reinstall, it seems 0.8 is selected by default.

I'm not seeing the issue repeating now, but if I see further crashes or figure out how to reproduce it, I'll update this bug report.

**Comment by zauberparacelsus** [comment]
What I've observed in 0.9 is that there is a slowdown when resizing with a more complicated node setup, but it doesn't cause a freeze, so it is possible that the issue was resolved in 0.9, especially if it had any changes regarding performance.

**Comment by RodZill4** [comment]
The real changes regarding performance will be in 0.92, and they are partly in the "April fools" 0.91 release.
