### ISSUE TITLE
[Proposal] Add Math Node

### ISSUE THREAD

**Issue by zauberparacelsus** [RodZill4/material-maker#117]
While toying around with Material Maker, I noticed that there was no math node, something that I rely upon in blender.  It takes two grayscale inputs and produces one grayscale output, and has a dropdown for the different math operations.  Some (such as Square Root) only use one of the grayscale inputs, and hide the second.  There's also a Clamp checkbox, which causes it to constrain the value to a range of 0 to 1.0.

Screenshot of the node in blender, plus all the different operations it supports:
![image](https://user-images.githubusercontent.com/548168/81335271-5895b100-9075-11ea-9a89-ae88623f3022.png)

Link to documentation for the math node: https://docs.blender.org/manual/en/latest/compositing/types/converter/math.html

**Comment by Hopefullyidontgetbanned** [comment]
I often Use Blender's math node for masks and procedral noise so this is a very important feature in my opinion.

**Comment by RodZill4** [comment]
Blender's nodes and Material Maker are very different tools. I'm not sure all those operations can be useful to create textures.

Could you please describe a few uses of the operators that are not already in the Blend node?

This, of course, is be a piece of cake to implement as custom node(s), so I'd rather provide a simple node with only useful operations.

**Comment by Hopefullyidontgetbanned** [comment]
well math node is primarily used for BW inputs such as roughness and bump, for example getting the average of two greyscale inputs by using an add and a divide math node.
![Screenshot (1376)](https://user-images.githubusercontent.com/45346421/82161975-ea5fa400-9855-11ea-95ed-7da807de3a8f.png)

**Comment by RodZill4** [comment]
To calculate the average you can use the Blend node. Which does not mean there won't be a Math node (started adding it already). ;)

**Comment by zauberparacelsus** [comment]
Main operations in the Math node that I usually wind up using outside of the basic ones (Addition, Subtraction, Multiplication, Division) are Square Root, Inverse Square Root, Absolute, Minimum, Maximum, Less Than, and Greater Than.
