### ISSUE TITLE
[Proposal] Add a Slope Blur node

### ISSUE THREAD

**Issue by huttyblue** [RodZill4/material-maker#123]
Slope blur is in short a directional blur that takes a height-map in instead of a fixed direction. It essentially blurs the source image using the heightmap's "downhill" direction for the direction of the blur. Its used extensively in substance for making the chips and dents you would expect to find in rocks, among other things.

I tried to replicate its behavior by stacking and blending a bunch of warp nodes but after getting 6 deep the program started to lag heavily when clicking on a node at the end of the stack (as in freezing for 10+ seconds).

**Comment by RodZill4** [comment]
A quick prototype (copy the text and paste into Material Maker).

https://pastebin.com/raw/imBxzX1C

@huttyblue could you test it and tell me if it's usable?

**Comment by huttyblue** [comment]
Sorry for the delay, I gave the node a try. 
![image](https://user-images.githubusercontent.com/38145037/84428438-115a8d00-abec-11ea-8585-82468dfeef3d.png)

It can get interesting results, although there are some issues. 
For one if full black or full white are sent as inputs it returns black. 
![image](https://user-images.githubusercontent.com/38145037/84429327-8da1a000-abed-11ea-9c90-5c37e8456d9c.png)

Which becomes a big issue when you try to stack them
![image](https://user-images.githubusercontent.com/38145037/84429428-bcb81180-abed-11ea-9385-754a198163b1.png)

Also its somewhat "pinchy" in its behavior, which does make sense with how I described it but in practice it doesn't really do the same thing as slope blur in other programs. 
![slopeblur1](https://user-images.githubusercontent.com/38145037/84430013-b1191a80-abee-11ea-9a82-c2e230b61f2a.gif)

**Comment by RodZill4** [comment]
Hmm I must investigate the first problem, it does not seem that easy.
For the "pinchy" aspect, do you mean you'd like finer control on the sigma parameter? Maybe less amplitude and better precision, or just better precision? You can use Ctrl+Alt for finer control over float parameters (not quite sure in which release this was introduced, though).
Anyway, thanks for your feedback!

**Comment by huttyblue** [comment]
https://imgur.com/a/h2g3eKT
I don't know if this is fully related but I was looking into it further and I noticed that the slope blur setting I was messing with in substance designer was basically the same as using a warp node. But the warp node in Material Maker behaves differently. I can kind of get similar results if I set the mystery bottom slider of the warp to a very small number but it also shows a strange pinching effect in the center of the cells. 

As for the pinching in slope blur it does make sense for what the node is doing, its just not helpful for the effect I'm trying to achieve. I'm not sure if its feasible math wise, but what if the blur intensity was also based off the steepness of the slope. So the tops of the "domes" wouldn't blur as much because they have a shallow angle. (Along with a slider to control that factor)

In total here, I'm trying to achieve that faceted look on the left-side of the gif. 
I didn't know about the Ctrl+Alt thing, thanks for the tip.

**Comment by RodZill4** [comment]
@huttyblue The first problem was a division by zero error in the shader (-> black pixels where it happened). Fixed version: https://pastebin.com/raw/kzgnLxNj

In the slope blur, the intensity of the blur **is** proportional to the steepness of the slopes. But voronoi patterns are cones (if seen as heightmaps), slopes are all the same. You can turn those into domes by choosing the third interpolation option in the colorize node (that uses a cosine curve between values instead of linearly).

**Comment by RodZill4** [comment]
@huttyblue for the faceted look I have no idea how the warp node from SD can generate this (reading the doc). I'll have to investigate further.

BTW the mystery parameter is the offset used to compute slopes in the warp texture.

**Comment by RodZill4** [comment]
@huttyblue OK, now I had time to think about it, I think I understand the difference. I misunderstood the Warp node description and thought the warp amount was given by the slope. In fact, it seems it seems it depends on the slope and distance to top, which means that with the right value of the intensity parameter, each point of a Voronoi cell will be warped from the same location (hence the nice faceted result).

Here's an example with a modified Warp node: https://pastebin.com/raw/QxMcAK6m

And here's the result.
![image](https://user-images.githubusercontent.com/6957908/84546643-0bef6680-ad02-11ea-997f-9d0b84502caf.png)

Please don't hesitate to test it if you have time and tell me if you like it.

**Comment by huttyblue** [comment]
Huh, I was not aware changing the colorize curve would get a sphere falloff. 

I had to download the git for the new warp node to work, but after getting that up and running it works great!
![image](https://user-images.githubusercontent.com/38145037/84552329-ff551900-acd5-11ea-9972-5af7d7cb7948.png)

New slope blur is looking good too. 
![image](https://user-images.githubusercontent.com/38145037/84553181-f6b21200-acd8-11ea-8d75-237de4eb721b.png)

Thanks alot for iterating on this.

**Comment by RodZill4** [comment]
@huttyblue Thanks a lot for your feedback. This is how Material Maker can progress!

**Comment by RodZill4** [comment]
Oh, and about the "shapes" (or rather profiles) that can be created using greyscale gradients, I think I will add a node that helps visualizing those.
