### ISSUE TITLE
[Proposal] Favorite folders for the open / save file dialog.

### ISSUE THREAD

**Issue by MrDiamondGold** [RodZill4/material-maker#126]
Something that has repeatably annoyed me is I have to change my drive and go through a bunch of folders to get to where I store all my materials every time I open, save or export a material file. It would really help if there was a favorites and/or history sidebar.

**Comment by RodZill4** [comment]
I have to admit this file dialog is a PITA.

The EditorFileDialog has this feature but does not seem to be usable in Godot projects, so it seems this problems needs a new file dialog.

**Comment by Calinou** [comment]
The default FileDialog location could be made configurable as a workaround.

**Comment by Jummit** [comment]
I actually made my own build that always targets my "Materials" folder, I couldn't stand navigating to it every time. I fully support this proposal. It should probably remember the last folder you saved a material in. Although, materials are mostly stored in their own folders, so it should maybe remember in which directory the last material folder was in?

**Comment by RodZill4** [comment]
Just commited a change that remembers location for last loaded material (and template, but that should not affect end user tat much). I will also add this for exports.

**Comment by owlnical** [comment]
Thanks for adding the memorize path function, it really makes things easier. Favourite fo
