### ISSUE TITLE
Why does this happen when moving around Bricks properties sheet?

### ISSUE THREAD

**Issue by wyattbiker** [RodZill4/material-maker#127]
v0.92

![material-maker-capture](https://user-images.githubusercontent.com/930478/85210245-5aa58d80-b30c-11ea-9110-a906c26dd20f.gif)

**Comment by Calinou** [comment]
This is because the random seed depends on the node's position. There's a "lock" icon you can use somewhere to lock it, so it won't change when you move the node.

**Comment by Calinou** [comment]
@RodZill4 This issue should probably be closed, unless we intend to lock nodes' seeds by default (which might be a good idea).

**Comment by wyattbiker** [comment]
I don't think adjusting the UI should affect the object in anyway. There should be a button for that.

**Comment by Jummit** [comment]
This discussion should be held in #79

**Comment by RodZill4** [comment]
This issue is a duplicate of #79

**Comment by RodZill4** [comment]
Duplicate of #79
