### ISSUE TITLE
Preview does not update when node is deleted

### ISSUE THREAD

**Issue by SekoiaTree** [RodZill4/material-maker#128]
How to reproduce:
Open a new material. Add a perlin warp1 node (for example. This works with any node that changes what the output looks like). Link up that node with the albedo, wait for the preview to update, then delete the node. The preview does not change.
Add another one, connect, disconnect. This "fixes" it.
Related to #64

**Comment by RodZill4** [comment]
Indeed, thanks for reporting. That will be a last minute fix. ;)

**Comment by RodZill4** [comment]
Looks like it's fixed now...
