### ISSUE TITLE
Blend node, blending modes incorrect.

### ISSUE THREAD

**Issue by rt974** [RodZill4/material-maker#129]
Hi,

Thanks for this great piece of software, i can see there is a lot of potential.

It seems to me that the blend node doesnt work as expected, some of the modes like overlay or screen, do not give results you get example from blender or photoshop or whatever substance designer/painter. I had to put some value like 0.0001 to blend the result of a edge finder to a simple uniform color to get edges highlighted very subtely.

Well normally you just have to put values such as 0.1 or 0.2, but not 0.0001. lol. The calculation is way off.

**Comment by RodZill4** [comment]
@rt974 would it be possible for you to provide an example (a Material Maker project and coresponding settings in  another tool)? Thanks a lot in advance.

**Comment by RodZill4** [comment]
OK, just understood the problem... Of course it's not the blend node, but the edge detect that do not clamp their result to [0, 1].

**Comment by RodZill4** [comment]
@rt974 you can workaround the problem by adding a colorize node (with default gradient) between the edge detect and the blend nodes.

**Comment by rt974** [comment]
thanks

**Comment by rt974** [comment]
sorry i did not see the email notification for your previous message. the first thing i tried after downloading and compiling was do a simple edge detect and plug it to a blend node. lol.
