### ISSUE TITLE
Some questions using the 0.6 Linux version from itch

### ISSUE THREAD

**Issue by wyattbiker** [RodZill4/material-maker#13]
- Can you also Export a complete face texture.png capture with all material/filters/etc settings applied?
- How do you restart the cube preview rotation once it is paused?
- I don't see Grid lines when clicking snap button.
- How do you add Material (in case I delete using the X button)

Thanks

**Comment by RodZill4** [comment]
- Materials are saved as up to 4 textures. Or do you mean some kind of screenshot of the preview ?
- It cannot be restarted yet, but there's a Pull Request for that.
- Hmm I will investigate this...
- This is a bug, you should not be able to delete this node.

**Comment by wyattbiker** [comment]
What I mean is to capture/bake the texture into a single one e.g. of the faces of the cube or cylinder.

**Comment by RodZill4** [comment]
OK. It is not possible in 0.6, but would not be difficult to implement.

**Comment by RodZill4** [comment]
All this has been fixed long ago
