### ISSUE TITLE
Linux –– font too small, DPI cant be ajusted 

### ISSUE THREAD

**Issue by leonard7e** [RodZill4/material-maker#132]
System - Ubuntu Linux
Monitor: 24'' with 1920x1080 

Font size is tiny and difficult to read. For comparison, look at attached image below.

Currently it seems there is no way to adjust font size via Xft//DPI. 

Test shows that any DPI value I set in Ubuntu/Linux is overridden with value of 91. If number 91 is hardcoded into Godot, might there be an option to scale MaterialMaker  UI to improve font readability on Linux machines?

![font_size](https://user-images.githubusercontent.com/5395270/86421378-218cf600-bcda-11ea-9117-e52ec99e3efa.jpg)

**Comment by Calinou** [comment]
Material Maker only supports integer scaling, as proper non-integer scaling requires a feature to be added into Godot: https://github.com/godotengine/godot/pull/21446

**Comment by Zireael07** [comment]
@Calinou: IIRC some devices report DPI badly, on top of what you said?

**Comment by Calinou** [comment]
@Zireael07 That too, but this is an entirely separate issue. Either way, we should add an option to force a specific UI scale once we add non-intger scaling.

It might be possible to add an option that changes just the font size, but this is bound to make many UI elements look uncanny or entirely broken.

**Comment by leonard7e** [comment]
I opened more general #132, because I like to make sure non-hdpi case is handled too. If so, I am perfectly fine #132 is seen as duplicate.

Does Godot use Monitor information to estimate DPI resolution?  
`91 == sqrt(1920**2+1080**2) / 24  `
There 91 DPI seems to come from. 

Thinking about it, this DPI is formally correct for my screen. But it does not work for me as user. In my workflow I do use multiple monitors, each is 80cm to 100cm away from my eyes. Scaling DPI to 128 DPI balances out eye distance and font size, keeps computing agreeable. 

Formally correct DPI for screen is not nescesarly the right size for a user. A user might need to scale UI independently from screen resolution to adapt UI to his needs, especially in multi monitoring workflows. 

In Godot, a floating point option to scale UI would be great way to balance formally correct DPI with user needs.
