### ISSUE TITLE
Hardcoded locations used in the code, causing warnings and errors.

### ISSUE THREAD

**Issue by Sslaxx** [RodZill4/material-maker#134]
Seen as of commit 2edf905964639984605107d12d6fe5514beef590 but undoubtedly long before this.

While running the project via Godot, at least one error turns up in the debugger panel indicating that, somewhere in the code, hard-coded directories are being used.

This is the error:
```
E 0:00:30.067   load_image: Error opening file 'D:/Dev/Godot/godot-procedural-textures/addons/material_maker/icons/icon.png'.
  <C++ Source>  core/io/image_loader.cpp:56 @ load_image()
  <Stack Trace> gen_image.gd:21 @ set_parameter()
                gen_base.gd:306 @ deserialize()
                loader.gd:116 @ create_gen()
                loader.gd:60 @ add_to_gen_graph()
                graph_edit.gd:222 @ create_nodes()
                graph_edit.gd:363 @ drop_data()
```

This may be an error in `material_maker/library/base.json`, but possibly also `material_maker/examples/metal_pattern.ptex`; the binary files `material_maker/preview/panoramas/moonless_golf.hdr` and `material_maker/preview/panoramas/epping_forest_01.hdr` may also be problematic.

**Comment by RodZill4** [comment]
Fixed in 0.97 (11330d6fa6fa6733c2ea810ae1a03c2f40a94730)
