### ISSUE TITLE
Emboss node with width set to 0 causes display glitch

### ISSUE THREAD

**Issue by fccDunce** [RodZill4/material-maker#135]
2D background preview active,
emboss node selected, set width to 0 .
preview turns black and display is glitched - see image below.

![emboss_glitch](https://user-images.githubusercontent.com/13915506/88460172-f5146600-cea2-11ea-99ec-3f60c5514949.png)

**Comment by Calinou** [comment]
@fccDunce Which operating system and graphics card model are you using?

**Comment by fccDunce** [comment]
> Which operating system and graphics card model are you using?

Windows 10, nvidia GTX 760
