### ISSUE TITLE
Expose grid size [and other] parameters for Output node

### ISSUE THREAD

**Issue by fccDunce** [RodZill4/material-maker#137]
**Feature/enhancement description:**

The workflow Output node generates normal and ambient occlusion passes automatically, but there's no way to control the filter/grid sizes for them.
Also, there's a Mat Normal strength parameter, but no such parameter for the generated normal.

**Comment by RodZill4** [comment]
Workflow nodes will be rewritten completely

**Comment by RodZill4** [comment]
Workflow nodes need to be rewritten completely
