### ISSUE TITLE
[Proposal] Show custom node groups in the library pane

### ISSUE THREAD

**Issue by fccDunce** [RodZill4/material-maker#138]
**Feature/enhancement description:**

Saving and reusing custom node groups is cool, but finding them only in the Tools>create menu is a little cumbersome.
Could it be possible to add a new section in the library, listing the user created .mmg files, while using a similarly named .png file as a custom thumbnail? This should use the same searching/filtering/drag-drop functionality as standard nodes.

**Comment by RodZill4** [comment]
Doing this would add many unsorted duplicates to the library. All nodes you want to access easily should be added to the library (using the "Add selected node to user library" menu entry).

I planned to:
- allow directory hierarchies for mmg files and mmg files in the user directory
- allow several libraries and make them a lot easier to create/modify

**Comment by RodZill4** [comment]
Libraries stuff has been added in 0.95
