### ISSUE TITLE
[Proposal] Opacity Output

### ISSUE THREAD

**Issue by Hopefullyidontgetbanned** [RodZill4/material-maker#141]
Many Programs that deal with Procedural texturing ex. (Blender/Substance Designer) have support for Opacity maps/alpha transparency, this is really useful for things like a mesh fence material
![chainlink_fence_fence_blur_barrier-57643](https://user-images.githubusercontent.com/45346421/89114893-fced8080-d435-11ea-863a-46133fcc4289.jpg)

**Comment by RodZill4** [comment]
That would be a piece of cake to implement, only requires work on the 3D preview and export targets.

**Comment by Hopefullyidontgetbanned** [comment]
should close this since it seems to be dealt with
