### ISSUE TITLE
Custom Random-ness Properties/Nodes for Sub-Graphs

### ISSUE THREAD

**Issue by Takanu** [RodZill4/material-maker#143]
**Feature/enhancement description:**
While nodes like noise can utilize noise and sub-graphs will roll randomness for them when moved, you can't setup your own randomness elements for values or nodes.

- It's something that's really useful for quickly finding or creating randomness when working with multiple of the same node type without having to dial in sets of different values repeatedly.

- For nodes dealing with nature or that should look more natural, it's an important component that is sometimes best expressed with a seed rather than a set of custom properties as currently unless the node relies on any pre-built nodes like noise nodes, they will always remain static until deliberately changed.

I'd propose two similar components to this effect:

#### 1) Add randomness linked controls to sub-graphs
Could work like a linked control on the graph that doesn't take an input and instead lets you set it as a seed, then link it to any number of properties you want in the graph.  Supporting a clamped range of values that could be randomly chosen from would be important.

#### 2) Add a random color AND/OR an eyedropper node
One easy way randomness could be introduced to a sub-graph is to just add a random color node or a color picker node.  One can quickly generate RGBA/Grayscale values when moved which can be modified and utilized however the designer chooses, the other can be used in a more specific way (for example, sampling noise maps).

**Comment by RodZill4** [comment]
Can now be done with named parameters and randomness in parameter expressions.
