### ISSUE TITLE
Bigger Node Connection Click Zones

### ISSUE THREAD

**Issue by Takanu** [RodZill4/material-maker#144]
With Material Maker right now, particularly when you zoom out it's almost impossible to click the little circle you need to make connections between nodes, and if the app gets the ability to zoom out further this clickable zone needs to be bigger.

![image](https://user-images.githubusercontent.com/9108903/90192923-d3c8da80-ddbb-11ea-879f-0ef60c2805d7.png)

My proposal is to take a page out of the iOS app Shade and it's touch-friendly input and output design:

![IMG_1782](https://user-images.githubusercontent.com/9108903/90192561-150cba80-ddbb-11ea-9799-a3619c26b4d1.png)

In Shade the entire text frame displaying the property is a clickable frame which can be used to link nodes together, and the frame BG changes color when it's linked based on the specific value it's receiving or sending.  If it's a value like a float that doesn't need an input, it also has a specific colour of it's own (such as float values being labelled in Yellow to mark it clearly as a configurable value).

- It saves some horizontal node space by removing the need for a dot icon to link on inputs.
- When dragging a link to a new input or output, the delivery zone also becomes bigger which makes it easier to finish connecting the link rather than missing and bringing up the, "New Node" menu.
- Requires that either output node links be given a labeling system similar to Shade where they hang off the frame to the right, or something that mimics the frame on the input text but without any labels.

![6AB25FA8-DEF2-4699-80A0-17C3357B6EE8](https://user-images.githubusercontent.com/9108903/90207983-9b3af800-dddf-11ea-9acf-c244141d74fa.jpeg)
![8305A569-7FE9-4045-B3E0-866662E1FB01](https://user-images.githubusercontent.com/9108903/90207988-9d04bb80-dddf-11ea-8614-d9124d86d520.jpeg)

These are two rough concepts i quickly mocked up to try and illustrate the "tab" idea for connecting nodes together.

(I assume that Material Maker's node design is constrained by Godot but I hope the design can develop over time 👌 )

EDIT - Honestly, even if you made the text labels a pick up and drop zone that would fix the issue at least mechanically, although the UI should visually show that ability too it can be done later as thats a much bigger task.

**Comment by RodZill4** [comment]
Part of that problem should be fixed in Godot, because connecting stuff in (for example) Godot's Visual Shader editor when zoomed out is difficult.

I'm not sure about your solution. Nodes are big already, and your proposal would make them bigger (there are very few nodes where an input corresponds to a parameter). But nodes UI also need to show what inputs and outputs are for so I must think about it.

And to connect nodes that are far from each other, what about:
- Control+Click an output selects it
- Click an input with an output selected connectes them
- Clicking anywhere else un-selects the selected output

**Comment by Takanu** [comment]
My proposal would make them a little wider, but not by much given how much padding the input/output circles get already.  I mocked up two concepts to try and compare the difference:

![IMG_1787](https://user-images.githubusercontent.com/9108903/90256870-42e71300-de3e-11ea-8e6f-adaaac2a6eee.jpeg)

Plus as the outputs wont likely take up the entire height of the node, you get more negative space to see the 2D or 3D preview background with.  Shade also makes the conscientious choice of keeping output names short and simple (R for some math operations, RGB, A for Alpha, Tex for Texture, etc).

That solution still has the problem of needing to click the small input/output circles to register so I dont think it solves the problem, although something like that sounds useful once this issue is solved.

**Comment by RodZill4** [comment]
My proposal for connecting nodes that are far from each other was a bonus, not a replacement for your proposal.

The main problem (being able to connect when zoomed out) seems to be in Godot, I must investigate if it is a known problem, if someone is working on it etc.

"I must think about it" does not mean "no". It just means "I must think about it". ;) I had plans to add tooltips on all ports and parameters, both topics are related.

**Comment by Takanu** [comment]
Ah, my apologies ^-^

And of course, it was never my intention to suggest your response was a denial, i'm just discussing it and making mockups to visually describe ideas (and because I like designing things).

**Comment by RodZill4** [comment]
Not much can be done in MM about this, this is mainly in Godot.
