### ISSUE TITLE
Replace Transform node to add donttouch/clamp/repeat parameter

### ISSUE THREAD

**Issue by Takanu** [RodZill4/material-maker#146]
**Material Maker version:**
0.92, spicy 0.93 version

**OS/device including version:**
Windows 10 (Build 18363)
Intel Core i5-3470
NVIDIA GeForce GTX 1060 3GB VRAM
24GB RAM

**Issue description:**
When a shape is scaled to a size of 1, distortion occurs beyond the boundaries of the UV space that can be revealed through a Transform operation.  Additionally, small line-like graphical artifacts appear above the shape.

![image](https://user-images.githubusercontent.com/9108903/90318131-4229ac00-df26-11ea-9219-546671e83638.png)

While this can be circumvented by using a lower scale property and stacking another transform operation on top of it, this adds extra unnecessary steps as well as a loss of detail from the original shape.

While you can set the scale value to 0.9999 which might be functionally identical to 1.0 in Material Maker's eyes my concern is that it might somehow result in a loss of precision, it shouldn't be left down to chance and the app should communicate it's own limits.  For example I needed a square with a size of 1 because I needed to make a precise, grid-based mask for a custom library node I was working on.

**Steps to reproduce:**
Copy and paste the following Material Maker demos for two examples as to how it happens and why it's important.

`
{"connections":[{"from":"shape_2_2","from_port":0,"to":"transform_3","to_port":0},{"from":"shape_2_2_2","from_port":0,"to":"transform_3_2","to_port":0},{"from":"noise","from_port":0,"to":"blend_4","to_port":0},{"from":"transform_3_2","from_port":0,"to":"blend_4","to_port":1},{"from":"shape_2_2_3","from_port":0,"to":"transform_3_3","to_port":0},{"from":"blend_4","from_port":0,"to":"Material","to_port":0},{"from":"shape_2_2_4","from_port":0,"to":"transform_3_4","to_port":0}],"nodes":[{"color":{"a":1,"b":0,"g":0.5,"r":1,"type":"Color"},"name":"comment_7","node_position":{"x":-400.728271,"y":180.32959},"parameters":{},"size":{"x":1192.960083,"y":289.200073},"text":"Precision importance (use 2D node background to see the small gap on the right side of the square)","title":"Comment","type":"comment"},{"color":{"a":1,"b":0,"g":0.5,"r":1,"type":"Color"},"name":"comment_6","node_position":{"x":-390.648285,"y":-103.350403},"parameters":{},"size":{"x":588.160034,"y":178.319946},"text":"Artifacts above the shape.","title":"Comment","type":"comment"},{"color":{"a":1,"b":0,"g":0.5,"r":1,"type":"Color"},"name":"comment_5_2","node_position":{"x":-367.928375,"y":-367.470398},"parameters":{},"size":{"x":536.320068,"y":174.000061},"text":"0.99 scaling demo","title":"Comment","type":"comment"},{"color":{"a":1,"b":0,"g":0.5,"r":1,"type":"Color"},"name":"comment_5","node_position":{"x":-358.968475,"y":-666.390381},"parameters":{},"size":{"x":536.320068,"y":174.000061},"text":"1.0 scale issue","title":"Comment","type":"comment"},{"name":"noise","node_position":{"x":-50.239624,"y":486.943726},"parameters":{"density":0.5,"size":11},"type":"noise"},{"name":"shape_2_2","node_position":{"x":-304.259613,"y":-591.946167},"parameters":{"edge":0,"radius":1,"shape":1,"sides":4},"seed_value":-39642,"type":"shape"},{"name":"transform_3_3","node_position":{"x":-103.488281,"y":-310.000244},"parameters":{"repeat":false,"rotate":0,"scale_x":0.5,"scale_y":0.5,"translate_x":0.008182,"translate_y":-0.059545},"type":"transform"},{"name":"transform_3","node_position":{"x":-98.81958,"y":-589.946167},"parameters":{"repeat":false,"rotate":0,"scale_x":0.5,"scale_y":0.5,"translate_x":0.008182,"translate_y":-0.059545},"type":"transform"},{"export_paths":{},"name":"Material","node_position":{"x":495.764709,"y":248.300415},"parameters":{"albedo_color":{"a":1,"b":1,"g":1,"r":1,"type":"Color"},"ao":1,"depth_scale":0.5,"emission_energy":1,"metallic":1,"normal":1,"roughness":1,"size":11,"sss":0},"type":"material"},{"name":"shape_2_2_3","node_position":{"x":-306.048279,"y":-320.640259},"parameters":{"edge":0,"radius":0.99,"shape":1,"sides":4},"seed_value":-39642,"type":"shape"},{"name":"transform_3_4","node_position":{"x":-108.548218,"y":-40.360413},"parameters":{"repeat":false,"rotate":0,"scale_x":0.5,"scale_y":0.5,"translate_x":0.008182,"translate_y":-0.059545},"type":"transform"},{"name":"shape_2_2_4","node_position":{"x":-312.548309,"y":-42.360352},"parameters":{"edge":0.22,"radius":1,"shape":1,"sides":5},"seed_value":-39642,"type":"shape"},{"name":"shape_2_2_2","node_position":{"x":-320.139648,"y":261.293823},"parameters":{"edge":0,"radius":0.99,"shape":1,"sides":4},"type":"shape"},{"name":"transform_3_2","node_position":{"x":-110.739563,"y":268.09375},"parameters":{"repeat":false,"rotate":0,"scale_x":0.5,"scale_y":0.5,"translate_x":0.25,"translate_y":0.008182},"type":"transform"},{"name":"blend_4","node_position":{"x":206.960449,"y":366.743774},"parameters":{"amount":1,"blend_type":2},"type":"blend"}]}
`

**Comment by RodZill4** [comment]
Hmm this is not a bug. The Transform node either clamps or repeats its input. The TRanslate, Scale and Rotate nodes will transform their input without clamping or repeating it. It would be difficult to change the Transform node behaviour without breaking compatibility.

Anyway, I have to admit this should be least explained in the doc...

**Comment by Takanu** [comment]
Ah, I understand now.  In that case maybe having a dropdown that changes it's UV behaviour between Clamp, Repeat and None would be a good idea - that way it doesn't break compatibility, the node becomes more useful, the user becomes familiar with the way it functions organically without having to open the manual and all it does is replace the space that the Repeat boolean occupies.

**Comment by RodZill4** [comment]
@Takanu 
This would break compatibility, since it would replace the "Repeat" parameter in the "Transform" node (adding parameters is generally not a problem, but removing or modifying them breaks compatibility). I guess the best solution would be to create a new Transform node, and remove the old one from the base library. The old Transform will remain (for old materials), but will be deprecated.

**Comment by Takanu** [comment]
Ah, understood.  And yeah, id agree that's the best option.

**Comment by RodZill4** [comment]
Btw,  do you know how substance designer handles that case?

**Comment by Takanu** [comment]
From what I remember a few years ago Substance Designer applied repeat on all transforms and was not customizable, which is why I made my own custom Transform node which used masks to circumvent that limitation.
