### ISSUE TITLE
Loading a specific material causes Material Maker to crash

### ISSUE THREAD

**Issue by Takanu** [RodZill4/material-maker#150]
**Material Maker version:**
0.92, some 0.93 versions

**OS/device including version:**
Windows 10
NVIDIA GeForce GTX 1060 (3GB VRAM)
24GB RAM

**Issue description:**
Ive been developing a texture and after several iterations the components inside it cause Material Maker to crash.  The file can load but at some point (I assume during the process it takes to build all the textures to create the preview) the app simply crashes.

**Steps to reproduce:**
https://pastebin.com/2U2dbKma

Add this sub-graph into a scene and see if it crashes?  My guess is that it's due to the Splatter node as the app always stutters when you push the node even a little.

**Comment by Takanu** [comment]
In the node I have added many buffers and it still crashes T _ T

**Comment by RodZill4** [comment]
Adding buffers is generally not the best solution. Splatter nodes with many instances can generally be replaced with Tiler nodes, that are a lot cheaper.
In your case, MM seems to crash on a really simple shader, so that may be a different problem.

**Comment by Takanu** [comment]
I can get away with grid tiles sometimes but it doesn't always get me the result I want, and with circular patterns I have to use the Circular Splatter node which heavily slows down the program even when only dealing with a count of 15.  In more recent nodes ive been trying to create brushes of pre-scattered objects to scatter again in order to avoid this but it also has it's specific use cases.

**Comment by RodZill4** [comment]
@Takanu That blur update should solve the problem with your material. I'll check if other nodes require the same optimization.
