### ISSUE TITLE
[proposal] change image paths from absolute to relative

### ISSUE THREAD

**Issue by owlnical** [RodZill4/material-maker#153]
**Feature/enhancement description:**

An option to have image paths relative instead of absolute to keep the ptex more portable.

**Example:**

I'm working with a ptex and an externally created image stored in repo my-game.

    /home/fred/my-game/material/panel.ptex
    /home/fred/my-game/material/panel.png

The node path is absolute but could instead be stored as relative to the ptex file.

    Old:   {"image":"/home/fred/my-game/material/panel.png"}
    New:   {"image":"./panel.png"}

I can then e.g. clone the project to another computer without the image node breaking.

Windows:

    c:\users\fred\my-game\material\panel.ptex
    c:\users\fred\my-game\material\panel.png

Linux

    /home/fred/my-game/material/panel.ptex
    /home/fred/my-game/material/panel.png

**Comment by RodZill4** [comment]
This is a bit more complex than it seems. Image paths could be relative to:
- the .ptex file
- the Material Maker install directory
- the Material Maker user directory

**Comment by owlnical** [comment]
(from a git perspective, moving

I think it makes most sense that the project file path are relative to the project. But that's looking at my workflow, which is working with MM on separate machines, ie other paths.

- installation dir would not work, since its Linux -> Windows.
- user path would work, but I would have to match the directory structures, an extra step.
- relative path. No work just clone.

I think that's how blender and audacity does. I'm not 100% sure, but I don't think external files in Blender are relative to the installation path "c:/program files/blender/".
-------- Original Message --------

**Comment by Takanu** [comment]
When Blender accepts relative files, it's always to the .blend file as that's whats using the assets in the first place, and I think that's the only place that makes sense for .ptex files in maintaining project portability.

**Comment by RodZill4** [comment]
Fixed in 0.97 (11330d6fa6fa6733c2ea810ae1a03c2f40a94730)
