### ISSUE TITLE
Capture cursor when rotating view in preview 3d

### ISSUE THREAD

**Issue by escargot-sans-gluten** [RodZill4/material-maker#158]
**Feature/enhancement description:**

Currently, when rotating the preview 3d view/model, the cursor is free to exit the window or to be blocked on screen borders which makes it inconvenient, especially in the background one:
now:
![preview3d no capture](https://user-images.githubusercontent.com/44414272/91555667-b9e9d480-e931-11ea-84eb-0946c8394707.gif)

With #157 :
![preview3d capture](https://user-images.githubusercontent.com/44414272/91555683-c53d0000-e931-11ea-8909-2f584a09d794.gif)

This is a change I made locally and I think benefits user experience.
Feel free to give feedback.

**Comment by RodZill4** [comment]
Fixed by PR#157
