### ISSUE TITLE
Scratches Pattern Issues

### ISSUE THREAD

**Issue by somefoo** [RodZill4/material-maker#160]
**Material Maker version:**
0.92

**OS/device including version:**
Linux (Ubuntu 20.04)

**Issue description:**
Scratches nodes produces wrong ends and some scratches are under-sampled.
![issue](https://user-images.githubusercontent.com/50917034/91724053-fec57380-eb9c-11ea-8c70-cb5d5a9ddc5e.png)

**Steps to reproduce:**
1. Create Scratches Node
2. Play with settings a little (length and angle)

**Comment by RodZill4** [comment]
@somefoo This should be fixed now (can be tested with [a dev build]( https://github.com/RodZill4/material-maker/actions/runs/233113632) if you want).

**Comment by somefoo** [comment]
Yup, works great now :)
