### ISSUE TITLE
Add custom shape support to the Brick node

### ISSUE THREAD

**Issue by Takanu** [RodZill4/material-maker#162]
# Feature/enhancement description
While I mentioned this on the Reddit chat I figured it'd be best to formalize it here.

While it's good that the Bricks node can supply it's own shape for simpler designs and ideas, for more precise and distinct shapes it needs to support custom shapes like Substance Designer does, preferably in the same way every other splatter node works with the option for 16 inputs using the nice Tile2x2 method.

## Why is this needed?
One of the qualities of bricks or tile-like structures is that they're made up of individual pieces of material that are bound together, and this necessitates that the different pieces have slightly different shapes to make it look more organic and to communicate that method of construction.

![image](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.bricksrus.com%2Fwp-content%2Fuploads%2F2018%2F01%2F37698989_xl.jpg&f=1&nofb=1)

While you can do general blend operations to try and mitigate this, you can't without affecting the shapes around it (not without an incredible amount of color map-based isolation and re-layering).

![image](https://user-images.githubusercontent.com/9108903/91929146-a940b200-ecd5-11ea-9f5f-d9fe2a77b3cb.png)

![image](https://user-images.githubusercontent.com/9108903/91928738-b8733000-ecd4-11ea-894a-1596cd0c4253.png)

----

While you can use Tiler as you mentioned earlier, the reason I avoided it is because every time you change the tiling you have to do a bunch of math and copy/paste work just to get a preview of that tiling change. 

![image](https://user-images.githubusercontent.com/9108903/91928463-020f4b00-ecd4-11ea-9f94-74dcac73fcbe.png)

Even getting around this, the Tiler mode has far fewer features than the Bricks node that make it really valuable, such as Position X and Y nodes and Normal-like information that in the Ghibli rebuild I was trying would be useful in re-lighting and layering additional effects.

**Comment by RodZill4** [comment]
A CustomUV update is probably the right solution to this problem (so other patterns can benefit from it).
