### ISSUE TITLE
App Crashes when assigning a parameter to multiple node properties

### ISSUE THREAD

**Issue by Takanu** [RodZill4/material-maker#164]
**Material Maker version:**
0.92, all tested 0.93 builds.

**OS/device including version:**
Windows 10.0.18363
NVIDIA GeForce GTX 1060 (3GB VRAM)
24GB DDR3 RAM
Intel Core i5-3470 CPU @ 3.20GHz

**Issue description:**
When assigning a new Parameter to a node property, OR when assigning an additional node property to an existing parameter in a sub-graph there is a chance that the application crashes.

When the Parameters node frame expands downwards randomly to accommodate content that doesnt exist, this indicates that any additional Parameter configurations will crash the application.

This can be avoided by reloading the sub-graph, either by:
- Double-clicking the sub-graph on the hierarchy list.
- Escaping to the parent of the sub-graph, and returning to the sub-graph.
- Reloading the file.

**Steps to reproduce:**
![Material Maker v0 93 2020-09-04 00-45-43](https://user-images.githubusercontent.com/9108903/92184238-8be02500-ee48-11ea-9c10-8542a2fb65c5.gif)

**Comment by Takanu** [comment]
This has returned in the official release of 0.93, same behavior as before.

**Comment by RodZill4** [comment]
@Takanu Do you have a scenario to repeat this problem ?

**Comment by Takanu** [comment]
@RodZill4 Ive made a small enough example for reproduction purposes, there's no specific method ive found to exactly recreate the crash as just using Parameter links enough will cause MM to crash.

`
{"connections":[{"from":"shape","from_port":0,"to":"graph_7","to_port":0},{"from":"graph_7","from_port":0,"to":"combine_2","to_port":0}],"nodes":[{"name":"combine_2","node_position":{"x":271.25,"y":-10},"parameters":{},"shader_model":{"code":"","global":"","includes":[""],"inputs":[{"default":"0.0","label":"","name":"in","type":"rgba"}],"instance":"","name":"Relay","outputs":[{"rgba":"$in($uv)","type":"rgba"}],"parameters":[]},"type":"shader"},{"name":"shape","node_position":{"x":-427.75,"y":-44},"parameters":{"edge":0.2,"radius":0.906667,"shape":0,"sides":2},"shader_model":{"code":"","global":"float shape_circle(vec2 uv, float sides, float size, float edge) {\n    uv = 2.0*uv-1.0;\n\tedge = max(edge, 1.0e-8);\n    float distance = length(uv);\n    return clamp((1.0-distance/size)/edge, 0.0, 1.0);\n}\n\nfloat shape_polygon(vec2 uv, float sides, float size, float edge) {\n    uv = 2.0*uv-1.0;\n\tedge = max(edge, 1.0e-8);\n    float angle = atan(uv.x, uv.y)+3.14159265359;\n    float slice = 6.28318530718/sides;\n    return clamp((size-cos(floor(0.5+angle/slice)*slice-angle)*length(uv))/(edge*size), 0.0, 1.0);\n}\n\nfloat shape_star(vec2 uv, float sides, float size, float edge) {\n    uv = 2.0*uv-1.0;\n\tedge = max(edge, 1.0e-8);\n    float angle = atan(uv.x, uv.y);\n    float slice = 6.28318530718/sides;\n    return clamp((size-cos(floor(1.5+angle/slice-2.0*step(0.5*slice, mod(angle, slice)))*slice-angle)*length(uv))/(edge*size), 0.0, 1.0);\n}\n\nfloat shape_curved_star(vec2 uv, float sides, float size, float edge) {\n    uv = 2.0*uv-1.0;\n\tedge = max(edge, 1.0e-8);\n    float angle = 2.0*(atan(uv.x, uv.y)+3.14159265359);\n    float slice = 6.28318530718/sides;\n    return clamp((size-cos(floor(0.5+0.5*angle/slice)*2.0*slice-angle)*length(uv))/(edge*size), 0.0, 1.0);\n}\n\nfloat shape_rays(vec2 uv, float sides, float size, float edge) {\n    uv = 2.0*uv-1.0;\n\tedge = 0.5*max(edge, 1.0e-8)*size;\n\tfloat slice = 6.28318530718/sides;\n    float angle = mod(atan(uv.x, uv.y)+3.14159265359, slice)/slice;\n    return clamp(min((size-angle)/edge, angle/edge), 0.0, 1.0);\n}\n\n","inputs":[{"default":"1.0","label":"3:","longdesc":"An input map that affects the shape size","name":"radius_map","shortdesc":"Size map","type":"f"},{"default":"1.0","label":"","longdesc":"An input map that affects the edge width","name":"edge_map","shortdesc":"Edge map","type":"f"}],"instance":"","longdesc":"A node that draws a white shape on a black background","name":"Shape","outputs":[{"f":"shape_$(shape)($(uv), $(sides), $(radius)*$radius_map($uv), $(edge)*$edge_map($uv))","longdesc":"Shows a white shape on a black background","shortdesc":"Output","type":"f"}],"parameters":[{"default":0,"label":"","longdesc":"The type of shape drawn by this node","name":"shape","shortdesc":"Shape","type":"enum","values":[{"name":"Circle","value":"circle"},{"name":"Polygon","value":"polygon"},{"name":"Star","value":"star"},{"name":"Curved star","value":"curved_star"},{"name":"Rays","value":"rays"}]},{"control":"None","default":3,"label":"","longdesc":"The number of sides of the generated shape (unused for Circle)","max":32,"min":2,"name":"sides","shortdesc":"Sides count","step":1,"type":"float"},{"control":"None","default":1,"label":"","longdesc":"The size of the generated shape","max":1,"min":0,"name":"radius","shortdesc":"Shape size","step":0.01,"type":"float"},{"control":"None","default":0.2,"label":"","longdesc":"The edge width of the generated shape","max":1,"min":0,"name":"edge","shortdesc":"Edge width","step":0.01,"type":"float"}]},"type":"shader"},{"connections":[{"from":"graph","from_port":0,"to":"tiler_color","to_port":1},{"from":"tiler_color","from_port":0,"to":"transform2_3","to_port":0},{"from":"transform2_3","from_port":0,"to":"curve","to_port":0},{"from":"curve","from_port":0,"to":"gen_outputs","to_port":0},{"from":"gen_inputs","from_port":0,"to":"tiler_color","to_port":0}],"label":"Branch Builder","longdesc":"","name":"graph_7","node_position":{"x":-68.75,"y":-30},"nodes":[{"name":"curve","node_position":{"x":1780,"y":180},"parameters":{"ax":0.202,"ay":-0.308,"bx":-0.06,"by":-0.036,"cx":-0.002,"cy":0.33,"repeat":1,"width":0.7},"seed_value":21530,"type":"curve"},{"name":"transform2_3","node_position":{"x":1520,"y":179},"parameters":{"mode":0,"rotate":90,"scale_x":1,"scale_y":1,"translate_x":0,"translate_y":0},"type":"transform2"},{"connections":[{"from":"shape_3","from_port":0,"to":"scale_4","to_port":0},{"from":"shape_3","from_port":0,"to":"scale_3","to_port":0},{"from":"shape_3","from_port":0,"to":"scale_2","to_port":0},{"from":"shape_3","from_port":0,"to":"scale","to_port":0},{"from":"scale_3","from_port":0,"to":"graph_6","to_port":0},{"from":"scale","from_port":0,"to":"graph_6","to_port":1},{"from":"scale_4","from_port":0,"to":"graph_6","to_port":2},{"from":"scale_2","from_port":0,"to":"graph_6","to_port":3},{"from":"graph_6","from_port":0,"to":"gen_outputs","to_port":0}],"label":"Margin Box","longdesc":"Controls the exact size of the box by the distance each side is from the edge of the UV space.  Useful in specific masking operations.","name":"graph","node_position":{"x":1010.144226,"y":327.828003},"nodes":[{"name":"shape_3","node_position":{"x":-20,"y":880},"parameters":{"edge":0,"radius":1,"shape":1,"sides":4},"seed_value":35477,"type":"shape"},{"name":"scale","node_position":{"x":260,"y":780},"parameters":{"cx":0,"cy":-0.5,"scale_x":1,"scale_y":0.68},"type":"scale"},{"name":"scale_3","node_position":{"x":260,"y":640},"parameters":{"cx":0,"cy":0.5,"scale_x":1,"scale_y":0.68},"type":"scale"},{"connections":[{"from":"gen_inputs","from_port":0,"to":"blend","to_port":0},{"from":"gen_inputs","from_port":1,"to":"blend","to_port":1},{"from":"gen_inputs","from_port":2,"to":"blend_2","to_port":1},{"from":"gen_inputs","from_port":3,"to":"blend_2_2","to_port":1},{"from":"gen_inputs","from_port":4,"to":"blend_2_2_2","to_port":1},{"from":"blend","from_port":0,"to":"blend_2","to_port":0},{"from":"blend_2","from_port":0,"to":"blend_2_2","to_port":0},{"from":"blend_2_2","from_port":0,"to":"blend_2_2_2","to_port":0},{"from":"gen_inputs","from_port":5,"to":"blend_2_2_2_2","to_port":1},{"from":"gen_inputs","from_port":6,"to":"blend_2_2_2_2_2","to_port":1},{"from":"gen_inputs","from_port":7,"to":"blend_2_2_2_2_2_2","to_port":1},{"from":"blend_2_2_2","from_port":0,"to":"blend_2_2_2_2","to_port":0},{"from":"blend_2_2_2_2","from_port":0,"to":"blend_2_2_2_2_2","to_port":0},{"from":"blend_2_2_2_2_2","from_port":0,"to":"blend_2_2_2_2_2_2","to_port":0},{"from":"blend","from_port":0,"to":"switch","to_port":0},{"from":"blend_2","from_port":0,"to":"switch","to_port":1},{"from":"blend_2_2","from_port":0,"to":"switch","to_port":2},{"from":"blend_2_2_2","from_port":0,"to":"switch","to_port":3},{"from":"blend_2_2_2_2","from_port":0,"to":"switch","to_port":4},{"from":"blend_2_2_2_2_2","from_port":0,"to":"switch","to_port":5},{"from":"blend_2_2_2_2_2_2","from_port":0,"to":"switch","to_port":6},{"from":"switch","from_port":0,"to":"gen_outputs","to_port":0},{"from":"gen_inputs","from_port":8,"to":"blend","to_port":2},{"from":"gen_inputs","from_port":8,"to":"blend_2","to_port":2},{"from":"gen_inputs","from_port":8,"to":"blend_2_2","to_port":2},{"from":"gen_inputs","from_port":8,"to":"blend_2_2_2","to_port":2},{"from":"gen_inputs","from_port":8,"to":"blend_2_2_2_2","to_port":2},{"from":"gen_inputs","from_port":8,"to":"blend_2_2_2_2_2","to_port":2},{"from":"gen_inputs","from_port":8,"to":"blend_2_2_2_2_2_2","to_port":2}],"label":"Mega Blend","longdesc":"Blends up to 8 inputs together sequentially, using the same operation\nand opacity level.","name":"graph_6","node_position":{"x":559.183838,"y":857.65033},"nodes":[{"name":"gen_inputs","node_position":{"x":-2440,"y":780},"parameters":{},"ports":[{"group_size":0,"name":"Mix 1","type":"rgba"},{"group_size":0,"name":"Mix 2","type":"rgba"},{"group_size":0,"name":"Mix 3","type":"rgba"},{"group_size":0,"name":"Mix 4 ","type":"rgba"},{"group_size":0,"name":"Mix 5","type":"rgba"},{"group_size":0,"name":"Mix 6","type":"rgba"},{"group_size":0,"name":"Mix 7","type":"rgba"},{"group_size":0,"name":"Mix 8","type":"rgba"},{"group_size":0,"name":"Opacity","type":"f"}],"type":"ios"},{"name":"gen_outputs","node_position":{"x":-880,"y":1200},"parameters":{},"ports":[{"group_size":0,"name":"Out","type":"rgba"}],"type":"ios"},{"name":"gen_parameters","node_position":{"x":-880,"y":1000},"parameters":{"param0":2,"param1":1,"param2":2},"type":"remote","widgets":[{"label":"Blend","linked_widgets":[{"node":"blend","widget":"blend_type"},{"node":"blend_2","widget":"blend_type"},{"node":"blend_2_2","widget":"blend_type"},{"node":"blend_2_2_2","widget":"blend_type"},{"node":"blend_2_2_2_2","widget":"blend_type"},{"node":"blend_2_2_2_2_2","widget":"blend_type"},{"node":"blend_2_2_2_2_2_2","widget":"blend_type"}],"longdesc":"The blend mode applied to all Blend operations.","name":"param0","type":"linked_control"},{"label":"Opacity","linked_widgets":[{"node":"blend_2","widget":"amount"},{"node":"blend","widget":"amount"},{"node":"blend_2_2","widget":"amount"},{"node":"blend_2_2_2","widget":"amount"},{"node":"blend_2_2_2_2","widget":"amount"},{"node":"blend_2_2_2_2_2","widget":"amount"},{"node":"blend_2_2_2_2_2_2","widget":"amount"}],"longdesc":"The opacity level applied to all Blend operations.","name":"param1","type":"linked_control"},{"label":"Blend Switch","linked_widgets":[{"node":"switch","widget":"source"}],"longdesc":"The number of blend operations in active use.  Slide up for more,\ndown for less.","name":"param2","type":"linked_control"}]},{"name":"blend","node_position":{"x":-1969.137695,"y":791.51178},"parameters":{"amount":1,"blend_type":2},"type":"blend"},{"name":"blend_2","node_position":{"x":-1887.137695,"y":922.011719},"parameters":{"amount":1,"blend_type":2},"type":"blend"},{"name":"blend_2_2","node_position":{"x":-1799.137695,"y":1044.011719},"parameters":{"amount":1,"blend_type":2},"type":"blend"},{"name":"blend_2_2_2","node_position":{"x":-1687.137695,"y":1167.011719},"parameters":{"amount":1,"blend_type":2},"type":"blend"},{"name":"blend_2_2_2_2","node_position":{"x":-1610.137695,"y":1280.011719},"parameters":{"amount":1,"blend_type":2},"type":"blend"},{"name":"blend_2_2_2_2_2","node_position":{"x":-1530.137695,"y":1397.011719},"parameters":{"amount":1,"blend_type":2},"type":"blend"},{"name":"blend_2_2_2_2_2_2","node_position":{"x":-1458.137695,"y":1522.011719},"parameters":{"amount":1,"blend_type":2},"type":"blend"},{"name":"switch","node_position":{"x":-1200,"y":1000},"parameters":{"choices":7,"outputs":1,"source":2},"type":"switch"}],"parameters":{"param0":2,"param1":1,"param2":2},"shortdesc":"","type":"graph"},{"name":"scale_4","node_position":{"x":260,"y":920},"parameters":{"cx":0.5,"cy":0,"scale_x":1,"scale_y":1},"type":"scale"},{"name":"scale_2","node_position":{"x":260,"y":1060},"parameters":{"cx":-0.5,"cy":0,"scale_x":1,"scale_y":1},"type":"scale"},{"name":"gen_inputs","node_position":{"x":-54,"y":548.941711},"parameters":{},"ports":[],"type":"ios"},{"name":"gen_outputs","node_position":{"x":982.183838,"y":840.941711},"parameters":{},"ports":[{"group_size":0,"name":"Output","type":"rgba"}],"type":"ios"},{"name":"gen_parameters","node_position":{"x":663.197266,"y":593},"parameters":{"param0":0.68,"param1":0.68,"param2":1,"param3":1,"param4":0},"type":"remote","widgets":[{"label":"Up","linked_widgets":[{"node":"scale_3","widget":"scale_y"}],"name":"param0","type":"linked_control"},{"label":"Down","linked_widgets":[{"node":"scale","widget":"scale_y"}],"name":"param1","type":"linked_control"},{"label":"Left","linked_widgets":[{"node":"scale_4","widget":"scale_x"}],"name":"param2","type":"linked_control"},{"label":"Right","linked_widgets":[{"node":"scale_2","widget":"scale_x"}],"name":"param3","type":"linked_control"},{"label":"Bevel","linked_widgets":[{"node":"shape_3","widget":"edge"}],"name":"param4","type":"linked_control"}]}],"parameters":{"param0":0.68,"param1":0.68,"param2":1,"param3":1,"param4":0},"shortdesc":"Margin Box.","type":"graph"},{"name":"tiler_color","node_position":{"x":1260,"y":180},"parameters":{"fixed_offset":0,"offset":0,"opacity":0,"overlap":5,"rotate":112.599998,"scale":0,"scale_x":1,"scale_y":1,"select_inputs":1,"tx":1,"ty":13},"type":"tiler_color"},{"name":"gen_inputs","node_position":{"x":826.78418,"y":173.983994},"parameters":{},"ports":[{"group_size":0,"name":"port0","type":"rgba"}],"type":"ios"},{"name":"gen_outputs","node_position":{"x":2220,"y":180},"parameters":{},"ports":[{"group_size":0,"name":"port0","type":"rgba"}],"type":"ios"},{"name":"gen_parameters","node_position":{"x":1707.468018,"y":-78.810692},"parameters":{},"type":"remote","widgets":[]},{"color":{"a":1,"b":0,"g":0.5,"r":1,"type":"Color"},"name":"comment","node_position":{"x":1529.285034,"y":-182.349045},"parameters":{},"size":{"x":500.166626,"y":182.833328},"text":"Now create and delete a link to Scale X in the Color Tiler node, it will eventually crash (theres plenty of random ways to make MM kill itself with Parameter links :C)","title":"Comment","type":"comment"}],"parameters":{},"shortdesc":"","type":"graph"},{"color":{"a":1,"b":0,"g":0.5,"r":1,"type":"Color"},"name":"comment","node_position":{"x":-180.75,"y":-151.5},"parameters":{},"size":{"x":378,"y":261},"text":"EDIT HERE","title":"Comment","type":"comment"}]}
`
