### ISSUE TITLE
Add a Relay Node

### ISSUE THREAD

**Issue by Takanu** [RodZill4/material-maker#171]
## Feature/enhancement description

![image](https://user-images.githubusercontent.com/9108903/92983963-9c267e80-f49e-11ea-90ea-70f86fe93127.png)

Often in complex graphs youll have outputs you need to connect to one or more inputs much further away than it is, and the process to both connecting them together and ensuring the connection looks organized in the scope of the full map can be quite difficult without a pass-through or relay node.

This node has the sole function of letting you change the direction and shape of the output as it flows across your node map.  Having one similar to the Switch node where it accepts any input and makes it the output would be really nice.

### Extra Credit
As an extra, it'd be nice if this node had a way you could name it OR an auto-name system so when you see it away from the output, it's still made clear what it does.

### Potential for project organization
This would need experimentation but I feel like Relay nodes could also be used to mark the beginning of a set of nodes that perform a particular function.  Normally in a project you get big chunks that youd group and connect together in some weird way, but maybe with a Relay node you can give it a graphical column that extends out the top and bottom of it with a certain colour, and the label marks it as being the boundary to a specific set of operations.

With comments they get clumsy to organize and resize which is why I use them sparingly, but with Relays almost acting as bookmarks it might make for nicer and quicker project organization.  I'll do a few visual tests later 🤔

**Comment by RodZill4** [comment]
Maybe reroute nodes could have a name and a preview, but closing this old request.
