### ISSUE TITLE
Builtin and user library can conflict

### ISSUE THREAD

**Issue by escargot-sans-gluten** [RodZill4/material-maker#179]
**Material Maker version:** 179f922

**OS/device including version:** Ubuntu 20.04

**Issue description:**

If you save a group in your library but with an already existing library path, the existing node/group will be overriden.

Since the library is stored in a single json, it is really inconvenient to remove a single custom node.

**Steps to reproduce:**
Spawn and save a 3d sdf box as `3D/SDF/Shapes/Sphere`:
![image](https://user-images.githubusercontent.com/44414272/93212794-5a7a2a00-f763-11ea-998c-42088e005844.png)

**Comment by RodZill4** [comment]
This is the expected behavior, you can override the default library with the user library.
I have plans to be able to add/remove/enable/disable/edit libraries in the future, to make all this a lot easier.

**Comment by escargot-sans-gluten** [comment]
Oh okay.
@RodZill4 
But I am genuinely curious about the rationale behind this, what interest is there to redefine builtin behavior ?
Wouldn't the behavior be weird if one was to redefine a node used in other graphs? Couldn't that lead to unexpected/broken results?
And in general when sharing materials, isn't this going to complicate understanding the graphs if person A's Voronoi node doesn't behave like person B's one?

**Comment by RodZill4** [comment]
Whenever you add nodes from the library, those are **copied** into the material, so changing the library won't prevent you from loading materials. What's **referenced** in materials are .mmg files, so if you change those you may break existing materials.
So a Voronoi is a Voronoi. If you replace the Voronoi in your user library, you may just not be able to create that node anymore, unless you use the Tools -> Create submenu (that gives you direct access to .mmg files).

So no, there's no risk at all!
