### ISSUE TITLE
Prevent Replacing Default Library Nodes

### ISSUE THREAD

**Issue by Takanu** [RodZill4/material-maker#180]
## Feature/enhancement description
Pretty self-explanatory, sometimes when im making new library nodes ill type in the wrong thing and itll be in the wrong position until I dig into the JSON file, but worse is when it replaces a default node.  Default nodes should be protected and not so easily replaced with custom ones.

**Comment by RodZill4** [comment]
Release 0.94 will be (mainly) dedicated to libraries.
