### ISSUE TITLE
Scratches Randomly Pixelated

### ISSUE THREAD

**Issue by zauberparacelsus** [RodZill4/material-maker#181]
**Material Maker version:** 0.92 Linux

**OS/device including version:**, Manjaro Linux 5.7.19, GeForce GTX 1650 Super with nVidia driver 450.66

**Issue description:** With the Scratches texture pattern, some of the scratches will appear pixelated.  The problem becomes more apparent when you use a lower Width value.  Issue seems to be seed-dependent, as some seeds will generate no pixelation while others will generate a lot.  Most seeds seem to generate at least some pixelation.

Example Screenshot:
![image](https://user-images.githubusercontent.com/548168/94018918-244e3300-fd7f-11ea-82e5-e37885aa2e7d.png)

**Steps to reproduce:** Enable 2D Preview, then drop in a Pattern/Scratches node and move it around.  Pixelation will become quickly apparent.

**Comment by RodZill4** [comment]
This problem should already be fixed for 0.93.
Could you get a dev build (see "Actions") and tell me if it fixes the problem ? Thanks!

**Comment by zauberparacelsus** [comment]
Aye, that particular issue appears to be fixed in 0.93.

I do notice that for low width values (like 0.025), a different kind of pixelation appears, though I guess it may be a shortcoming of the algorithm used.

**Comment by RodZill4** [comment]
Hmm pixelation in this case because scratches are thinner than a pixel. A workaround would be to (create and) use an antialiasing node.

**Comment by Calinou** [comment]
@RodZill4 What about adding a "supersampling" mode that doubles the resolution the texture is rendered at then downscales it?

(This wouldn't be a node but a setting in the output node, probably.)

**Comment by zauberparacelsus** [comment]
Yeah, some kind of super-sampling setting would be more ideal, especially if you want very thin scratches like I do.

**Comment by RodZill4** [comment]
A setting in the output node would not be useful if the scratches node is connected to a buffer. A supersampling setting (that affects all rendered textures including buffers) would also be a bad idea.

**Comment by RodZill4** [comment]
Looks like a supersample node is a decent solution:
![image](https://user-images.githubusercontent.com/6957908/94986744-7eaa7900-0561-11eb-9c76-fd54706677b7.png)
![image](https://user-images.githubusercontent.com/6957908/94986750-8bc76800-0561-11eb-9fdb-2eac1700a486.png)

**Comment by RodZill4** [comment]
Now supersample is available, we can close this...
