### ISSUE TITLE
Allow exporting higher texture resolutions (more than 4K)

### ISSUE THREAD

**Issue by unfa** [RodZill4/material-maker#186]
Currently Material Maker allows to export textures with up to 4K resolution.
I wish 8K and 16K were also possible.
Is that doable? What do you think?

**Comment by Calinou** [comment]
Out of curiosity, what do you need 8K and 16K textures for?

It's likely possible to expose this, but keep in mind such textures will take a long time to generate and will use up lots of VRAM. (6+ GB of VRAM are highly recommended if you plan on exporting 8K textures.)

**Comment by RodZill4** [comment]
Hmm very long GPU operations tend to crash Godot, so I think just enabling those resolutions would not work. But it's probably possible to workaround that problem (the problem is not only export but wherever buffers are used).

But yes, I'd be curious what those huge textures will be useful for.

**Comment by bonbonmiel** [comment]
A workaround to avoid a big task could be to export multiple 2k/4k textures using mapped uvs and then stitch them together. This would make it possible to compute such textures with any hardware, at the cost of high compute time.

**Comment by RodZill4** [comment]
OK, just tried to export a 16K image with the code we have today. Had to reboot my PC (my GPU is an old nvidia 660)...
Exporting multiple textures is how I'd do it, but this is low priority until I understand why huge textures are needed.

**Comment by unfa** [comment]
Hey! I've requested this because I wanted to process some images for a Blender animation. Also - if I were to make textures for movies/VFX it could be a good option, as highest possible fidelity is a requirement there. In games - I'd rarely use such huge textures (though it may still be a valid use case), but Material Maker can be used for more than just games!

**Comment by unfa** [comment]
Could this be possible by tiling?
The software could render 4 4K tiles for each texture, then just stitch hem together if processing more than 4K at once is not going to work.
I think for some use cases, like movies, animations or extremely large textures for game terrains, this would be fantastic.
