### ISSUE TITLE
Improve the tiling map view

### ISSUE THREAD

**Issue by unfa** [RodZill4/material-maker#190]
**Feature/enhancement description:**

The current tiling view is making it extremely hard to tell if the texture is tiling properly or not, because the lines completely obscure the edges of the previewed map. 

I think a much better solution would be to truncate these lines so that they are shown outside of the texture and away from it's borders, so that the user can tell if they can see the seam on their own or not. 

![Mockup](https://user-images.githubusercontent.com/491704/95726910-ccb62f80-0c79-11eb-8646-df41564a18a8.png)

Right now I find the tiling view pretty much useless, because I can't tell if the map is tiling anyway, having the lines in the way.

What do you think?

**Comment by RodZill4** [comment]
I completely agree. I have a few ideas for improvements of this 2D view anyway (make it possible to zoom/pan, and make it possible to see beyond the limits of the image without wrapping it).

**Comment by unfa** [comment]
Oh, yes, zoom/pan would be awesome too.
Thank you!
