### ISSUE TITLE
Autosave / Crash Recovery

### ISSUE THREAD

**Issue by unfa** [RodZill4/material-maker#192]
I've just lost another 30 minutes of work in Material Maker due to a random crash and the fact that I got into a flow and forgot to compulsively smash Ctrl+S every time I do anything,

Please. For the sake of mental health - implement a crash recovery system that'll automatically save progress every minute and prompt users to restore the autosave copy when the program is run again after the crash.

**Comment by RodZill4** [comment]
I'd rather have a crashless Material Maker, but this is just too easy to implement.

**Comment by unfa** [comment]
Well, we all would prefer that :D
And I really appreciate your work - I've been looking for such a program for years, and I've finally found it!

I think all creative programs need crash recovery as a safety net, because software is very complex and there's inevitably situations where the program will crash - all software of sufficient complexity crashes. But handling that gracefully ensures users they are not going to be hurt by the software. And there's nothing more soul-crushing to an artist, than seeing his work go down the drain of data loss :D

Please do implement this!

**Comment by RodZill4** [comment]
@unfa There should be basic recovery on master (you can grab a dev build there: https://github.com/RodZill4/material-maker/actions/runs/305265137). Saves every 15 seconds. Not sure it won't suggest to recover when no crash occurred, so please be aware you cannot trust this for now, and don't hesitate to report weird behavior.

**Comment by unfa** [comment]
Fantastic! I'll start testing this!
Thank you!

**Comment by unfa** [comment]
I've tested it today and it did rescue my progress after multiple segfaults!

**Comment by RodZill4** [comment]
Great. Did not have much time to test it more myself yet.
