### ISSUE TITLE
Sharing a material I made plus my thoughts about Material Maker and how to improve it

### ISSUE THREAD

**Issue by unfa** [RodZill4/material-maker#193]
Hi! I've started doing some work in Material Maker and I love it.

Here's one of the materials I've made recently - I release it under CC-0 - enjoy!

![image](https://user-images.githubusercontent.com/491704/95895589-307c4d80-0d8b-11eb-8a7b-bd090bd8d1a2.png)

[unfa-Concrete_Wall.ptex.zip](https://github.com/RodZill4/material-maker/files/5373093/unfa-Concrete_Wall.ptex.zip)

![graph](https://user-images.githubusercontent.com/491704/95896784-1c395000-0d8d-11eb-8c63-c1bcfb49b5c4.png)

My overall feeling is that it's very powerful, but the UI and UX need work - I find it especially difficult to work with large node graphs. Just panning and zooming the node graph is difficult.
I know a lot of these limitations come from Godot - maybe material Maker could become a driving force in improving it upstream?

I think I can manage much more complex node graphs in Blender than in Material Maker, because:

- I can zoom in and out without much limitation
- I can use dot (no-op) nodes to create visually readable DAG paths (like PCBs) instead of getting tangled in unwieldy noodles that cross each other in every direction
- I can use panels to group nodes visually and make it easier to move these groups around
- I can drag a node onto a noodle to insert it between two other nodes
- I can duplicate a node with it's original inputs staying connected
- I can cut the noodles instead of disconnecting them one by one
- I can create groups and re-use node groups much more easily, with finer control still being there

I think one of the easiest ways to improve this node editing experience is by allowing the users to zoom out far more.
Right now I feel like hitting my head on a low ceiling all the time when I try to zoom out more.

Also - a mini map of the node graph with the ability to pan with it would be very helpful.

I'm excited to see he Workflow nodes, trying to implement a way of merging sub-materials together - it'd be way easier to work this way instead of manually affecting every PBR map of my material by hand for every layer of detail. However I was unable to understand how these are supposed to work and how to use them.

Now - these are pretty fresh notes, I've been using Material Maker for about a week now - I am very, very excited for it, and it already can do amazing things, but I feel there's a need for many quality of life improvements and helping users manage large graphs.

Thank you for creating this software, and making it free for everyone.
This is wonderful!

PS: I'm sorry if this is a wrong place to post such a letter. I'll happily move it somewhere if need be.

**Comment by Calinou** [comment]
A lot of the changes you've requested must be done in GraphEdit/GraphNode, which is known to be a very complex GUI node in Godot. There are many [proposals](https://github.com/godotengine/godot-proposals/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+graphedit+label%3Atopic%3Agui+) about it. The main "driving forces" behind GraphEdit development are visual scripting and the visual shader editor.

Since many of these involve breaking compatibility, this can't be done before Godot 4.0 is released. And since these nodes are not a development priority, they may not change significantly in 4.0 either.

**Comment by unfa** [comment]
Thanks @Calinou - I understand most of this needs to be addressed in Godot itself, and I also expect porting Material Maker to Godot 4 is going to be a major task once it's out.

I think text readability is not a concern when zoomed way back out. What I want to see is the layout of nodes. The structure -being able to zoom out and in with no limits lets me build a mental image of the node graph and manage them better, this is handicapped right now and it's difficult to find your way around large graphs.

Maybe I should start using groups aggressively to mitigate that problem, though they work way different than in Blender so I'm not sure how to use them properly right now.

They are probably something I should really stat using going forward.

**Comment by RodZill4** [comment]
Hmm I wrote Material Maker with some of those limitations in mind. So I totally agree that those improvements should be made, but **you should definitely use groups in such a huge graph**. You can use the comment node to document your graph as well, it is resizable and you can choose the background color (and yes it needs more love from me because editing the text is still a PITA).

Anyway, thanks for testing the "screenshot" feature with a real life example, and thanks for sharing this awesome material!

And yes porting this to Godot 4 will be a lot of work, but **I just can't wait**. Multiple windows, probably new possibilities with shaders... This Godot release will be awesome.

**Comment by RodZill4** [comment]
@unfa BTW, would it be possible for you to share your material in the subreddit? Would be a pity to hide it in a feature request...

**Comment by unfa** [comment]
I'd totally love to share this material there - could you give me a link?

**Comment by RodZill4** [comment]
There's an entry in the Help menu for the subreddit.

**Comment by unfa** [comment]
Posted on Reddit:
https://www.reddit.com/r/MaterialMaker/comments/jaobw6/a_weathered_concrete_wall_material_made_in/

I don't know why my account has a random name. I tkink I'll delete it and create a new one, but I don't have time to do that right now.

**Comment by Jummit** [comment]
> I can use dot (no-op) nodes to create visually readable DAG paths (like PCBs) instead of getting tangled in unwieldy noodles that cross each other in every direction
I can drag a node onto a noodle to insert it between two other nodes
I can cut the noodles instead of disconnecting them one by one

These would be possible if godotengine/godot#40513 would be merged.

**Comment by RodZill4** [comment]
@Jummit Do you think this PR will be merged? When?

**Comment by Jummit** [comment]
It depends on an engine rendering fix, and even if that is merged, it'll take a while.

**Comment by RodZill4** [comment]
Hmm maybe we could fork Godot to get those fixes early. Material Maker will need EXR support in runtimes anyway (and a way of getting an error message from shaders would also help a lot).

**Comment by Calinou** [comment]
> @Calinou , is there a way I can force Godot to include tinyexr when compiling runtime execs (non-tool), or do I have to modify config.py in the module?

Import functionality isn't included in non-editor builds to decrease binary sizes. Itg would require a pretty significant amount of work to allow building non-editor builds with import functionality; see https://github.com/godotengine/godot-proposals/issues/1658.

**Comment by Calinou** [comment]
A built-in GraphEdit minimap is being worked on in https://github.com/godotengine/godot/pull/43416.

**Comment by fire** [comment]
I second Image.load_exr_from_buffer() for run-time EXR loading https://github.com/godotengine/godot-proposals/issues/676

**Comment by RodZill4** [comment]
Many issues here were fixed (minimap, reroute nodes...)
