### ISSUE TITLE
Material Maker 0.93 crashes on startup on Windows 10

### ISSUE THREAD

**Issue by webwarrior-ws** [RodZill4/material-maker#195]
After splash screen, when main window opens, the application suddenly closes.
Version 0.92 works just fine on the same machine.

**Comment by RodZill4** [comment]
Hmm @webwarrior-ws, could you please try a dev build? A few problems have been fixed since the release (yours may be related to a rare problem that was reported under Linux).
https://github.com/RodZill4/material-maker/actions/runs/313589965

**Comment by webwarrior-ws** [comment]
Tried dev build, works fine.

**Comment by RodZill4** [comment]
OK, nice. I think this software needs a 0.93p1. Will wait one more week so I get a few more bug reports...

**Comment by Zeepnely** [comment]
@RodZill4  this same issue is happening to me as well, but the link you sent to the dev build displays a 404. is there any other solution you would have for me?

**Comment by RodZill4** [comment]
> @RodZill4 this same issue is happening to me as well, but the link you sent to the dev build displays a 404. is there any other solution you would have for me?

This is related to a very old release. I guess you're using 1.3 (and otherwise, you should download it).
If MM crashes when starting, you probably have an AMD GPU, and updating your drivers should fix the problem.
