### ISSUE TITLE
Some unwanted information when generating star shape

### ISSUE THREAD

**Issue by Tar0x** [RodZill4/material-maker#196]
**Material Maker version:**
0.93

**OS/device including version:**
Win10

**Issue description:**
I guess MM is generating some inwanted artifacts when using simple star shape, see the screeshot.https://i.imgur.com/buH9SjF.png
Do you see those 2 dilated "pixels"?

**Steps to reproduce:**

**Comment by RodZill4** [comment]
@Tar0x This should be fixed now. Would it be possible for you to check the fix in this dev build? https://github.com/RodZill4/material-maker/actions/runs/316154092
Thanks!

**Comment by Tar0x** [comment]
It works as it should, thank you :) 👍
