### ISSUE TITLE
Changing model / envinronment is now less intuitive

### ISSUE THREAD

**Issue by Pio64** [RodZill4/material-maker#197]
Version 0.93 changed the way users can switch models and environments. It now requires more clicks to use this basic functionality. For `Model` button it makes sense, because more options were added, but `Environment` just displays another menu with one option, so it requires extra clicking for no reason.

![material-maker-environment](https://user-images.githubusercontent.com/51057487/96612655-89993380-12ed-11eb-8010-e17877e1b323.png)

**Comment by RodZill4** [comment]
Future releases wil have more options in that menu.
