### ISSUE TITLE
Discord server?

### ISSUE THREAD

**Issue by Tar0x** [RodZill4/material-maker#199]
What about making a Discord server for Material maker? Many people may welcome this for faster communication between artists and sharing content. :) I can help to moderate it if needed.

**Comment by RodZill4** [comment]
Hmm Material Maker already has a subreddit. I don't think discord would be better for sharing materials and nodes.

**Comment by me2beats** [comment]
I think discord server would be a great place (especially to new users) for asking questions and sharing stuff

**Comment by RodZill4** [comment]
This might be true for asking questions, but discord would be really bad (worse than reddit) for sharing stuff.
