### ISSUE TITLE
mouse got captured when drag Transform

### ISSUE THREAD

**Issue by puppetmaster-** [RodZill4/material-maker#2]
System: Windows 7, Nvidia GT 610 
![image](https://user-images.githubusercontent.com/10463138/44618534-02201900-a878-11e8-96e2-fab2df227114.png)

**Comment by RodZill4** [comment]
OK, seems this is a problem in Godot (#11893). I submitted a PR so it should be fixed in 3.1. I also added a workaround in this project so the mouse pointer is released when dropping the node (it is just dropped at the center of the GraphEdit, still a bit annoying).

**Comment by puppetmaster-** [comment]
thanks for reporting the issue

**Comment by RodZill4** [comment]
Hmm I'm afraid that problem is back, but not sure which widget type causes it...

**Comment by RodZill4** [comment]
Didn't notice the problem for a while... Let's close it for now.
