### ISSUE TITLE
Lounge thread on /r/materialmaker has been archived and can't be replied to anymore

### ISSUE THREAD

**Issue by Calinou** [RodZill4/material-maker#200]
The lounge thread on /r/materialmaker has been archived. This is because the thread more than 6 months old now (having been created on 2020-04-21). Reddit automatically archives all threads more than 6 months old, and there's no way to configure that on a per-subreddit basis as far as I know.

https://www.reddit.com/r/MaterialMaker/comments/g5j2ha/rmaterialmaker_lounge/

**Comment by RodZill4** [comment]
@Calinou I added a chat room. Can you see it, or do I have to advertise it?

**Comment by Calinou** [comment]
I can't see it when using old.reddit.com (which I still use today).

When using new.reddit.com, I can see it in the sidebar (scroll down a bit) but it's not particularly easy to find.

**Comment by RodZill4** [comment]
Discord is where everything happens now...
