### ISSUE TITLE
Moving node on screen changes the pattern

### ISSUE THREAD

**Issue by dunawayc** [RodZill4/material-maker#201]
Version 0.93
Windows 10 (2004, Build 19041.572)

I'm not sure if this is a bug or not.  I loaded up the software and then loaded the example Mosaic material.

When I grab the Voronoi node and move it around, the texture changes as if the position of the on screen node affects it.  Is this be design?

Steps to reproduce:

1.  Start Material Maker.
2.  Open the example Mosaic material.
3.  Grab the Voronoi node and just drag it around the screen.
4.  Notice that the texture changes as you move the node around.

**Comment by RodZill4** [comment]
Yes it is a feature, moving random nodes rerolls their seed.
But it will soon be optional (it's very nice for small material graphs, but not when the graph becomes too big). Seeds will be rerolled when clicking on the "dice" button.
