### ISSUE TITLE
Change the behaviour of LMB dragging over parameters number

### ISSUE THREAD

**Issue by Tar0x** [RodZill4/material-maker#205]
**Change the behaviour of LMB dragging over parameter number to select decimals instead of behaving as a slider.**
I know that it's possible to doubleclick to select whole number, but sometimes it behaves like slider, so basically I end up with changing a mll number between those clicks. You may LMB drag on property name to behave as a slider. See this for example https://youtu.be/Tsv8UGqDibc?t=767 .... but with LMB and without those multiple of ten :)

**RodZill4's respond:**

> there is no (not always at least) property name for float input controls. But it's certainly possible to disable the drag behavior when the text entry has the focus.

Yes please, it definitely would help for float parameters :)

**Comment by RodZill4** [comment]
Cannot do much more for that widget. :(
