### ISSUE TITLE
Opportunity to rotate HDRI

### ISSUE THREAD

**Issue by Tar0x** [RodZill4/material-maker#206]
**Opportunity to rotate HDRI**
This one is self explanatory.

**RodZill4's respond:**

> You can already rotate the camera and the object. Not sure it's useful.

It is usefull, because if you rotate camera or the object, the whole "scenery" is changing. But if someone is building specular texture, he wants to see how those reflections are interacting with the material, how they are sliding along the surface without changing the view angle of the material. (I hope it makes sense :) )

**Comment by bonbonmiel** [comment]
@RodZill4 here is what it would look like.
With a new environment, this can be used to higlight bumps or reflections as @Tar0x pointed out:
![rotate_hdri_3](https://user-images.githubusercontent.com/71937306/97223612-4ef13880-17d0-11eb-838e-de9ebbf6ec2e.gif)
This can also test contrast between lit/shadowed areas:
![rotate_hdri_2](https://user-images.githubusercontent.com/71937306/97223217-c2467a80-17cf-11eb-872d-73f82502c4ed.gif)

I find this can be more useful than rotating the object so I tried replacing this by that.
What do you think?

**Comment by Tar0x** [comment]
Oh, this is awesome! <3 But rotating with the objects is also usefull, especially for testing displacement :)

**Comment by RodZill4** [comment]
Rotating the environment could just be another modifier (Control?).

**Comment by bonbonmiel** [comment]
![rotate_commands](https://user-images.githubusercontent.com/71937306/97288530-3b80b480-1846-11eb-8cbc-ba9fd4e0f580.gif)
Done.
I can't open a PR right now, any comment before I do so?

**Comment by RodZill4** [comment]
Did you use the Control modifier?

**Comment by bonbonmiel** [comment]
@RodZill4 yeah. `no modifier` rotates the camera, `shift` rotates the object, `control` rotates both (thus making it look like we're rotating the sky). `control` wins over `shift` when both are pressed.

I just did some more testing and here are a few notes I think can be discussed here:
- The `rotate` animation resets the object rotation when playing. I don't know how it should behave in that case (rotate along global y, object y or camera y? etc) but this could be solved by replacing the animation by code.
![rotate_resets](https://user-images.githubusercontent.com/71937306/97298110-42fa8a80-1853-11eb-9001-3017d4a16836.gif)

- Having a "reset rotation" button could be useful.

**Comment by Tar0x** [comment]
I guess it would be most usefull to keep rotating along camera Y, so it would look like that only HDRI is rotating (as you said before) :)

**Comment by RodZill4** [comment]
Fixed
