### ISSUE TITLE
Add new basic shape node: crescent

### ISSUE THREAD

**Issue by Tar0x** [RodZill4/material-maker#207]
**Add new basic shape node: crescent**
Some sort of navette (marquise) shape that would be superusefull for making leaves and other foliage stuff.

**RodZill4's respond:**

> You know you can create groups and add them to your user library, right? Sure we can add more shapes, but I want users to reuse (and share) whatever they create as much as possible. ;) But yes, the more, the merrier.

I will let it here and hope, that it will be in some of the future official builds :)

**Comment by RodZill4** [comment]
@TarOx please don't hesitate to submit useful shapes, so I can include them in future releases. ;)

Just one rule: they should be simple (no more than 5 parameters) and useful to get stuff done quickly for beginners.
