### ISSUE TITLE
Zooming out with scrollwheel instead with scrollwheel+ctrl

### ISSUE THREAD

**Issue by Tar0x** [RodZill4/material-maker#210]
**Zooming out with scrollwheel instead with scrollwheel+ctrl**
I guess there's more need to zoom in/out than scrolling down, even in this program, where the graph flows from left to right instead from top to bottom

**RodZill4's respond:**

> That behavior is in Godot, not sure if I can disable it.

**Comment by AsciiRebellion** [comment]
Hello! I would like to second this request. You say it is default behavior of Godot, so it might be hard to change. This is a significant frustration when interacting with graphs and alternating between programs.

**Comment by melvixiodf** [comment]
I second this but it seems this can't be changed. Its just way easier to scroll to zoom when using a mouse with most 3d softwares out there.

**Comment by RodZill4** [comment]
LOL ! It's actually possible since you can modify the event when handling it to modify the default behavior.
Had to use that approach for another feature, but didn't think of applying it here.

**Comment by melvixiodf** [comment]
@RodZill4 Thank you.
