### ISSUE TITLE
More export options

### ISSUE THREAD

**Issue by Tar0x** [RodZill4/material-maker#212]
Such as ability to choose specific channel for storing information (useful for RGB stacking channels such as metalic, roughness and height into one texture). Export textures from default material output node checkbox .... most of the time I use those export nodes, because of more customization and I find it a bit useless, because export from material output node clutters the folder with unnesessary diplicate textures i don't want to have so I have to delete them later.

**RodZill4's respond:**
> Hmm I have ideas for export, such as adding parameters. There could be a "Custom" export option that don't export anything from Material. You could add it yourself easily if you don't mind hacking the material.mmg file.

Yes, it would be really cool to have this checkbox for not exporting anything from material node. I am just an artist, so I don't wanna break it :D

**Comment by TheRektafire** [comment]
Personally I would like to see support for blender principled bsdf export added, I was just making a material and was going to import it into blender to apply to the model but then I saw there was no blender export option :(

**Comment by RodZill4** [comment]
@TheRektafire Is there a file format for those principled BSDF materials? I cannot find a menu to import/export materials in Blender.

**Comment by Tar0x** [comment]
> Personally I would like to see support for blender principled bsdf export added, I was just making a material and was going to import it into blender to apply to the model but then I saw there was no blender export option :(

It's not needed. Even there's not something like "blender material", so every material to be shared is just .blend file with the material in it. BUT! It's easy to export textures for Unreal (it does not create any unwanted stuff like .meta files for Unity...just textures) and then with node wrangler addon enabled (comes with Blender, just needs to be enabled) create a material, select your Principled BSDF and by pressing ctrl+shift+T it will open file browser. Just select previously exported textures and Blender will make PBR setup for you (automaticaly connect nodes and set up non-color option to greyscale maps and normal). It's super easy and event faster to do it than reading this description I've just wrote :)

**Comment by RodZill4** [comment]
@Tar0x Is the Unreal export EXACTLY what's needed for Blender? It's easy to add new export targets, so if Blender can benefit from its own target, there's no reason not to provide it (and Blender deserves its own export anyway). I just don't know Blender enough to answer this question.

**Comment by Tar0x** [comment]
@RodZill4 Not really, but it export only textures (not, like those meta files for Unity (I havent tried exporting using godot settings)). I am still waiting for better export options tho (user custom channel packing and not exporting those default settings while using export nodes) :)

**Comment by warriormaster12** [comment]
@RodZill4 is it possible to add an option to just export all output textures instead of exporting materials?

**Comment by Tar0x** [comment]
I am closing this one as custom exports were added
