### ISSUE TITLE
Add curves node

### ISSUE THREAD

**Issue by Tar0x** [RodZill4/material-maker#213]
Please, add curves node. It's usefull not only for color correction, but also for shaping custom bevel profies. 
![image](https://user-images.githubusercontent.com/73115159/97112146-f2fcb600-16e2-11eb-8612-1f6294b8b229.png)

**Comment by wojtekpil** [comment]
There is this project: https://github.com/newold3/PathEditor It could be useful for something like this. I don't know about Curve editors built in directly in godot as a node (only those in Godot Editor itself, but I don't think you can use them in your project).

**Comment by Tar0x** [comment]
This is cool, but I mean color grading curves. I know, that there's colorize ramp or tones, but it's really hard to achive precise profiles with that. And also color grading curves are really powerful for color corrections, as you can tweak anything with them. Also I am aware, that there's a profile node in MM, but it's only for preview heh? Check this quick demo I made in Blender: https://www.youtube.com/watch?v=bglSccQlmEg&feature=youtu.be&ab_channel=Tarox%27sPlaylists

**Comment by Tar0x** [comment]
@wojtekpil https://www.youtube.com/watch?v=93MMNFrhX1k&ab_channel=XolotlStudio This is exactly what I was talking about :)
