### ISSUE TITLE
Click zones when zoomed out

### ISSUE THREAD

**Issue by Tar0x** [RodZill4/material-maker#217]
**Material Maker version:**
0.93

**OS/device including version:**
Win10

**Issue description:**
Click zones are messed up when zoomed out. When zoom level is 1:1, everything behaves correctly, but the more you zoom out, the more click zones are shifted. For example I grab a node like 2 cm away from the point I click onto and this is the same with ports. Sometimes I have to like 5 times try to pull a connection line out of it. :)

**Comment by Calinou** [comment]
Out of curiosity, are you using Material Maker in hiDPI mode? (This is likely the case if you're using a 4K monitor or a small 1440p monitor.)

**Comment by Tar0x** [comment]
I am not aware of that. I am using standard 1920x1080 notebook display.

**Comment by wojtekpil** [comment]
Same here. I think this it a problem with GraphNode itself in Godot. My setup: Linux, elementary OS Hera and standard 1920x1080 netbook display.

**Comment by masseymo** [comment]
I have also had this issue on Mac. It seems as Tar0x said, its not just that the ports are difficult/too small to click, but they actually shift in position. Sometimes leading to accidental disconnecting of nodes. which is a real pain if that connection is from a distance on the graph or the graph is in any way complicated.

**Comment by RodZill4** [comment]
Improved a lot thanks to fixed in Godot. there's still room for improvements.
