### ISSUE TITLE
[Proposal] Quick search redesign

### ISSUE THREAD

**Issue by Tar0x** [RodZill4/material-maker#219]
**Feature/enhancement description:**
What about this UI redesign to make content inside quick search more readable? (font is different, because I could't match the font from Godot, even thought I used the same font). Basically the last object in the hierarchy chain would be bold and the rest would be darker with that arrow in the middle (I find it more readable than without the arrow). And also I would add like 2 px space between thumbnail and the text :) 

![image](https://user-images.githubusercontent.com/73115159/97439201-27ac7f80-1926-11eb-9bb9-03a466c3ea5d.png)

**Comment by RodZill4** [comment]
Good idea, but ItemLists in Godot do not support multiple text colors per item. So this needs a new custom widget.

**Comment by bonbonmiel** [comment]
I made this, it is working but it probably needs further discussion and adjustments.
Notably, some paths are too long for the popup size (this was already the case before).
Making a PR now so you can test it, any remarks?

![new](https://user-images.githubusercontent.com/71937306/98424050-cfe1e700-2090-11eb-95e2-c74f39ec062c.png)

**Comment by Tar0x** [comment]
It's great <3 Maybe I would make those spaces shorter (in front and behind the arrow) and the arrow darker. It might be good to have have that pop up window a bit wider and speaking of those long paths...when you mouseover, that text could be moving (like in train stations or buses :) )

**Comment by bonbonmiel** [comment]
![new3](https://user-images.githubusercontent.com/71937306/98482046-f02fb400-21fe-11eb-8479-5e04d8b4988d.png)
@Tar0x any feedback apreciated :)

There is still a question that needs to be answered: how should filtering behave when quick connecting? There are 3 possibilities:
 1. reset the filter
![reset filter](https://user-images.githubusercontent.com/71937306/98482299-cecfc780-2200-11eb-80be-bc4986cda7f6.gif)

 2. only reset the filter in the context of the current quick connection and bring it back after
![ignore filter](https://user-images.githubusercontent.com/71937306/98482740-ab5a4c00-2203-11eb-8cf7-43b1bb4b4f6f.gif)

 3. reuse it
![keep filter](https://user-images.githubusercontent.com/71937306/98482383-47cf1f00-2201-11eb-85a4-37fa47437c5a.gif)

I personally think 2. is the best option.


For showing the full paths, I think using tooltips is better that animated text :)

@RodZill4 what do you think about this?
Also, do you know if it could be possible (and a good idea) to plug node descriptions into the tooltips?

**Comment by RodZill4** [comment]
I think there is no good reason for keeping the filter. If you want to create the same node twice, duplicating (Control+D) is the fastest way. I vote for (1).

**Comment by Tar0x** [comment]
@bonbonmiel Tooltips are great idea! I think it's not usefull for keeping the filter. If you want the same node, you can copy it. Mostly you want another type of the filter to keep moving :) (as Rod said) Anyway great job! :)

**Comment by bonbonmiel** [comment]
(1) is it, then!
