### ISSUE TITLE
[Proposal] Get/register local variable node

### ISSUE THREAD

**Issue by Tar0x** [RodZill4/material-maker#220]
**Feature/enhancement description:**
It would be great to have similar node to this: https://wiki.amplify.pt/index.php?title=Unity_Products:Amplify_Shader_Editor/Register_Local_Var . Basically you create a variable somewhere in the graph (with register local variable node) and then you can reference it anywhere else even multiple times (with get local variable node). It's like a teleport, to prevent spaghetti-like tree :)  It's very powerful in combination with background frames.

**Comment by wojtekpil** [comment]
Isn't it something like a Remote Node? I think it works very similar.

**Comment by Tar0x** [comment]
> Isn't it something like a Remote Node? I think it works very similar.

Not much, its different. Remote node holds informations about properties, but local var nodes from amplify hold any information. Basically it's some kind of a buffer, that you can instantiate.

**Comment by RodZill4** [comment]
No it's like a teleporter for connections.
I think it's a very bad idea, as its purpose is the same as groups (make complex graphs simpler), but it will just make graphs harder to understand.
At least a good "Relay" node that helps routing long connections does not make the graph unreadable.

**Comment by wojtekpil** [comment]
Ok I think  I get it now. This is something like net labels in pcb schematics. I am not sure about it, it's something definitely possible, but it may require some effort to make.

**Comment by Tar0x** [comment]
Ok ok, it's true, that when we will have those "reroute nodes", it won't be so usefull :)
