### ISSUE TITLE
Make zooming to the center of node tree window (using ctrl+scrollwheel)

### ISSUE THREAD

**Issue by Tar0x** [RodZill4/material-maker#228]
**Material Maker version:**
0.93

**OS/device including version:**
Win10

**Issue description:**
Make zooming to the center of node tree window. I am not sure, where it is zooming now, but it seems very random to me. When using zoom in/out buttons, it is OK, but not with using ctrl+scrollwheel.

**Comment by Takanu** [comment]
This, it seems to zoom in from the center of the canvas which is useless, the origin point should be the center of the node viewport.

- Hotkeys would also be nice, a simple Ctrl-+ / - would make dialing in more specific zoom increments better.
- Having a keybind that uses the Middle Mouse Button would also be useful, particularly for drawing tablets where using a scroll wheel means you have to move the cursor.

**Comment by Tar0x** [comment]
This was fixed with the last update. So I am closing this
