### ISSUE TITLE
some brick node outputs (UV, random color) don't tile well

### ISSUE THREAD

**Issue by novemberist** [RodZill4/material-maker#237]
**Material Maker version:**
happens on both latest version cloned from github and official release

**OS/device including version:**
Linux
AMD RX580 with Mesa 20.2.3

**Issue description:**
As already described in this [post on reddit](https://www.reddit.com/r/MaterialMaker/comments/jpn8bm/help_needed_tileable_brick_material/) I'm having issues with the UV and random color output of the brick node. Especially when using the default offset value of 0.5 or somewhere close, the offset half-bricks on every other row (those that actually have to tile) from the left and right edges don't fit together, since they don't "wrap around" with the same color and UV. This unfortunately produces very bad results at the seams, where the material tiles. 

Since other users have reported, that they don't have this issue, I'm assuming this is some driver/GPU-specific bug. Thus I'm opening this issue here.

**Steps to reproduce:**

see above link to reddit, where the issue was described in detail

**Comment by fccDunce** [comment]
I can confirm this issue. 
(Windows 10, Nvidia GTX 760)

**Comment by novemberist** [comment]
I don't think this issue should be closed yet, since #293 only resolves the tiling of the random brick colors. The more severe issue with the tiling of the brick UV still persists, as you can see in the following screenshot

![Bildschirmfoto vom 2021-03-07 06-02-20](https://user-images.githubusercontent.com/7927471/110229743-e9465300-7f0b-11eb-9946-d3b55e1d1f1a.png)

**Comment by novemberist** [comment]
Sorry. I'm not sure if this was accidentally or deliberately fixed in the meantime, but with the latest version from master, I can no longer reproduce this issue.
