### ISSUE TITLE
Gaussian Blur is not resolution independent

### ISSUE THREAD

**Issue by Arnklit** [RodZill4/material-maker#243]
**Material Maker version:**
v0.94a1

**OS/device including version:**
NA

**Issue description:**
Gaussian Blur is not resolution independent. The node does not take the resolution into account to adjust the blur, meaning that setting different resolutions will change the look of the effect rather than just the resolution. By comparison, dilate seems to correctly take the resolution into account.
![image](https://user-images.githubusercontent.com/4955051/101238533-cf149300-36d8-11eb-89df-a11893acddb9.png)

**Steps to reproduce:**
Apply the same amount of blur to a node but with different resolutions to see the issue.

**Comment by RodZill4** [comment]
This node has this behavior since the beginning, modifying it would break compatibility. Blur amount depends on resolution because speed depends on kernel size (blurring a lot at high resolutions would take too much time).

It's probably possible to workaround this problem using mipmaps, but I dod not investigate this yet...

**Comment by Arnklit** [comment]
I see your point with breaking compatibility, but I guess it's better to do it early on rather than later. Or maybe you'll have some release later that will break compatibility, like when you go over to Godot 4.0 and do this as well at that point. 

It does come off as a bug and the user having to guess at the internal logic of the node if they need to change the resolution to double, does that mean they have to exactly double the sigma as well? Probably, but you would have to fiddle about to figure it out.

I feel if you could find a work around for the blur being slow on higher resolution it would be very nice to have it consistent.

**Comment by RodZill4** [comment]
Actually, it's not necessary to break compatibility. We can just create a new Blur node, and obsolete the old one (while keeping it in the lib).

Anyway, this won't be fixed for next release, I still have lots of things to do/fix/document.

**Comment by Arnklit** [comment]
Closing as we now have Fast Blur which is resolution independent.
