### ISSUE TITLE
Source code of the sharing website

### ISSUE THREAD

**Issue by Calinou** [RodZill4/material-maker#245]
**Feature/enhancement description:**

I can't find the source code of https://material-maker.glitch.me/ anywhere. Is it published somewhere?

It would be nice to have the source code somewhere so the community can send code contributions :slightly_smiling_face:

**Comment by RodZill4** [comment]
No the code is not shared yet.

The source code is mainly node.js stuff, and I already received contributions as HTML+CSS+client-side JS (and this helped a lot). I guess that way is easier for most contributors.
