### ISSUE TITLE
Library Filter seach field should have an X / clear button to clear the search

### ISSUE THREAD

**Issue by Arnklit** [RodZill4/material-maker#246]
**Feature/enhancement description:**
Library Filter seach field should have an X / clear button to clear the search.
![image](https://user-images.githubusercontent.com/4955051/101280521-8553a780-37c1-11eb-98ce-dd63e2e10b68.png)

Like Godot does:
![image](https://user-images.githubusercontent.com/4955051/101280541-a1574900-37c1-11eb-8d90-a7a5db270f46.png)

It's cumbersome to have to select the text and clear it to go back to the full library view.

**Comment by Calinou** [comment]
> It's cumbersome to have to select the text and clear it to go back to the full library view.

I never use the "clear" button personally. Instead, I press <kbd>Ctrl + A</kbd> to select the whole line then enter the new desired text. (You don't even need to press <kbd>Delete</kbd> or <kbd>Backspace</kbd>).
