### ISSUE TITLE
Add a FPS limit setting to improve battery use on laptops

### ISSUE THREAD

**Issue by Calinou** [RodZill4/material-maker#249]
**Feature/enhancement description:**

Right now, Material Maker runs as fast as it can when something is animated (e.g. the 3D preview is rotating). It would be useful to be able to specify an FPS limit (e.g. between 30 and 200) to improve battery use and reduce noise/heat emissions on laptops. This can be done by setting `Engine.target_fps` at run-time.

Of course, when using a low FPS limit, the editor won't feel as responsive. This is a compromise you need to make to improve battery life when you need it.

**Comment by Tar0x** [comment]
@RodZill4 This has been implemented, so it should be closed.
