### ISSUE TITLE
Submit new samples?

### ISSUE THREAD

**Issue by MrDiamondGold** [RodZill4/material-maker#25]
Is there a way or place that I or anyone could submit samples to be used in future versions?

**Comment by RodZill4** [comment]
You can either submit pull requests for them or just post the .ptex files here so I can add them to the examples directory. Please don't forget to add a comment node in the graph mentionning your name.

**Comment by MrDiamondGold** [comment]
[improved_brick.zip](https://github.com/RodZill4/godot-procedural-textures/files/3748289/improved_brick.zip)

I ended up spending a large amount of time on this material after thinking it was done so that's why this took two days. It still isn't finished completely and is a mess, but it is in a usable state so I decided I should upload it before I end up spending even more time on it. I'm working on other materials so there should me more to come.

**Comment by RodZill4** [comment]
Damn, it looks great.

Since it seems you spent quite a bit of time using Material Maker, please don't hesitate to send feedback about how to improve the tool. Thanks. :)

**Comment by MrDiamondGold** [comment]
Just wanted to update you on why nothing else has been posted. I have been waiting for newer versions to be released. At the moment I am now working on more materials but it might take a while but there should be quite a few more materials.

**Comment by RodZill4** [comment]
Great ! Please don't hesitate to ask if you need new nodes. I can create them for you (and the current release) and integrate them later.

**Comment by RodZill4** [comment]
New samples should now be submitted on [the subreddit](https://www.reddit.com/r/MaterialMaker/)
