### ISSUE TITLE
Add an AO and Thickness map

### ISSUE THREAD

**Issue by SIsilicon** [RodZill4/material-maker#254]
**Feature/enhancement description:**

For those who don't know, AO stands for ambient occlusion, so an AO map is a mesh texture that stores how occluded each part of said mesh is occluded by other geometry.
A thickness map is like an AO map, but with the normals inverted. It stores information of approximately how thick each part of a mesh is; useful for when you want to fake subsurface scattering.

While these could both be created in an external program, having a button for it along with the other baked mesh textures would improve efficiency, especially when you have a low-endish PC and want to run as little programs as possible.

I can have them implemented, and have already thought of how.
1. A BVH (Bounding Volume Hierarchy) of the mesh's triangles is created. We're gonna be ray-tracing this thing!
2. Then this BVH is transfered to a floating-point texture. We're gonna be ray-tracing on the GPU!
3. Doing it in tiles, progressively or both; we ray-trace the BVH in a shader with the inverse-UV and object normal maps too. Since recursive functions are non existent in shaders, a stack must be implemented manually.
4. We denoise the result with smart bilateral blur passes.
5. Profit!!!

**Comment by SIsilicon** [comment]
Sweet, sweet progress!
I got the BVH construction working and also got BVH _traversal_ working on both CPU and GPU.
The mesh you see in the screenshot below is fully raytraced. Can you believe that? :D
![image](https://user-images.githubusercontent.com/34734122/103793238-f8934800-5011-11eb-9c16-b631a342ffb1.png)
It runs surprisingly well on my Intel GPU, even when I bump up the subdivision level a little. The next step would be to put this ray-tracer to good use, and make an AO map with it. That and optimize the BVH builder, 'cause even though building it doesn't take too long, transferring the data to an array to be transferred to an image texture does _not_ seem to scale well right now.

**Comment by Tar0x** [comment]
Wow, really cool! :) It would be cool to be able to bake from highpoly model to lowpoly model. Usually you don't want to waste time unwraping highpoly model and transfer UVs from lowpoly one. I am not sure, how hard it would be to implement something like that (speaking from an artist perspecive) :) Keep it up :)

**Comment by SIsilicon** [comment]
BVH :- __optimized.__
Map generation :- __underway.__
![image](https://user-images.githubusercontent.com/34734122/103828429-a02b6d00-5048-11eb-9498-044651e119a9.png)

**Comment by SIsilicon** [comment]
@Tar0x What you have proposed sounds like it would come in pretty handy. :)
However, that is beyond the scope of this enhancement, so it'd be better if you open a separate issue on that.

**Comment by SIsilicon** [comment]
Here it is folks! The AO and Thickness maps are now generatable in the UI. There are still some things that need to be done, such as making the ray distances and iterations configurable, but other than that, it's usable now! I'll make a pull request later in the day.
![image](https://user-images.githubusercontent.com/34734122/104049165-7c843600-51b2-11eb-9c74-6b5d3669326c.png)
![image](https://user-images.githubusercontent.com/34734122/104049172-8148ea00-51b2-11eb-911a-34903f303dbb.png)

**Comment by SIsilicon** [comment]
Hey @RodZill4 . Is there a place where the ray tracing settings can be exposed, or do you need to set one up?

**Comment by RodZill4** [comment]
@SIsilicon There's the Preferences dialog, but this would deserve a new tab.

**Comment by SIsilicon** [comment]
@RodZill4 Alright, I'll just have the variables lying around in `map_renderer.gd`. You could figure out where to put them.
