### ISSUE TITLE
Add default extension to Right click export from Preview2D window, I beg thee.

### ISSUE THREAD

**Issue by some9000** [RodZill4/material-maker#259]
First of all - absolutely amazing app. Ease of use and possibilities in a perfect mix. I tried many and this one easily smashed the competition.

**Now onto the wish:**
Please add an option to have an extension by default when Right click exporting from the Preview2D window.

My use case scenario is a bit different from the target audience. I only export  grayscale 2D textures for use as transparency maps in a vector editing application. Having to add ".png" every single time is getting really annoying over time.

Thanks in advance!

**Comment by Tar0x** [comment]
Why do you export by right clicking Preview2D instead of using export node? :)

**Comment by some9000** [comment]
> Why do you export by right clicking Preview2D instead of using export node? :)

Feels like it's easier to just quickly export at a resolution I'd like to use with a single drag and click... :) Once again, a 2D usage thing.

**Comment by some9000** [comment]
This has been beautifully improved with ability to automatically save multiple images if their name ends with a number. Awesome!
