### ISSUE TITLE
Splatter does not always produce the correct amount of shapes.

### ISSUE THREAD

**Issue by some9000** [RodZill4/material-maker#260]
Splatter does not always produce the correct amount of shapes (either that, or some of them have the exact same position).

I am doing some testing, the amount of shapes generated is seemingly random number - like one time it does not show anything more over 80. Another it is 156. Another it is 307. Would be nice to have some more reliable way to generate a given number of shapes.

Not that the amount of shapes is important, but rather how much those shapes fill the available space. Sure, one can blend several of these, but would be nice to have a single element that can generate A LOT of elements.

Also, I just noticed that having several of these blending just made the PC heat up like a toaster. Not sure if it is the blending or just generating a bunch of splatter nodes.

**Comment by RodZill4** [comment]
Yes, shape locations are random, and it's likely some will overlap. The main goal of this node is not to have shapes evenly placed on the texture.
You may want to try the Tiler node, that places shapes on a grid, but let you introduce enough randomness. Plus it's a lot cheaper in terms of GPU compute power.

**Comment by some9000** [comment]
I see, thanks for the quick reply. Would it make sense then to hard limit the amount of shapes to 100 (so it's impossible to scroll outside of that limit) to avoid unnecessary resource usage? Or is that just how the interface works, as it seems you can out-value almost everything?

**Comment by RodZill4** [comment]
That's how Material Maker is. as a user, you're free to mess with parameters, at your own risk. ;)

**Comment by some9000** [comment]
Got it. Well, then, it's not a bug, but a feature and thus this "issue" can be closed :)

Have to use the occasion of you being here to say that this is one amazing application. Powerful, easy to use, good looking. Massive potential to create nearly anything if one has the motivation. Thanks for making it and, hopefully, you can keep on improving it for a looooong time. 👍

**Comment by RodZill4** [comment]
@some9000 please don't hesitate to join our subreddit and our Discord if you haven't already. ;)
