### ISSUE TITLE
Proper Tab functionality in entry fields, Right Click default value setting and some other interface wishes.

### ISSUE THREAD

**Issue by some9000** [RodZill4/material-maker#261]
Hello again. Get ready for a bunch of wishes/suggestions from a 2D centric user:

- Currently when pressing Tab in an entry field of, for example, Color Value Noise node, focus does not jump to the next entry field, but rather to the grid step entry field, then the background 2D preview, then 3D preview, then the hierarchy up button, etc. I (and surely others as well) would greatly appreciate having expected tab behavior of jumping to the next entry field in the current element.
- Also, right click on entry fields does nothing, so, perhaps, it could reset the value to default (or 0)? Would be great.
- Would be fantastic to see the position value of the gradient element somewhere. Even if it only shows up on the extended double-click view.
- Would it be tough to have a round cap (circular end) option for the Curve node?
- As already mentioned an option to not show Material would be nice.
- In the Tones node it would be nice to have the same larger handles as the gradient node (actually the gradient there could be as big as the gradient is, or at least half that height).
- For example, for a Voronoi pattern it randomly changing when moving the node around is neat. But you cannot see the later nodes when that is happening. Would there be a way to drag on their forms and change the random seed without selecting them?

That's it for now.

**Comment by Calinou** [comment]
Could you open individual issues for each proposed feature? This makes things easier to track.

**Comment by some9000** [comment]
Well, I did go through all the open issues to have a look at all the things people have talked about and seemingly didn't see any of this mentioned.
Didn't have a look in closed ones, though.
In general it felt like most of these were generic UI ideas, which might unify them somewhat. But I will do the extra look in closed issues and repost these as suggested then.

**Comment by Calinou** [comment]
> Also opening a whole new suggestion topic for each felt a little pushy. So this approach seemed better.

It's not pushy, it's *atomic* :slightly_smiling_face:
