### ISSUE TITLE
Visible numerical element position for Gradient, Colorize and anything else that uses gradients.

### ISSUE THREAD

**Issue by some9000** [RodZill4/material-maker#264]
Would be fantastic to see the position value of the gradient elements somewhere. Even if it only shows up on the extended double-click view. So you can have that perfect center or perfectly sized lines , for example.

**Comment by Tar0x** [comment]
Yes, I hope this will be implemented. Also tonality node, colorize node and other similar nodes should have this improvement :)

**Comment by some9000** [comment]
Time to celebrate, it has been implemented. Could be improved, but still very helpful.
