### ISSUE TITLE
Random length and width for Scratches?

### ISSUE THREAD

**Issue by some9000** [RodZill4/material-maker#268]
It's been a century since I ever tried to make any shaders, but since the amount of Scratches can be changed I assume they are generated in some sort of a loop so changing size of each should be possible...? Would be a little easier to make more realistic scratching than blending a bunch of them.

**Comment by Tar0x** [comment]
To be honest I like he simplicity of actial scratches node, it's so versatile. I think more realistic scratches node (for grunge maps) should be made out of scratch (pun not intended) with some noise overlay and distortion :)

**Comment by some9000** [comment]
I don't know - seems like if it's under Patterns it can be relatively complex as well. For example, Brick patterns have many options. This just feels like something that would fit in.

Then you could add some opacity or distortion maps and have more options.

**Comment by some9000** [comment]
Well, I know how to edit shaders (badly) now so can improve this on my own. Thus closing.
