### ISSUE TITLE
Color picker has no background when changing comment color

### ISSUE THREAD

**Issue by Arnklit** [RodZill4/material-maker#271]
**Material Maker version:**
0.94a4, latest alpha two days ago.

**OS/device including version:**
Windows 10 64 Bit

**Issue description:**

Color picker has no background when changing comment color. The color picker is also smaller than other color pickers. I tried disabling DPI scaling, thinking that was effecting it, but that made no difference.
![image](https://user-images.githubusercontent.com/4955051/106387169-655eef80-63d0-11eb-9e14-dec30008a705.png)

**Steps to reproduce:**
Add a comment node and select it's color field.

**Comment by some9000** [comment]
Can confirm. Must be a bug.
