### ISSUE TITLE
Resizing comments does not adhere to snapping

### ISSUE THREAD

**Issue by Arnklit** [RodZill4/material-maker#274]
**Material Maker version:**
0.94.stable

**OS/device including version:**
NA

**Issue description:**
Resizing comments does not adhere to snapping. When snapping is enabled I would expect comment box scaling to also snap to the grid so I can have everything adhere to the grid.

**Steps to reproduce:**
Enable snapping. Create a comment and drag at it's corner.

**Comment by RodZill4** [comment]
It's likely this is a Godot behavior and we don't have any control over it.

**Comment by Arnklit** [comment]
Aren't comments specific to MM? I don't see them available in normal Godot graphs.

**Comment by RodZill4** [comment]
> Aren't comments specific to MM? I don't see them available in normal Godot graphs.

Comment is a flag in nodes.

**Comment by Calinou** [comment]
This should be fixed in Godot itself, no?

**Comment by Arnklit** [comment]
Closing and opening in Godot instead.

**Comment by Calinou** [comment]
For the record, this was fixed by https://github.com/godotengine/godot/pull/45776 in 3.2.4.
