### ISSUE TITLE
Issues found on read through of documentation

### ISSUE THREAD

**Issue by Arnklit** [RodZill4/material-maker#277]
**Material Maker version:**
0.94.Stable

**OS/device including version:**
NA

**Issue description:**

https://rodzill4.github.io/material-maker/doc/user_interface_overview.html#overview

"Additional panels can be shown on **ooth** sides of the Project panel." - Typo

"The following panels will be shown only **in when** editing a material project:" - "in" should be removed

*Are the below default locations of panels correct any more? I'm pretty sure I have the default layout and the panels are not set up like this:*

"
The Hierarchy panel (by default in the bottom left corner) shows the hierarchy of node groups of the current material graph.

The 2D preview panel (by default in the top right corner) shows the first texture generated by the currently selected node

The 3D preview panel (by default in the bottom right corner) shows the current material applied to a sample mesh in a sample environment
"

https://rodzill4.github.io/material-maker/doc/user_interface_2d_preview_panel.html

"The animated dashed lines show the bounds of the texture" - I think the 2d preview has changed and no longer uses animated dashed lines.

https://rodzill4.github.io/material-maker/doc/user_interface_performance.html

"Material Maker relies on shader generation and rendering to generate **texture**. It sometimes creates very complex **shader** that can impact performance, while trying to provide smooth user experience." - I think "texture" and "shader" needs to be plural here.

https://rodzill4.github.io/material-maker/doc/nodes_common.html#inputs

"Inputs are images the node will transform (if any). An input is always connected to at most **an** output." - "an" should be "one" here I think.

https://rodzill4.github.io/material-maker/doc/nodes_common.html#parameters

"When the lower or upper bound is **reach**, the value will stick to it ... " - "reach" should be "reached"

"It is possible to freeze the seed value using the small **dice** button in the node’s title bar in the graph." - There is only one die on the button, shouldn't it be "die" rather than "dice" ?

https://rodzill4.github.io/material-maker/doc/shader_nodes.html#parameters

"... There are a few tricks with this label that can help tweaking the UI." - As far as I can tell the "tricks" are never elaborated on?!?

https://rodzill4.github.io/material-maker/doc/shader_nodes.html#outputs

"The yellow document button can be used to define a name and add a tooltip to the input." - "input" should be "output" here.

https://rodzill4.github.io/material-maker/doc/base_library.html#nodes-library

"This section describes all nodes that **can** are provided in the base library to describe procedural materials." - Typo, "can" should be removed.

https://rodzill4.github.io/material-maker/doc/node_filter_adjust_hsv.html#parameters

"Value **defunes** how the lightness is affected." 

https://rodzill4.github.io/material-maker/doc/node_filter_tones.html#tones-node

"The nodes shows **an** histogram of all channels of its input ..." - "an" should be "a"

https://rodzill4.github.io/material-maker/doc/node_filter_combine.html#inputs

"The Combine node has 3 inputs, one for each (red, green and blue) channel." - should be 4, it also has alpha.

https://rodzill4.github.io/material-maker/doc/node_transform_warpdilation.html#warp-dilation-node

"The Warp Dilation node **dilated** its input image along the slope or contours of a heightmap." - "dilated" should be "dilates"

https://rodzill4.github.io/material-maker/doc/node_miscellaneous_switch.html#switch-node

"The Switch node can be used to select sources for **2 to 5** output textures from a choice of **2 to five** inputs sets. It is useful to create variations of a material and easily switch between them." - Inconsistent usage of numbers. Also as far as I can tell it's 2 to 10 input sets?

"The Switch node has from 2 to 25 color inputs A1, B1, .. D5, E5." - I think it goes up to 50 imputs instead?

https://rodzill4.github.io/material-maker/doc/node_miscellaneous_export.html#export-node

"The Export node defines **a a** texture that will be saved together with the material textures when exporting the project." - "a" repeats

https://rodzill4.github.io/material-maker/doc/node_miscellaneous_export.html#parameters

"The Export node has a single parameter that defines the suffix of the PNG file that will be created." - the export node also has a size parameter.

https://rodzill4.github.io/material-maker/doc/export.html#exporting-materials

"In all cases, the generated PNG files (and especially the normal map) **is** generated in the correct format." - "is" should be "are" as it refers to "files"

**Steps to reproduce:**
NA

**Comment by Arnklit** [comment]
Just saw now that the "Occlusion" node calls itself the "Normal Map" node twice in it's page. https://rodzill4.github.io/material-maker/doc/node_filter_occlusion.html

Now that I've gotten setup for handling the documentation I can go through and fix all of these myself if you want @RodZill4?

But maybe you can just let me know if you'd like me to and if it can all be done with a single pull request of it should be done with multiple?

**Comment by RodZill4** [comment]
Yeah please dont hesitate to fix mistakes, and no need to open many PRs for that.
