### ISSUE TITLE
App randomly crashes when making Group Parameter or Remote connections

### ISSUE THREAD

**Issue by Takanu** [RodZill4/material-maker#283]
## Material Maker version
0.94, 0.95

## OS/device including version
Windows 10 20H2 19042.804
AMD Ryzen 5 3600
NVIDIA GeForce 1060 3GB

## Issue description
Whenever new property connection are made or an additional connection is made on an existing property, there is a chance the app will crash.

- Happens in groups with the Properties panel.
- Happens outside of groups using the Remote node.
- There is no distinct pattern, the same file can be loaded a dozen times and there's no pattern as to when the app will crash, only that it's frequent enough to where using Parameters has become near-impossible for me (usually crashes in 1-3 connections).
- There was one time during a 0.94 beta where a memory allocation error appeared during this kind of crash, but I don't know what it was specifically.

## Steps to reproduce

https://user-images.githubusercontent.com/9108903/107823111-1e311100-6d77-11eb-9aa6-e8a1c4a918fc.mp4

**Comment by Takanu** [comment]
Still happens with 0.95 Q _ Q

**Comment by RodZill4** [comment]
Many problems have been fixed in Remote node. I close this, we'll reopen one if problems show again.
