### ISSUE TITLE
Improve environment lighting

### ISSUE THREAD

**Issue by tinmanjuggernaut** [RodZill4/material-maker#29]
The current environments are inadequate for accurately depicting materials.

* In Schelde, a pure white cube displays as medium blue-grey, even though the sun is shining directly on it.
* In Park, with a bright blue sky, it's dark green-brown.
* In Night, it's dark grey-brown; the white cube is darker than the black asphalt ground!
* In Lobby, it's medium brown with 50 lights overhead.
* In Experiment, it's multicolored medium grey.

One cannot accurately determine colors or texture depth in this situation. This is mostly due to Godot's current poor implementation of environment lighting but there are many things you can do to improve it.

* In Godot's environment settings/tonemap, you should set it to Filmic, and set White to 16. Set the background to Schelde and observe what happens to the sun as you do this.

* Most of the HDRIs provided by Godot are under exposed (or at least rendered under exposed). For Schelde you should set Exposure (in the same panel) to at least 2, up to 4. All the other HDRIs need a boost as well.

* You also need a directional light (energy 0.5-1) that lines up with the environment lighting. Environment lighting in Godot is severely inadequate. The environment doesn't provide shadows, and even increasing the exposure as above really only gets the background accurate. It doesn't adequately light objects to accurately show material attributes like color, normal maps, etc. To get your lighting and shadows accurate, the light needs to come from the exact same angle as the sun in the background. There's a trick to make it easy if you need it.

* In addition to these environment maps,  you should provide a pure white studio lighting setup. Maybe 2: One with a 3-point light set. And another using flood lights or an emissive plane, though this might have to wait until you can use a realtime GI probe in Godot 4.

* The background should rotate. I'd have one button to rotate the object, and another to rotate the background  (or the camera and all objects except lights). That way I can control the object position and light position independently.

Here is a sample file for schelde. Drop `shcelde.hdr` in the project folder. Though the cube still appears blue here, it's a proper blue from the environment rather than a dark blue-grey when the sun is supposed to be shining directly on it.

[Lighting Sample.zip](https://github.com/RodZill4/godot-procedural-textures/files/3746861/Lighting.Sample.zip)

**Comment by Calinou** [comment]
> The background should rotate. I'd have one button to rotate the object, and another to rotate the background (or the camera and all objects except lights). That way I can control the object position and light position independently.

In the `export_plugin` branch (which is where development currently happens), you can hold <kbd>Shift</kbd> while rotating to control whether the background should rotate at the same time as the model.

**Comment by RodZill4** [comment]
@tinmanjuggernaut Thanks for all those details. I must admit environments in 0.6 are just randomly selected HDRIs with default WorldEnvironment and a point light.

In the export_plugin branch environments are now more flexible and easier to modify (in preview_3d.tscn/Environments).

**Comment by tinmanjuggernaut** [comment]
Ok, well feel free to close this if and when you feel the environments are up to par. I was just letting you know of an issue in 0.6 and some ideas on how to fix it, but it appears you were already aware.

**Comment by RodZill4** [comment]
Hmm I knew that part was bad but did not know how to fix it. I still need to figure out a studio setup. Thanks anyway, I learnt a lot about this topic. ;)

**Comment by Calinou** [comment]
I think it makes sense to offer a pure black/gray environment with ambient lighting only, for those who are working on pixel art materials (where you generally don't care about PBR).

**Comment by tinmanjuggernaut** [comment]
Here's a sky based studio-like environment. The problem with lighting in Godot is that normals are informed by lights and skies. Metals are informed by skies and ignore lights. Anisotropy is informed by both. The Godot environment comes with 5 light producers for the sky (ground x2, sky x2, sun) and 2 ambient lights (energy, sky contribution). In the default environment, most of these are colored. And as noted before HDRi lighting is inadequate. It's kind of a mess. 

Here's an environment that has all light sources set to pure white. It has a directional light coming from the same direction as the sky sun. And the values are all balanced by eye so that metallic and non-metallic surfaces, anisotropy, and shadows look reasonably realistic.

As for a 3 point lighting setup that I recommended having, I'm not sure it's worth doing now as metal is informed by the background color, regardless of if its a sky or not. I would switch the environment to GI aiming for true physically correctness. But that might have to wait until Godot 4 for realtime GI.

[Studio Sky.zip](https://github.com/RodZill4/godot-procedural-textures/files/3794091/Studio.Sky.zip)

**Comment by RodZill4** [comment]
Great. It shoud be easy to integrate as a preview option. Thanks !
