### ISSUE TITLE
Godot plugin unable to load, code error

### ISSUE THREAD

**Issue by Valinakova** [RodZill4/material-maker#315]
When I tried to enable the addon, I get the following error message: Unable to load addon script from path: 'res://addons/material_maker plugin/plugin.gd' There seems to be an error in the code, please check the syntax.

I recently just downloaded all the files of Github. I tried enabling it but it gave me a syntax error.

I also tried downloading the plugin off the asset library but it did not resolve the issue.
 https://godotengine.org/asset-library/asset/267 and downloaded 0.94. 

Folder set up:
![image](https://user-images.githubusercontent.com/81381626/112525359-0da08d00-8d5e-11eb-83b9-1d23217d017c.png)

I'm unable to run the addon, due to code error.
![image](https://user-images.githubusercontent.com/81381626/112525480-29a42e80-8d5e-11eb-8227-3d1cf300b8c8.png)

**Steps to reproduce:**
Use Godot 3.2.3
Download material-maker and install it in the game you intend to use it in.
Attempt to enable.

the game can be downloaded here which has the addon I'm attempting to enabled installed. https://drive.google.com/drive/folders/1eX1_K3ydwZ6kTlb6D1998e1aKOCrrd-K?usp=sharing

**Comment by Valinakova** [comment]
I looked at the plugins file. There appears to be some issues im not sure how to fix. 
![image](https://user-images.githubusercontent.com/81381626/112533688-73dddd80-8d67-11eb-8b8c-7df8292c24f5.png)
![image](https://user-images.githubusercontent.com/81381626/112533751-81936300-8d67-11eb-8550-6f1fe40868d7.png)

**Comment by Calinou** [comment]
See also https://github.com/RodZill4/material-maker/issues/184 and https://github.com/RodZill4/material-maker/issues/139.

**Comment by Valinakova** [comment]
Ok, the maker mentioned 
mm_io_types="*res://addons/material_maker/engine/io_types.gd"
mm_loader="*res://addons/material_maker/engine/loader.gd"
mm_renderer="*res://addons/material_maker/engine/renderer.tscn"

I'm not sure where to put these. I'm very new to coding, I understand some of the basics but do not know where to put these items. I want to get the addon to work so I can run procedural textures without baking anything.

**Comment by RodZill4** [comment]
Could you tell me why you want Material Maker as a Godot addon?
This is not maintained anymore, and I see very little use for that now.

**Comment by Valinakova** [comment]
Thanks for replying, what I'm hoping to do is allow for the textures to be manipulated dynamically in game for a procedural game. I like the idea of combining procedural objects with dynamic procedural textures, since there would be a way to create a set up in which every object, planet, etc has at least slightly different texture.

**Comment by RodZill4** [comment]
Hmm I think that approach would be overkill (Material Maker generates shaders, you probably don't want your game to generate shaders for every object).
Another solution would be to create shaders with enough parameters to bring the variety you want in your game. And this can be done with Material Maker (using the Debug node to get the shader code, and then integrating it into your materials).
Please don't hesitate to join us on Discord if you need help.

**Comment by Valinakova** [comment]
Sure, I could drop by discord when I need some advice! And thanks for letting me know what's going on with the addon.
