### ISSUE TITLE
Material Maker crashes before fully launching when the "material_maker" folder is missing in AppData/Roaming

### ISSUE THREAD

**Issue by Arnklit** [RodZill4/material-maker#317]
**Material Maker version:**

aab52fa2a484b6c3cd9115e3e6ab1a22e6e5d75e

**OS/device including version:**

Windows 10

**Issue description:**

Latest build of Material Maker crashes if I delete the "material_maker" folder in AppData/Roaming. It does not correctly create a new folder, just an empty one and cannot be launched afterwards either.
Launching .94 stable instead will correctly create the folder and then latest nightly can run.

**Steps to reproduce:**
1. Delete or rename AppData/Roaming/material_maker folder and launch Material Maker.

**Comment by RodZill4** [comment]
Should be fixed. Does it still happen for you?

**Comment by Arnklit** [comment]
Yeah perfect. Works exactly as expected now. Closing.
