### ISSUE TITLE
Save User Interface layout & other preferences

### ISSUE THREAD

**Issue by JustSaiyan01** [RodZill4/material-maker#328]
**Feature/enhancement description:**

**1).** Would be great to have more UI preferences to be saved on exit or provide the options in the preference menu.

For example, here is a screenshot of the progam on start up:
![startup](https://user-images.githubusercontent.com/55152007/115894075-c850a780-a450-11eb-9db8-2a0f33737c7e.jpg)

Here is how I would like it on start up though:
![edited start up](https://user-images.githubusercontent.com/55152007/115894275-fb933680-a450-11eb-9c86-d964ffc542b4.jpg)

As you can see, there are a few small things that have been changed; list below.
- Grid snap & view turned on by default
- Grid snapping value changed from 20 > 30
- 3D preview HDRI Environment changed from Epping Forest > Studio
- Model Rotation off by default
- Graph center view (it's offseted on start up)

**2).** Would be great to have User Interface themes colours be customiseable. 
Not a fan of the default theme, so I use the dark theme as you can tell. Though the dark theme feels a bit too black for my liking, noticebale around the top of the program. Doesn't feel like there is any nice colour speration between the panels and graph.

**Comment by melvixiodf** [comment]
Just seeing this after making a feature request for preview 2d and 3d configuration to be saved. I think this is important as well for other windows too.

**Comment by RodZill4** [comment]
This is done except for 3D preview. I keep #339 for this.
