### ISSUE TITLE
Directional/ Vector Offset Warp?

### ISSUE THREAD

**Issue by melvixiodf** [RodZill4/material-maker#341]
Are these planned for Material Maker in the next release or they already exist?

There are two warp nodes, Warp and Warp Dilation but they can't offset an input image based on a say a brick height map with a random grey or color from a fill node.

**Comment by melvixiodf** [comment]
Something like this:
https://www.youtube.com/watch?v=Y_s0Yr_OFCQ

Directional Warp:
https://youtu.be/we4lMxU94CA?list=PLB0wXHrWAmCzTXeyYT5Vy3ds711ZRHRYh&t=1159

**Comment by RodZill4** [comment]
Yes. I just gave you the answer. Use the second output of Bricks plugged into translate inputs of a Transform.

**Comment by melvixiodf** [comment]
Wow. It works. Thanks a ton.

Sorry, should have tried it out before posting the videos.
