### ISSUE TITLE
Crashes while editing node groups

### ISSUE THREAD

**Issue by orestiskon** [RodZill4/material-maker#342]
**Material Maker version:**  0.95

**OS/device including version:** Windows 10 / GeForce 1080Ti/ Ryzen 7 1700x

**Issue description:** Crash

**Steps to reproduce:**
I had a couple of crashes after creating the two node groups, and trying to go in and out to edit them. It crashed while editing values or while jumping through the hierarchy levels.
File:
[screw4.zip](https://github.com/RodZill4/material-maker/files/6851229/screw4.zip)

**Comment by RodZill4** [comment]
Many bug were fixed in groups/remotes. Closing this, we'll open a new one when new bugs are discovered.
