### ISSUE TITLE
Text node doesn't respect the center setting after loading a material

### ISSUE THREAD

**Issue by opl-** [RodZill4/material-maker#362]
**Material Maker version:** v0.96

**OS/device including version:** Linux/Debian

**Issue description:**

Saving a material containing a text node with the center option enabled and loading it after a restart results in the text rendered by the node to render as if the center option wasn't enabled.

**Steps to reproduce:**

1. Create a new material with a Text node. Set `font_size` to `512`, `center` to `true`, `x` and `y` to `0`.
2. Save the material.
3. Restart Material Maker.
4. Load the material.
5. Select the Text node.
6. The text rendered by the node will not be aligned correctly.

**Comment by RodZill4** [comment]
This is fixed for 0.97
