### ISSUE TITLE
[Proposal] When Comment block is dragged, also move all nodes within it.

### ISSUE THREAD

**Issue by varkatope** [RodZill4/material-maker#370]
**Feature/enhancement description:**

When using a Comment block to organize graphs, which I often do, it would be helpful if when the comment block is moved, for all other nodes within its boundaries to move with it. In the example image below, imagine that moving the Normal comment box also moves the nodes with it, regardless of whether you've individually selected them or not. There could perhaps be a lock icon in the top-right of the comment box that turns this behavior on and off: locked, move nodes with the comment box; unlocked, behavior as it is now.

![comment_org_example](https://user-images.githubusercontent.com/10719843/139794023-d681960b-d36e-45e9-935b-c2ac7caa7f72.png)

Right now you basically have to box-select all the nodes and the comment to move them around, which can be tedious currently because selection is kind of broken at anything but 1:1 zoom level. It can be argued that groups should be used to organize instead, but for graphs that are medium-complex, it makes sense to have everything on the main screen but while still wanting to organize it a bit, and the comment colors make using the mini-map much more useful.

By the way, the graph pictured above isn't really an actual material, I just got carried away with my example. Imagine it's 2-3 times that size.

**Comment by RodZill4** [comment]
Added for 0.98 (selecting a comment will select all nodes inside it)
