### ISSUE TITLE
OpenEXR export … color channels shifted in generated EXR file

### ISSUE THREAD

**Issue by leonard7e** [RodZill4/material-maker#372]
**Material Maker version:**
Version 0.97, this build:
https://github.com/RodZill4/material-maker/actions/runs/1431815396

**OS/device including version:**
Ubuntu Linux 20.04
GPU: RTX 2060s 

**Issue description:**
OpenEXR generated from MaterialMaker has mismatching colors. 

Testing colors, it seems that color channels got shifted like that

```
Alpha → Red
Red → Green
Green → Blue
Blue → Alpha

```

**Steps to reproduce:**
Just export OpenEXR from Viewport2D and check the result.

I prepared something which might be useful. Load test_colors.ptex file from there …
https://drive.google.com/file/d/1xlusZCEib_18czDcPqSpfDDlG5re3D-_/view?usp=sharing

There are float nodes for 0.0 and 1.0, which could be connected to a Combine node. Plug floats to different inputs of the combine node, and export an EXR file from the Preview2D of the Combine node.

Use Gimp (or other software which supports OpenEXR) to examine result EXR file.

**Comment by RodZill4** [comment]
Hmm I don't understand this problem. Godot reads the generated files correctly, and Godot's code seems to handle channel order.
No problem with exports? It's exactly the same code...

**Comment by leonard7e** [comment]
Looking at EXR images I generated from MM, the colors were wrong. I needed some time to figure out what is going on.

The MM file I shared helped me to discover that RGBA channels have been shifted in the EXR image.

For some reason the alpha channel seems to get at the wrong side of the RGB data block. 

The problem occurs with export (Blender) too.

**Comment by leonard7e** [comment]
Another test-setup for MM, much cleaner and simpler.

![test_channels](https://user-images.githubusercontent.com/5395270/141516363-5975c41b-5880-4ce2-aeff-9acfa3cb29a4.png)
The MM file … [test_color_channels.ptex](https://drive.google.com/file/d/1oyS4Mu5yAU5syrwvcDjL-nA9y9orZ8eD/view?usp=sharing)

Shifting colors into the opposite direction, I balance out 'alpha channel shift' and do get correct colors.

Original image  …
![channels_original](https://user-images.githubusercontent.com/5395270/141515830-bbf212c7-c9e8-4662-987e-be9951cd64cd.png)

Exporting this image would result in distorted colors in the EXR file.  To balance it out, the channels are shifted with "Swap channels" in opposite direction. 
![channels_shift](https://user-images.githubusercontent.com/5395270/141515921-eb83b6bf-6972-481a-b275-bb63f7e45d27.png)

The EXR output of this image does show the correct colors, the same colors as the original images.

**Comment by RodZill4** [comment]
I want to investigate the issue in Godot (without any MM code). Godot seems to read the exported EXR files just fine.

**Comment by leonard7e** [comment]
I tried in a minimal Godot project. Godot reads MM generated colors fine.

But the same is not true for other software I tested. I tried exrdisplay, Gimp, Blender, Natron2 and DaVinci-Resolve. 

If possible, try exrdisplay. ([exrdisplay is from makers of OpenEXR](https://www.openexr.com/using.html))

**Comment by thenegativehunter2** [comment]
i have the same problem. they aren't actually shifted. they go in reverse.

**Comment by thenegativehunter2** [comment]
same problem here. in the previous version (0.95) blender export wasn't working at all, now it just exports wrong.

**Comment by leonard7e** [comment]
The strange thing about it, this problem won't appear if Godot is used for testing. Godot loads EXR generated from MaterialMaker just fine.
However, EXR files generated by MM aren't working for other apps which support EXR (Blender, Gimp, DV Resolve, etc.).  Technically, they 'load', but the channel's order is changed. Sadly, this is a no-go for an EXR based workflow.

Because of the disfunctional EXR workflow (MM and other apps), one still needs to move to PNG.

**Comment by thenegativehunter2** [comment]
> The strange thing about it, this problem won't appear if Godot is used for testing. Godot loads EXR generated from MaterialMaker just fine. However, EXR files generated by MM aren't working for other apps which support EXR (Blender, Gimp, DV Resolve, etc.). Technically, they 'load', but the channel's order is changed. Sadly, this is a no-go for an EXR based workflow.
> 
> Because of the disfunctional EXR workflow, one still needs to move to PNG.

i'm not sure about that. i think godot itself handles exr wrong. and it's being exported with the help of godot libraries (is it?) then it will be just wrong...
i open the exr images with gimp. decompose their color channels and their wrong.

**Comment by leonard7e** [comment]
I checked EXR generated from Godot. You are right, it's Godot. My little Godot-Project does just load an RGBA png file and export it as EXR (if button pressed). Generated image shows wrong colors (exrdisplay reveals).

MM just uses Godot to generate EXR files.

I created a new issue in Godot's Github project.
https://github.com/godotengine/godot/issues/55472

**Comment by fire** [comment]
Made a pr. https://github.com/godotengine/godot/pull/56715

**Comment by leonard7e** [comment]
Thank you very much for your help.

**Comment by fire** [comment]
Is this confirmed fixed?

**Comment by leonard7e** [comment]
I used the changed godot build inside MaterialMaker. And I  can confirm that the channel order is fixed.
Godot created an indent artifact if I import/export the rgb-flower image from Godot. But I  was not able to recreate the indent artifact with a different image yet.

**Comment by RodZill4** [comment]
This should be fixed with Godot 3.5. MM does not generate color EXR files for Blender anymore, anyway...

**Comment by leonard7e** [comment]
Godot's EXR bug distorted MM's  Blender output for decades. 
I can understand your decision to switch to PNG to get a working solution.
