### ISSUE TITLE
Sampler2D declaration missing in code generated for Custom Shader node

### ISSUE THREAD

**Issue by Mirko-Salm** [RodZill4/material-maker#374]
**Material Maker version:** v0.97

**OS/device including version:** Win10, NVIDIA GeForce RTX 2060, driver version 466.77

**Issue description:** 
The shader code generated for a Custom Shader node is missing a sampler2D declaration and doesn't work as a result of that.

**Steps to reproduce:**
- create a new Custom Shader node
    - add a RGBA input to it called "in"
    - add a RGBA output to it with the value: textureLod($in.texture, $uv, 0.0)
- connect a Buffer node to the input of the Custom Shader node (without doing so even "$in.texture" doesn't get parsed correctly)
- connect a Debug node to the Custom Shader node to inspect the shader code: there is no sampler2D declaration
- change the output value to: textureLod($in.texture, $uv, 0.0) + ($in($uv))*0.0
-> now the necessary sampler2D declaration is added to the code and the node is functional

**Comment by RodZill4** [comment]
Looks like it was fixed for 0.98

**Comment by Qendolin** [comment]
Bug happens again in 1.4 alpha 2.
