### ISSUE TITLE
Node connection lost after editing group node

### ISSUE THREAD

**Issue by Mirko-Salm** [RodZill4/material-maker#375]
**Material Maker version:** v0.97

**OS/device including version:** Win10

**Issue description:** 
Node connection lost after editing group node

**Steps to reproduce:**
- create a Custom Shader node with a greyscale input
- add a Shape node and connect its output to the Custom Shader node
- add a Gaussian Blur node and edit it by pressing the pencil icon
- don't actually alter anything inside the Gaussian Blur node and instead press the 'Back to parent' button
- the connection between the Shape node and the Custom Shader node is now missing

**Comment by RodZill4** [comment]
Does not happen anymore (maybe fixed while rewriting edit code for undo/redo)
