### ISSUE TITLE
[Proposal] Option to paint normals relative to camera.

### ISSUE THREAD

**Issue by jitspoe** [RodZill4/material-maker#379]
**Feature/enhancement description:**
This is something I would really love to have for doing painterly, hand painted normals: being able to paint the normals relative to the camera angle, rather than the texture.

Another great application would be to do things like put bevels on hard edges
![image](https://user-images.githubusercontent.com/7751182/141613034-121d2e35-6b75-4af4-b104-6171e37e9835.png)

I actually attempted to do this, but ran out of time tonight, and figured it'd probably be a lot faster for you to implement, since you know how it all works.  Took a while to figure out how everything was set up.  I was trying to set up something similar to what you had with View2Texture using a shader that set albedo to the normal, then I could do the normal blending calculations remapped to the normals relative to the camera.

![image](https://user-images.githubusercontent.com/7751182/141614297-0a1e1a46-0162-4e03-97ac-8b88d8b8820b.png)
Another nice benefit of being able to paint like this would be to touch up low poly meshes where there are some ugly artifacts causing the poly edges to be really visible, especially if there's some way to blur/smooth.

**Comment by RodZill4** [comment]
Hmm normals are already relative to the camera if the brush is set to stamp or pattern mode (I'm not completely satisfied with the math, that's why the solution I mention below will be added). You can paint the "normal color" you want by just connecting a gradient node to a normal map node and the normal map output to the normal input of the brush.
Instead of the gradient, you can also define a "profile" to be drawn on the normal map:

![image](https://user-images.githubusercontent.com/6957908/141615258-aff0f24e-906b-4ce5-891e-9d8cdc54c568.png)
(visible pixels are due to the very bad UV unwrap of the model).

In next release, it will also be possible to generate the normal map from the depth map, so this should be even easier (you can grab a dev build in the "Actions" section).

**Comment by Calinou** [comment]
> Another great application would be to do things like put bevels on hard edges

Note that this can also be done on the model side by using the Weighted Normal modifier in Blender 2.80 and later, or the **Harden Normal** option in the Bevel modifier.

**Comment by jitspoe** [comment]
I think I explained this poorly.  What currently happens, if I have just a straight "up" normal and paint it, regardless of brush mode, just paints a "flat" normal on the texture (same as if there was no normal map).  What I WANT to happen, is for the normal map to be created such that the end result would be the normal facing toward the camera in the current view.

**Comment by RodZill4** [comment]
> 
> 
> I think I explained this poorly. What currently happens, if I have just a straight "up" normal and paint it, regardless of brush mode, just paints a "flat" normal on the texture (same as if there was no normal map). What I WANT to happen, is for the normal map to be created such that the end result would be the normal facing toward the camera in the current view.

Yep, that's what I mention in my last sentence (was not quite sure about the UI you expected). I think it's possible to have access to world normals, tangents and view vector in brushes and create a brush that calculates the right normal. Will try this later today.

**Comment by RodZill4** [comment]
BTW, any name idea for that brush?

**Comment by RodZill4** [comment]
Looks like I got something working... Should be available in latest dev build. Please tell me if it works for you.

![image](https://user-images.githubusercontent.com/6957908/141679168-67ea4531-325c-4fb5-a575-49c5a2e9729a.png)

There's a catch, though. It's possible to generate normal maps using both depth and normal layers. It's necessary to remove the depth-generated (in Tools->Paint project settings menu) part to get normals right when using this brush (just spent an hour trying to find out why my brush did not work. :( ).
This is a new feature in 0.98 and I'll probably make it a per-layer option, and I'll probably add different normal blend options that workaround this problem.

**Comment by jitspoe** [comment]
This is almost perfect!  If you could find a way to do this relative to the actual lerped vertex normals, though that'd be amazing!  In addition to the hand painted style, I was hoping to hide some of the low-poly normal artifacts like this (painted all flat, but you cans till see them):
![image](https://user-images.githubusercontent.com/7751182/141742323-ee178d61-4a7b-4156-996b-3204263b0bc2.png)

**Comment by RodZill4** [comment]
Did you disable normals from depth as described above? Painting with that brush should completely flatten surfaces.

**Comment by jitspoe** [comment]
Oh, man, you are a legend.  I misunderstood the post.  With depth normal disabled it works just as I wanted it to!

![image](https://user-images.githubusercontent.com/7751182/141772113-4a83a86a-6591-4345-a8c3-8417ecedd446.png)

I assume we can use this flatten node and do other math relative to those normals if we wanted to add additional texture or something?

Thanks for doing this!
