### ISSUE TITLE
Using random seed button in sdRepeat node corrupts output

### ISSUE THREAD

**Issue by belzecue** [RodZill4/material-maker#381]
**Material Maker version:**
v0.97

**OS/device including version:**
Ubuntu 20.04, Intel graphics, NUC7PJYH4

**Issue description:**
Pressing the randomize button on the sdRepeat node, with non-zero random rotation, corrupts the output.

**Steps to reproduce:**
See video.  

https://user-images.githubusercontent.com/1931303/142574492-7a6f9fd9-7c8a-456e-bf0e-acb6670aaa89.mp4

**Comment by RodZill4** [comment]
I cannot repeat this problem. I'm afraid it could be GPU specific.

**Comment by RodZill4** [comment]
Oh, never mind, looks like I fixed this a while ago. But it's still broken in 3D SDF repeat...
