### ISSUE TITLE
Enabling standard visual shader nodes like UV coordinates or scalar/vector3 values

### ISSUE THREAD

**Issue by jcarlosrc** [RodZill4/material-maker#394]
**Feature/enhancement description:**

It seems like common input shader nodes like UV coordinates, float scalar / vector values, camera transform and so on are not included in the set of nodes. I think they are kind of standard nodes in many visual shading tools.

**Comment by RodZill4** [comment]
This is not how nodes work in MM, it's a completely different approach.

Node ports are functions, not values. UV coordinates (and spatial position in 3D SDF and 3D TEX) are implicit parameters of those functions. Values are only used as parameters.
