### ISSUE TITLE
texture lose tilable

### ISSUE THREAD

**Issue by turbodizayn** [RodZill4/material-maker#411]
**Material Maker version:**
96

**OS/device including version:**
 win 10 

**Issue description:**
I have got no tilable texture, if use FILL/FILL TO RANDOME nodes. U can see difference between sorce texture (pict1) and prodused texture used as mask (pict3). Because mask texture has not correct extensions result (pict4) is not tilable(((. Thans U

**Steps to reproduce:**

**Comment by turbodizayn** [comment]
![Capture](https://user-images.githubusercontent.com/97593553/149098394-ad188fc1-196d-4d87-923e-4cb6dd468003.JPG)

**Comment by turbodizayn** [comment]
![Capture](https://user-images.githubusercontent.com/97593553/149098702-b9388341-f370-4154-b026-e1f34f0d50f2.JPG)

**Comment by turbodizayn** [comment]
![Capture](https://user-images.githubusercontent.com/97593553/149098805-c5b30bd6-3206-46e5-81b2-2eb8abd5bd49.JPG)

**Comment by turbodizayn** [comment]
![Capture](https://user-images.githubusercontent.com/97593553/149099375-8f47dbfb-402d-4174-a062-44cc885827da.JPG)

**Comment by RodZill4** [comment]
The generated is what's inside the axes, and it is still tilable. The parts outside that square will be ignored when exporting.

0.98 will have an option to tile in the 2D preview.
