### ISSUE TITLE
Ambient lighting disabled on material export in some unchangable way

### ISSUE THREAD

**Issue by Jimmio92** [RodZill4/material-maker#413]
**Material Maker version:**

0.97

**OS/device including version:**

Fedora Linux Ryzen 7 AMD RX 590

**Issue description:**

I exported a material to Godot and it refuses to acknowledge any sort of ambient. No settings changes in editor fixes it. If I make a new SpatialMaterial and set the textures up manually, it works as expected.

**Steps to reproduce:**
Export a material with Roughness, Emission, and Normal is about all I did.

**Comment by Calinou** [comment]
> Export a material with Roughness, Emission, and Normal is about all I did.

Could you upload a ZIP of the material here to ease troubleshooting?

**Comment by Jimmio92** [comment]
Attached is the zip file containing the material and the textures it generated, but I think I've found the problem. My recreation of the material from SpatialMaterial defaults left metallic at 0.0. Material maker's exported value defaults that to 1.0. It seems metallic of 1.0 kills all ambient, and that's the real problem. I misunderstood how metallic works in Godot and blamed MaterialMaker potentially?

Only other thing was the IDs from the MaterialMaker export aren't in order from 1, but I doubt that matters at all. It also set a default albedo color when I never assigned it, but again... it's the metallic amount removing ambient.

[ship_test.tres.zip](https://github.com/RodZill4/material-maker/files/7875978/ship_test.tres.zip)
.
