### ISSUE TITLE
please change icon for "Warp Dilation" 

### ISSUE THREAD

**Issue by novemberist** [RodZill4/material-maker#420]
I hope I don't sound too sensitive here and I don't have a specific suggestion...but that icon really looks too much like a swastika and makes me kind of uncomfortable. I hope this can be changed for something less ambiguous in future releases.

**Comment by RodZill4** [comment]
Hmm OK. Didn't think of this. At all.
Warp dilation is about creating whirls, so they have to be there...
Does this one look OK?
![warpdilation_icon](https://user-images.githubusercontent.com/6957908/152730091-b903e0a6-0ab9-495d-b845-6e2012193ea0.png)

**Comment by RodZill4** [comment]
Ooooh, I think this one looks better.
![warpdilation_icon](https://user-images.githubusercontent.com/6957908/152730501-775b6c34-a627-4130-bfef-a30780a93a1b.png)

**Comment by RodZill4** [comment]
Or maybe just a single whirl shows best what the node does.
![warpdilation_icon](https://user-images.githubusercontent.com/6957908/152731096-e5df28e5-735c-4402-a88a-4bbeafd778e2.png)

**Comment by RodZill4** [comment]
You can grab a dev build. ;)

**Comment by novemberist** [comment]
Thank you, looks good :+1:
