### ISSUE TITLE
Crash when deleteing certain nodes in selection

### ISSUE THREAD

**Issue by jrdmellow** [RodZill4/material-maker#423]
**Material Maker version:**
0.98

**OS/device including version:**
OS: Pop!_OS 21.10 x86_64 
Kernel: 5.15.15-76051515-generic 
DE: GNOME 40.5 
CPU: 11th Gen Intel i7-11700K (16) @ 4.9GHz 
GPU: NVIDIA GeForce RTX 2070 SUPER 
GPU Driver: NVIDIA 470.86 

**Issue description:**
Selecting a group of nodes causes the application to crash. [cash_test.ptex.zip](https://github.com/RodZill4/material-maker/files/8064960/cash_test.ptex.zip)
![image](https://user-images.githubusercontent.com/3386906/153972701-69d94cfe-566d-43e3-bcd0-2151b0fc877b.png)

Box selecting the three nodes highlighted by the comment and deleting them causes the crash consistently (100% repro for me so far).

**Steps to reproduce:**

1. Create a material graph including the following nodes; Tiler, Transform, Auto Tones or load the attached sample
2. Box select the Tiler, Transform and Auto Tones nodes
3. Press the Delete key

**Comment by RodZill4** [comment]
Looks like it is fixed now...

**Comment by S00pergang** [comment]
For some reason, the program crashes sometimes when I deleted a bunch of nodes.
