### ISSUE TITLE
UX: Gallery loading

### ISSUE THREAD

**Issue by lexum0** [RodZill4/material-maker#428]
**Feature/enhancement description:**
It takes too long to load the catalog, even when it's cached, making it really slow to navigate and open materials since the UI is jumping around making it hard to use. 

1. If the data is cached, it should be loaded faster, it seems to take too long to display each thumbnail. If it's not, data should be cached
2. When there is no thumbnail each row is shown with a small height, then with the full height once the image is available. This causes the whole catalog to jump while it loads, making it impossible to read or select a material while it's still loading the images. An easy fix would be to just show a placeholder image

**Comment by RodZill4** [comment]
Images are now loaded in a separate thread (added this while implementing #427). Cannot do much more about this...

**Comment by Calinou** [comment]
> Images are now loaded in a separate thread (added this while implementing #427). Cannot do much more about this...

Could multiple be threads be used for thumbnail updates, or does it depend on the main thread anyway?

**Comment by RodZill4** [comment]
> > Images are now loaded in a separate thread (added this while implementing #427). Cannot do much more about this...
> Could multiple threads be used for thumbnail updates, or does it depend on the main thread anyway?

Thumbnails are loaded either from the disk or from the website. Using a thread separates this from UI, so it makes UI more responsive. I don't think loading thumbnails in parallel will change anything.
