### ISSUE TITLE
Add a small grey outline around gradients

### ISSUE THREAD

**Issue by Arnklit** [RodZill4/material-maker#442]
Gradients that are black at either end, fade into the node panel colour. It might be good to add a 1px grey color around the gradient.

![image](https://user-images.githubusercontent.com/4955051/161000906-2f03be51-52d4-4107-8c3d-c55a90fcb31a.png)

I can give it a go to add this in myself, I just don't have time to try now, so I thought I'd log a bug for it.

**Comment by bliepp** [comment]
I quickly submitted one since I was exploring the nodes anyway. #457
