### ISSUE TITLE
Crash After Canceled Add Parameter

### ISSUE THREAD

**Issue by Waffle1434** [RodZill4/material-maker#451]
**Material Maker version:** 0.99

**OS/device including version:** Windows 10 Latest

**Issue description:**
After cancelling the "Add linked control" or "Add configurations" operation in a node group, a new "Unnamed" parameter is created in a broken state that will instantly crash if you attempt to link a parameter to it. However, clicking "Move parameter up / down" will fix this broken state and prevent a crash.
![image](https://user-images.githubusercontent.com/8021358/166832561-e7d747d0-01fc-4ff9-af11-02b874ae5ee1.png)

**Steps to reproduce:**
1. Create group `Ctrl+G` or open an existing
2. Parameters -> "Add linked control" or "Add configurations"
3. Right or middle mouse click anywhere to cancel the operation
4. On the newly created "Unnamed" parameter -> "Link another parameter"
5. Instant crash

**Comment by meywue** [comment]
Hey @Waffle1434 

In case you cloned the project instead of using the precompiled executable, you can add the following lines to the link.gd file at line 79 to fix the problem.

`
else:
    node.generator.remove_parameter(param_name)
`

This will remove the control again once you hit MMB/RMB.
In my opinion there's a small UX problem though. If there's and existing link, you would like to update it and hit MMB/RMB, it will remove the control. But this also happened before when hitting the escape button on your keyboard.

Full file (link.gd):
`
extends Control
class_name MMNodeLink

var end
var source = null
var target = null

var node = null
var param_name : String = ""
var creating : bool = false

func _init(parent) -> void:
	size_flags_horizontal = SIZE_EXPAND_FILL
	size_flags_vertical = SIZE_EXPAND_FILL
	rect_size = parent.rect_size
	rect_clip_content = true
	parent.add_child(self)

func pick(s, n, pn : String, c : bool = false) -> void:
	source = s
	end = get_global_transform().xform_inv(source.get_global_transform().xform(0.5*source.rect_size))
	node = n
	param_name = pn
	creating = c
	set_process_input(true)

func show_link(s, t) -> void:
	set_process_input(false)
	mouse_filter = Control.MOUSE_FILTER_IGNORE
	source = s
	target = t
	update()

func closest(rect, point) -> Vector2:
	return Vector2(max(rect.position.x, min(rect.end.x, point.x)), max(rect.position.y, min(rect.end.y, point.y)))

func find_control(gp) -> Dictionary:
	for c in get_parent().get_children():
		if c is GraphNode:
			if c.get("controls") != null:
				for w in c.controls:
					var widget = c.controls[w]
					if is_instance_valid(widget) and Rect2(widget.rect_global_position, widget.rect_size*widget.get_global_transform().get_scale()).has_point(gp):
						return { node=c, widget=widget }
	return {}

func _draw() -> void:
	var start = get_global_transform().xform_inv(source.get_global_transform().xform(0.5*source.rect_size))
	var color = Color(1, 0.5, 0.5, 0.5)
	var rect
	if target != null:
		color = Color(0.5, 1, 0.5, 0.5)
		rect = get_global_transform().xform_inv(target.get_global_transform().xform(Rect2(Vector2(0, 0), target.rect_size)))
		draw_rect(rect, color, false, 2)
		end = closest(rect, start)
	rect = get_global_transform().xform_inv(source.get_global_transform().xform(Rect2(Vector2(0, 0), source.rect_size)))
	draw_rect(rect, color, false, 2)
	start = closest(rect, end)
	draw_line(start, end, color, 1.5, true)

func _input(event: InputEvent) -> void:
	if event.is_action_pressed("ui_cancel"):
		set_process_input(false)
		queue_free()
		node.generator.remove_parameter(param_name)
	if event is InputEventMouseMotion:
		var control = find_control(event.global_position)
		end = get_global_transform().xform_inv(event.global_position)
		target = control.widget if control != null and !control.empty() and node.generator.can_link_parameter(param_name, control.node.generator, control.widget.name) else null
		update()
	elif event is InputEventMouseButton:
		if event.pressed:
			if event.button_index == BUTTON_LEFT:
				var control = find_control(event.global_position)
				if !control.empty():
					node.link_parameter(param_name, control.node.generator, control.widget.name)
				elif creating:
					node.generator.remove_parameter(param_name)
			else:
				node.generator.remove_parameter(param_name)
			set_process_input(false)
			queue_free()
	get_tree().set_input_as_handled()
`

**Comment by RodZill4** [comment]
@Waffle1434 @meywue Please don't hesitate to grab latest dev build and tell me if this works for you. Thanks!

**Comment by meywue** [comment]
Hey, thanks for looking into it. Unfortunately I can still reproduce crashes. And depending on the version I use they seem to be different.

---
master branch, fresh clone, v3.4.4.stable.official [419e713a2] [29762be](https://github.com/RodZill4/material-maker/commit/29762be7f7f5c599f67547ed213c5b28d0afcaed) (latest Godot version on steam in case that's relevant)

Repro:
* Add Remote node
* Hit 'Add linked control'
* Cancel action by hitting RMB
* Hit 'Add linked control' again
[video](https://www.dropbox.com/s/emb6z92c4k2e6tf/material_maker_%23451.mp4?dl=0) You might have to download it, the quality in the web player is horrific.

---
[dev build](https://github.com/RodZill4/material-maker/actions/runs/2407262944)

Repro:
* Add Remote node
* Hit 'Add linked control'
* LMB on an empty spot (try a few times, seems to be a kinda random)
(note: I can't even cancel the action with RMB here)
[video](https://www.dropbox.com/s/gvc8spf0u52ksyl/material_maker_%23451b.mp4?dl=0)

---
The PR I posted [here](https://github.com/RodZill4/material-maker/pull/458) was just bypassing the actual underlying problem.
