### ISSUE TITLE
Divide by 0 crash with math node and depth

### ISSUE THREAD

**Issue by ajknowles11** [RodZill4/material-maker#452]
**Material Maker version:** 0.99

**OS/device including version:** Windows 10 Latest

**Issue description:**

Had 3d view open. Inserted math node between pattern and output to divide pattern colors by 2, switched math node to divide before changing B from 0, crashed.

**Steps to reproduce:**
1. Open material maker and open 3d preview
2. Connect a math node output to output material depth
3. While B is still 0, change math mode to divide
4. Crash

**Comment by RodZill4** [comment]
Probably fixed by 41ee5a0. Will have to check.
