### ISSUE TITLE
Drag and Drop material causes an error on Exported version

### ISSUE THREAD

**Issue by wyattbiker** [RodZill4/material-maker#46]
Mac OS X,
Godot 3.2 alpha2

0.6 Drag and Drop material. E.g. Brick:

Running it through the IDE works fine except for the **Warnings**

But when Exported and run as an app produces the warnings AND error when dragging and dropping. Looks like the load() method for preview. This is what shows up in the logs.

> HERE0
> res://addons/material_maker/library/base/bricks.png
> HERE1
> HERE1.5
> HERE2
> **WARNING**: This method has been deprecated and will be removed in the future
>    At: scene/resources/texture.cpp:239:load() - This method has been deprecated and will be removed in the future
> **WARNING**: Loaded resource as image file, this will not work on export: 'res://addons/material_maker/library/base/bricks.png'. Instead, import the image file as an Image resource and load it normally as a resource.
>    At: core/image.cpp:1877:load() - Loaded resource as image file, this will not work on export: 'res://addons/material_maker/library/base/bricks.png'. Instead, import the image file as an Image resource and load it normally as a resource.
> **ERROR**: Error opening file 'res://addons/material_maker/library/base/bricks.png'.
>    At: core/io/image_loader.cpp:56:load_image() - Error opening file 'res://addons/material_maker/library/base/bricks.png'.
> HERE3
> here4

Lines of code with issue:
**library.gd**
```gdscript
func get_drag_data(position):
	var selected_item = get_selected()
	if selected_item != null:
		var data = selected_item.get_metadata(0)
		if data == null:
			return null
		var preview
		if data.has("icon") && data.has("library"):
			print("HERE0")
			var filename = data.library.left(data.library.rfind("."))+"/"+data.icon+".png"
			print(filename)
			print("HERE1")
			preview = TextureRect.new()
			print("HERE1.5")
			preview.texture = ImageTexture.new()
			print("HERE2")
			preview.texture.load(filename)
			print("HERE3")
		elif data.has("type") and data.type == "uniform":
			preview = ColorRect.new()
			preview.rect_size = Vector2(32, 32)
			if data.has("color"):
				preview.color = Color(data.color.r, data.color.g, data.color.b, data.color.a)
		else:
			preview = Label.new()
			preview.text = data.tree_item
		print("here4")
		set_drag_preview(preview)
		return data 
	return null
```

**Comment by RodZill4** [comment]
Exported version should not contain the library files but in a separate directory. Same applies to examples and .mmg files. Unfortunately I don't have a Mac so I cannot help much with a Mac build...

**Comment by RodZill4** [comment]
That's an old MacOSX issue. See #140 for MacOSX status.
