### ISSUE TITLE
Entering incomplete/invalid $rnd expression causes freeze

### ISSUE THREAD

**Issue by fccDunce** [RodZill4/material-maker#465]
**Material Maker version:**

0.99

**OS/device including version:**

Windows

**Issue description:**

Entering an incomplete $rnd expression into a field (e.g scale_x in transform node), and then clicking outside before completing the expression causes MM to freeze. 

- Example of icomplete expression: _$rnd(1._

**Comment by RodZill4** [comment]
Fixed in [4cd578f](https://github.com/RodZill4/material-maker/commit/4cd578f2790784a918c00c018d470af179a94c1e)
