### ISSUE TITLE
Very slow movement of Linux windows

### ISSUE THREAD

**Issue by CocoR55** [RodZill4/material-maker#473]
Hello,
I use Appimage for different Linux Mint 20.3: Cinnamon, Mate, XFCE with the same hard materail.
However only with XFCE, I get an issue.
I can move the windows right, left, up and down but they move very very slowly.
The processors don't have much activity in the 5% range. The RAM is not used much, about 10%.
If I don't start Appimage, no problem while I start Appimage with whatever the associated application, the problem occurs. I must kill Xorg to stop issue with all running applications....
Do you have any idea?
Regards,
CocoR55

**Comment by Calinou** [comment]
What graphics card model and driver are you using?

Can you reproduce this if you disable compositing in the Xfwm options (or if it's already disabled, enable it)?

**Comment by CocoR55** [comment]
Graphics:  Device-1: VMware SVGA II Adapter driver: vmwgfx v: 2.15.0.0 bus ID: 00:02.0 chip ID: 15ad:0405 
           Display: x11 server: X.Org 1.20.13 driver: vmware unloaded: fbdev,modesetting,vesa compositor: marco 
           resolution: 1920x1095~60Hz 
           OpenGL: renderer: SVGA3D; build v: 2.1 Mesa 21.2.6 direct render: Yes 
 Great idea. If the Xfwm compositor is disabled, they are any more problem. If the Xfwm compositor is enabled, problem occurs.

**Comment by RodZill4** [comment]
Hmm are you trying to use Material Maker in a VM? I'd strongly advise against doing this, because MM relies on shaders to compute all textures, so hardware acceleration is required.

**Comment by CocoR55** [comment]
For information, with Firejail or with Flatpak, this is the same. If the Xfwm compositor is disabled, they are any more problem. If the Xfwm compositor is enabled, problem occurs.

**Comment by CocoR55** [comment]
I don't but I am going to try and I will say to you.
I'm not sure but I feel like I can do without the enabled Xfwm compositor.
Thank you for help.

**Comment by CocoR55** [comment]
You are right. Following Material Maker installation, an error window indicates that "Unable to initialize Video driver"  " Your video card driver does not support any of the supported OpenGL versions. Please update your drivers or if you have a very old or integrated GPU upgrade it."
