### ISSUE TITLE
How can I create an installable, standalone export?

### ISSUE THREAD

**Issue by rcorre** [RodZill4/material-maker#478]
**Material Maker version:**

dab44d2c762406c0869843ce698d8ad1bc8f917d

**OS/device including version:**

Linux 5.18.3-arch1-1

**Issue description:**

When I run Material Maker from the editor (godot 3.4), it works fine.
When I export it, I cannot add any nodes to the graph, and get errors like:

```
LOADER: data not supported:{name:Material, parameters:{size:11}, type:material}
Cannot create gen {name:Material, parameters:{size:11}, type:material}
```

I noticed the builds copy a bunch of files beside the executable: https://github.com/RodZill4/material-maker/blob/dab44d2c762406c0869843ce698d8ad1bc8f917d/.github/workflows/dev-desktop-builds.yml#L46-L60.
Is there a way to bake the necessary files into the executable as resources, so you can have a single standalone binary that could be installed to `/usr/bin`? If not, do the files have to reside next to the executable, or is it possible to put them in a separate location? E.g. could I have `material_maker` installed to `/usr/bin` and the data files in `/usr/share`?

**Steps to reproduce:**

**Comment by RodZill4** [comment]
You just have to mimic how MM is packaged (with node, doc, library... directories alongside the binary and pck  file). But I'm not sure why you'd want to do this. Even if all those resources were embedded in the .pck, there would still be 2 files.

**Comment by rcorre** [comment]
There's only be one file if you choose "embed pck". I'd want to do this to install it on my system, and possibly write an AUR package for it. It would be unusual for a linux package to install a bunch of data files under `/usr/bin`, hence the desire to either bake them in, or place them in a separate spot that could be configured (e.g. `/usr/share`).
