### ISSUE TITLE
Color picker in Reference panel not working

### ISSUE THREAD

**Issue by KJO** [RodZill4/material-maker#490]
**Material Maker version:**

1.0

**OS/device including version:**
Windows 11

**Issue description:**

Hasn't been working since version 0.97

**Comment by RodZill4** [comment]
Could you please describe how you (try to) use the reference panel and what does not work?
Did it work prior to 0.97?

**Comment by KJO** [comment]
Hi
In version 0.97 i would click one of the boxes under the reference image and then on the image itself to get a color, 
just as described in the documentation under reference panel page.

It stopped working in version 0.98.

It's a very nice feature especially the ability to quickly construct a gradient.
