### ISSUE TITLE
Godot 3.1 beta freezes when adding Image

### ISSUE THREAD

**Issue by me2beats** [RodZill4/material-maker#5]
Godot 3.1 beta 2 freezes when adding Image box (generator - image).
Material maker 0.6, Master branch, windows 10 64

**Comment by Calinou** [comment]
@me2beats Can you still reproduce this on the current `master` branch (or `export_plugin` branch, which is more recent)?

**Comment by Calinou** [comment]
@RodZill4 This issue can probably be closed now.

**Comment by me2beats** [comment]
it seems to work now.
sorry, I didn't watch this project for a while,
so many new features added, just wow)
