### ISSUE TITLE
canvas_item shader_type

### ISSUE THREAD

**Issue by novalis** [RodZill4/material-maker#511]
**Feature/enhancement description:**

For 2d textures in Godot, the `shader_type` is `canvas_item`, and output goes to `COLOR=` in the `vertex()` function (rather than `fragment()`).  There should be a new type of material, called something like "Dynamic 2D material" to support this.

**Comment by novalis** [comment]
[material_2d.txt](https://github.com/RodZill4/material-maker/files/9472563/material_2d.txt)

Something like this -- but I have no idea what to do for Unity or Unreal, so ignore those parts.

**Comment by RodZill4** [comment]
I guess this could just be an export option of the dynamic unlit material.
