### ISSUE TITLE
Filmic tone mapper aka ACEScg.

### ISSUE THREAD

**Issue by ratherrandomaccname9000** [RodZill4/material-maker#530]
I am guessing MM does not have tone mapper and that is the reason for huge difference the way things look in Unreal and Material Maker. Without it 3d preview is so different it is impossible to judge material in MM and you have to keep switching to Unreal. Saturation basically doubles. So ACEScg tone mapper would be nice. But I am guessing it is already on your radar.

**Comment by Calinou** [comment]
Godot has tonemapping settings (including ACES Fitted – which is similar to the default UE4/5 tonemapper. However, these settings aren't exposed in Material Maker.

Changing the default tonemapper will change how materials appear by default, so changing the default to ACES Fitted should be considered carefully. Also, a whitepoint greater than 1 should be used to prevent highlights from being blown out (`6.0` is a good starting point).

**Comment by ratherrandomaccname9000** [comment]
I see. So basically it is a matter of exposing them. Similar would be good enough. A choice of tonemapper in settings would be good.

By the way changing the default look of how things in MM is the whole point. People don't create materials in MM to just look at them. The target is some realtime or offline external engine. It does not matter how good or bad something looks in MM if when as soon as it gets exported it looks drastically different. I legit turned off 3d view because it tells me absolutely nothing and most things use some sort of filmic tone mapper these days.

**Comment by RodZill4** [comment]
That could be in the 3D preview settings. Would any other option from Godot environments be useful?

**Comment by ratherrandomaccname9000** [comment]
Sorry am not an expert on Godot, played with it once a while ago. Antialiasing perhaps? Shader quality (as in shader samples) if Godot even has something like that. Dunno srgb/linear switch for roughness in 3d preview settings?
