### ISSUE TITLE
Opening the "Load Material from Website" view with no internet connection causes MM to crash

### ISSUE THREAD

**Issue by Arnklit** [RodZill4/material-maker#535]
**Material Maker version:**
Material Maker 1.0

**OS/device including version:**
Windows 10

**Issue description:**
Opening the "Load Material from Website" view with no internet connection causes MM to crash.

**Steps to reproduce:**
Disable your internet connection and try to launch the view.

**Comment by RodZill4** [comment]
Fixed!
