### ISSUE TITLE
Material Makes whole desktop unresponsive and crashes.

### ISSUE THREAD

**Issue by LimaneGaya** [RodZill4/material-maker#541]
When i load materials from the website or when i import them some of them makes the whole desktop freeze and flicker and get unresponsive with only the mouse position able to refresh and i'd have to hard reboot the computer.
I really like the software but the issue makes me second guess when i want to use it.
using kde neon 5.26
6gb rab
amd apu

**Comment by Calinou** [comment]
> amd apu

Which exact APU model do you have?

What's the resolution you're trying to render at? Integrated graphics don't do well with high-resolution textures, especially in complex graphs. You probably want to stick to 1024×1024.

**Comment by RodZill4** [comment]
There's still something you can do if you have a low end GPU (or if you want a very smooth Material Maker while creating materials):

- right click on the progress bar (top right, will be bottom-right in 1.1)
- uncheck the "auto" option
- set the number of renderers to 1
- set the maximum buffer size to 512 (this wil render lower resolution/quality materials and some nodes might render incorrectly, but you should avoid crashes)
- then load materials

**Comment by LimaneGaya** [comment]
> Which exact APU model do you have?
It's an old notebook apu.
Tried rendering at 2048x2048

**Comment by LimaneGaya** [comment]
> * right click on the progress bar (top right, will be bottom-right in 1.1)

Thanks, i didn't know about these settings, the app no longer crashes.

**Comment by Calinou** [comment]
This issue can be closed as it seems to have been resolved by OP.
