### ISSUE TITLE
Add Support for drawing tablets and pen pressure sensitivity

### ISSUE THREAD

**Issue by Alriightyman** [RodZill4/material-maker#548]
**Feature/enhancement description:**
It would be great to use a drawing tablet and pen pressure to lightly color a model using this application. 
Pen sensitivity could help by either being bound to opacity - lighter pressure less opacity; or bound to brush size - lighter pressure smaller brush size, harder pressure larger brush size; or both.  

Having a small toggle button by those options in the app so you could turn them off/on would be nice as well - for an example, see Blender's Texture painting tool.

**Comment by RodZill4** [comment]
Painting already supports pressure and tilt. You just have to create brushes that support this feature (use the "pressure" variable in any parameter expression).

**Comment by mika314** [comment]
![image](https://user-images.githubusercontent.com/1877406/201979417-94ca6430-0179-495e-81c6-7eb8047df891.png)
This is an example of how you can apply the pressure variable in the node graph.

**Comment by Alriightyman** [comment]
> Painting already supports pressure and tilt. You just have to create brushes that support this feature (use the "pressure" variable in any parameter expression).
Ah, I see. Thanks. 



> ![image](https://user-images.githubusercontent.com/1877406/201979417-94ca6430-0179-495e-81c6-7eb8047df891.png)
> This is an example of how you can apply the pressure variable in the node graph.

This was very helpful. Thank you
