### ISSUE TITLE
Godot 3 export is not working with depth

### ISSUE THREAD

**Issue by MikeFrom** [RodZill4/material-maker#575]
**Material Maker version:** 1.1

**OS/device including version:** Windows 10, Geforce GTX 1080, 8 GB

**Issue description:**
Exporting to Godot 3, depth doesn't show up in Godot 3.5.1.

**Steps to reproduce:**
1. I've made a material in Material Maker with nobs with depth:
[knobs_with_depth.zip](https://github.com/RodZill4/material-maker/files/10333352/knobs_with_depth.zip)

2. Export to Godot 3
<img width="1624" alt="Material_Maker_depth_and_godot_3_export_test" src="https://user-images.githubusercontent.com/50963378/210274580-65a70d04-edfc-41cc-984e-23249461dfa3.png">

3. In Godot 3.5.1 material is cut and depth is not shown
<img width="985" alt="Godot_3_Material_Maker_material_not_showing_depth" src="https://user-images.githubusercontent.com/50963378/210274596-ce2d84ce-dc1c-490f-a88c-a80278569b3a.png">

[godot230102_material_maker_depth_test.zip](https://github.com/RodZill4/material-maker/files/10333367/godot230102_material_maker_depth_test.zip)

**Comment by Calinou** [comment]
This is not an issue with Material Maker. Godot's CubeMesh (BoxMesh in 4.0) is designed to display 6 faces with individual textures. To display the same texture on each face, you need to set the material's UV1 to `(3, 2, 1)`.
