### ISSUE TITLE
Exported images from Paint Project are all blank

### ISSUE THREAD

**Issue by werdnahull** [RodZill4/material-maker#599]
**Material Maker version:**
1.2p1

**OS/device including version:**
Windows 10
Geforce GTX 1650 Super

**Issue description:**
From a Paint Project, all exported albedo, depth, emission, and orm images are all white, and the normal is all green, in any export format chosen (Godot 3/4, Unity, Blender, etc). 
My paint project texture size is 1024x1024, all other settings default. 

Project layers:
![image](https://user-images.githubusercontent.com/10228963/231369021-6de7adbc-f28e-460e-8516-e447da26b461.png)

Exported images:
![image](https://user-images.githubusercontent.com/10228963/231369101-ff148c9e-f53a-4ffb-83ec-9486b9069edd.png)

**Steps to reproduce:**

1. Create a new paint project
2. Add some layers, paint some things
3. Export as Godot 3

**Comment by RodZill4** [comment]
Fixed for 1.3
