### ISSUE TITLE
Memory leak and crash on saving new paint project for specific Linux device

### ISSUE THREAD

**Issue by belzecue** [RodZill4/material-maker#605]
Attempting to create a new Paint project leads to rapid memory exhaustion and program crash/termination.

**Material Maker version:**
1.3 Linux

**OS/device including version:**
Not graphics related.
MX Linux 21.3 (Debian 11.6)
XFCE 4.18.1
CPU: Dual Core Intel Celeron 3215U (-MCP-) speed/min/max: 798/500/1700 MHz 
Kernel: 5.10.0-21-amd64 x86_64
MEM: 4G

**Issue description:**
At startup, attempt to create a new paint project using the suzanne mesh obj from meshes folder and after clicking OK all memory is rapidly consumed until the kernel automatically terminates Material Maker.

I cannot take a screen recording due to the whole 'kills every running program' side effect, but I've included a screenshot of task manager showing the memory leak and termination.

**Steps to reproduce:**

1. Open Material Maker 1.3 on Linux
2. Choose FILE > NEW PAINT PROJECT
3. For the model, choose the suzanne.obj under the meshes subfolder
4. Click on PROJECT and enter a filename to save this project under, in another folder somewhere
5. All good so far.  Now click OK and see if it consumes all available memory and crashes.

![Screenshot_2023-04-25_11-05-11](https://user-images.githubusercontent.com/1931303/234165833-00be9c2b-cabe-4c0f-9e0e-e8e35596b3b8.png)

![Screenshot_2023-04-25_11-00-20](https://user-images.githubusercontent.com/1931303/234165852-88e9689b-63b8-4ca1-8173-1094b78d925e.png)

**Comment by RodZill4** [comment]
Hmm what's your GFX card? Which texture resolution did you choose when creating the paint project?

**Comment by belzecue** [comment]
I tested on a much less capable device -- basically as potato as you can get, an Intel Compute Stick (ICS) with 2G ram -- and a new paint project opened fine (eventually).  Same MX Linux version running there, so it's unlikely to be the OS.

In my testing, I use the default 1K texture resolution.  I'm performing the same steps every time.

I'll do some more testing on the offending device to try to isolate what's going on with it.

**Comment by belzecue** [comment]
Looks like memory requirements have jumped between 1.0 and 1.3.

On an Intel [ICS](https://www.intel.com.au/content/www/au/en/products/sku/91065/intel-compute-stick-stk1aw32sc/specifications.html) device with 2G memory (don't laugh!), under Windows 10, I can run 1.0 but 1.3 crashes during load with a memory exhaustion error:

![startup crash on ICS win10](https://user-images.githubusercontent.com/1931303/235335416-91ed4849-9720-4bc2-9e9a-51f0817b4559.PNG)

**Comment by belzecue** [comment]
Closing.  My testing between devices and OSes was inconclusive other than to suggest that the newer release simply needs more memory.
