### ISSUE TITLE
Sub-windows can't be closed with the X in the corner.

### ISSUE THREAD

**Issue by MadMinstrel** [RodZill4/material-maker#613]
**Material Maker version:**
fd90ecc29f0922a6c12bd0331360cc7f05a2452b

**OS/device including version:**
Windows 11, nvidia.

**Issue description:**
Sub windows can't be closed with the X in the corner.

**Steps to reproduce:**
1. Open About window or Environment Editor
2. Try to close it.

**Comment by RodZill4** [comment]
I'll create a thread on Discord for 1.4 bug hunting, so we don't get a million new requests here. ;)
