### ISSUE TITLE
Connect to website problem in Safari/ macOS Ventura

### ISSUE THREAD

**Issue by artoonick** [RodZill4/material-maker#616]
**Material Maker version:**
v1.2p1

**OS/device including version:**Apple M1 Pro, MacOS Ventura 13.3.1, Safari Version 16.4 

**Issue description:**
"Connect to website" top right button opens Safari browser. After the browser login the link icon is still white/not connected to website.

<img width="512" alt="Screenshot 2023-05-24 at 23 25 17" src="https://github.com/RodZill4/material-maker/assets/52720857/d5441c87-ba52-4f66-8b35-137473609b1d">

**Comment by RodZill4** [comment]
This should be fixed in 1.3.
