### ISSUE TITLE
Material Maker for Android?

### ISSUE THREAD

**Issue by pemguin005** [RodZill4/material-maker#627]
**Feature/enhancement description:**

There have been many times where I want to work on making materials casually while on the go. In waiting rooms, on buses, watching TV etc. Is the performance requirements for MM too great for mobile devices or would a mobile version be a possibility in the future?

**Comment by Calinou** [comment]
The issue is that Android GPU drivers are all over the place, so I wouldn't be surprised if output ends up looking different compared to desktop platforms.

Adapting the UI to work well on mobile is also a lot of work.

**Comment by Zireael07** [comment]
.. or MM crashes/refuses to work outright. Android GPUs really ARE all over the place.

**Comment by RodZill4** [comment]
I had a working MM on my (android) phone, but there's still a lot of work (mainly UI related) for anything usable.

**Comment by pemguin005** [comment]
GPUs and how heavy the workload can get is reason enough. Closing the ticket
