### ISSUE TITLE
3D Preview doesn't refresh

### ISSUE THREAD

**Issue by orestiskon** [RodZill4/material-maker#64]
Fantastic work on this tool. I'll get to the bug:

It happens often that the 3D preview of a material doesn't refresh, thus providing false feedback.
I'm using material maker v0.8 on Windows 10 with an AMD Vega 64 GPU and a Ryzen 1700x CPU.

![refresh_fail](https://user-images.githubusercontent.com/14933041/72918766-882ee080-3d46-11ea-908c-655f874ca4fb.gif)
In the attached gif you can see that I'm disconnecting all material ports but the preview isn't changing. Changing settings oftentimes fails to refresh as well, and reloading the file produces inconsistent results that are different each time.
The material file is also attached:
[sdf_operations.zip](https://github.com/RodZill4/godot-procedural-textures/files/4098891/sdf_operations.zip)

**Comment by RodZill4** [comment]
Hmm looks like a problem in shader generation (related to function/variable name collisions between 2 nodes).
