### ISSUE TITLE
[ Feature ] Painting - add ID Mask support

### ISSUE THREAD

**Issue by iwubcode** [RodZill4/material-maker#658]
I just found out that some programs have a fancy way to add materials to painted surfaces by using a single color mask called an "id mask".  The advantage is it's a much faster way than manually making masks via nodes or through layers.

Examples:

https://www.youtube.com/watch?v=qelqpR_mTSM
https://www.youtube.com/watch?v=wHjLNLrAmZo

I didn't see it in the documentation so I thought I'd request it.

Semi related to #585  (which I need to get back to trying, I didn't have a workflow to test on before).

Thanks again for this great program!

**Comment by RodZill4** [comment]
There is already a tool to define a mask for painting or filling (rightmost button in the painting tool).

**Comment by iwubcode** [comment]
Works perfectly.  Thanks!

**Comment by iwubcode** [comment]
@RodZill4  - actually, can't seem to zoom out in the mini id-map window?

Would it be possible to add an option to sync to the main window?

**Comment by iwubcode** [comment]
Example:

![image](https://github.com/RodZill4/material-maker/assets/15224722/b57ec20c-09f7-4324-9ce3-b32d69ce05e5)

**Comment by RodZill4** [comment]
I think I will completely change the UI for this. Porting it to Godot 4, I realized it's a PITA it is in a popup.
I guess I will make it a tool, just like color picker, and add it to the brush/jitter part of the UI.
