### ISSUE TITLE
Add exclusive view or preview for diffuse texture workflow

### ISSUE THREAD

**Issue by kaphula** [RodZill4/material-maker#671]
**Feature/enhancement description:**

Currently if you want to view a flat unlit version of your generated diffuse texture you have to select a node at the end of the node pipeline so that the correct results will be displayed on the 2D preview. If you are only interested in generating 2D diffuse textures, this workflow gets very tedious. By diffuse texture I mean the end results as pixels which will be saved to the disk as a regular image file. 

The 3D view displays the diffuse texture on the 3D object's surface, but issue here is that you cannot modify the scene so that all lighting calculations are turned off. The results on the surface of the 3D object are not the same as what can be seen when the texture is saved to disk. You cannot for example see the darkest pixels because the 3D lighting calculatations light these pixels in 3D view depending on the orientation of the object.

**Possible solutions**
- Allow users to lock a specific node to a separate 2D viewport. In my case this would mean locking the last node next to Static PBR Material node. Since Material Maker already supports multiple view windows, it would be nice to have this locked viewport and a separate viewport for the currently selected node 2D preview for best user experience.

- Allow flat shading in 3D viewport which would make the texture on the surface of the 3D object look exactly the same as on the disk as an image file.

**Extra**

Allow exporting the resulting texture as an image for those who don't care about game engines. This is not a big deal as you get the textures anyway when you export for Blender for example, but it would still be nice thing to have.

**Comment by RodZill4** [comment]
A possible solution is to set albedo to black, roughness to 0 and and metal to 1 and connect your texture to emission. Itg would also be possible (and easy) to create a new material type for this.
You can already export the 2D preview as a single texture (right click the preview).

**Comment by kaphula** [comment]
Thanks! This works mostly. The 3D view is still lighter than the 2D view, unless I did something wrong with the settings:

![image](https://github.com/RodZill4/material-maker/assets/36015558/3596b71d-093c-480a-906d-81b53a11f26c)

![image](https://github.com/RodZill4/material-maker/assets/36015558/18c95629-db0f-4d73-ac6e-d9e25e4fae18)

**Comment by williamchange** [comment]
> * Allow users to lock a specific node to a separate 2D viewport

![image](https://github.com/RodZill4/material-maker/assets/830253/73eff9d5-13d6-4178-a7cc-2e6edfde7b41)

You should already be able to do this with the Preview(2) window(shift left-click any output port of a node to use it):

![preview2](https://github.com/RodZill4/material-maker/assets/830253/aa251726-35e5-4927-80fa-fe910cb5fba0)

**Comment by kaphula** [comment]
> You should already be able to do this with the Preview(2) window(shift left-click any output port of a node to use it):

Very cool, thanks! This works for me.
