### ISSUE TITLE
Materials with AO turn black when converting to shader in Godot

### ISSUE THREAD

**Issue by nan0m** [RodZill4/material-maker#672]
**Material Maker version:**
v1.3

**OS/device including version:**
Win10 RTX 3070

**Issue description:**

I export a MM-material to godot.
In Godot I have a nice working material but now I want to convert that material to a shader in Godot.
I press convert to shader.
If Ambient Occlusion was enabled on the material. The material will look fine in the editor view but once I start the game it's completely black.
If I unticked Ambient Occlusion it is fine.

If I simply recreate the whole material using the texture maps in Godot, this doesn't happen and it works

**Comment by nan0m** [comment]
my bad, the error must be something else. As it just happened again whilst I respected everything I wrote before

**Comment by Megalomaniak** [comment]
Based on the description it sounds like the break happens on godot side when converting material into shader. You might want to open an issue on their side too?

**Comment by Favkis** [comment]
I am trying to gear parallax code from spatial to shader and same thing - after converting to text shader, it doesnt work.
