### ISSUE TITLE
Name port / group / node outputs or parameters

### ISSUE THREAD

**Issue by Pydes-boop** [RodZill4/material-maker#679]
Im sure i am simply missing the right words to find it in the documentation or in another issue and its somewhere, but im struggling to find any possibility to name any of my output parameters of a group so i have a name that is always visible when using these groups in the parent.

Basically i want the description / name that is to the right of the dot / mouse right now and only shows when i hover over the dot, but as an always visible name to the left of the dot and i cannot figure out how.

![image](https://github.com/RodZill4/material-maker/assets/59734957/9b366ba5-4b3e-48ca-bf0f-bdaab3a12aa6)

![image](https://github.com/RodZill4/material-maker/assets/59734957/dac13346-0ab2-4326-a595-92dc2de76f5b)

**Comment by RodZill4** [comment]
No, it's not possible that name, and I don't plan to change this (nodes are large enough already). What I could add is an option so the text on the right is always shown, but I'm not sure it is a good idea.

**Comment by Pydes-boop** [comment]
Ah okay thank you, i thought i was going crazy because i couldnt find the right keyword ,:D

I didnt realize that the inside space of the node is taken up by parameters if such are added, now it makes sense how this "empty" space is used.

I think an option to always display it would be great for readability of graphs both for inputs and outputs, this could be a simple eye toggle inside a group or something similar. But i do understand that that would add even more UI to the outputs and inputs of nodes.
