### ISSUE TITLE
Mac OS X runs fine. But there is an error on startup

### ISSUE THREAD

**Issue by wyattbiker** [RodZill4/material-maker#68]
Hi, I tested it with Godot RC 2 on Mac OS X Mojave. Runs good. However on startup there is this error. Maybe it is irrelevant.

E 0:00:02.517   get_child: Index p_index=-1 out of size (data.children.size()=1)
  <C++ Source>  scene/main/node.cpp:1296 @ get_child()
  <Stack Trace> tabs.gd:52 @ get_current_tab_control()
                main_window.gd:120 @ get_current_graph_edit()
                main_window.gd:496 @ update_preview_3d()
                preview_3d.gd:42 @ _on_Model_item_selected()
                preview_3d_ui.gd:23 @ _on_Model_item_selected()
                main_window.gd:76 @ _ready()

**Comment by freder** [comment]
for me it does not seem to work in godot 3.2.1.

I get this, when I run the project:

![Screenshot 2020-04-19 at 16 11 50](https://user-images.githubusercontent.com/724844/79690042-b1351380-8258-11ea-871f-43e20e742997.png)

**Comment by RodZill4** [comment]
That's an old MacOSX issue. See #140 for MacOSX status.
