### ISSUE TITLE
Add to Homebrew

### ISSUE THREAD

**Issue by 3Samourai** [RodZill4/material-maker#695]
**Feature/enhancement description:**
Since it's possible on Windows, it would be interesting for macOS users like me to install Material Maker with Homebrew Cask.

**Comment by williamchange** [comment]
I already have the cask for 1.3 written so I'm just waiting @RodZill4 to add the dmg/artifact the the [release page](https://github.com/RodZill4/material-maker/releases/tag/1.3) then I can try submitting the PR to Homebrew.

**Comment by RodZill4** [comment]
Just added the dmg file to 1.3.

**Comment by williamchange** [comment]
material-maker 1.3 was accepted as a cask so this issue could probably be closed
https://formulae.brew.sh/cask/material-maker
