### ISSUE TITLE
Only "Modern" theme is usable on Linux

### ISSUE THREAD

**Issue by ivxvm** [RodZill4/material-maker#711]
**Material Maker version:**
Latest master (https://github.com/RodZill4/material-maker/commit/855b270a58b771ee3b42f8d1ef651ec3202edec5), but also present in released `1.4a` build. Doesn't happen in `1.3`.

**OS/device including version:**
`Pop!_OS 22.04 LTS x86_64`

**Issue description:**
Only `Modern` theme is usable, other themes have issues like dark fonts on dark backgrounds, weird borders around some controls, etc.

`Modern` theme:

![Screenshot from 2024-10-23 15-45-02](https://github.com/user-attachments/assets/c55695b1-d267-43e8-9434-dd02ad08898b)

Other themes all have the same issues as this:

![Screenshot from 2024-10-23 15-44-51](https://github.com/user-attachments/assets/e105e2b9-559f-4cd9-b217-79ca722208f6)

**Steps to reproduce:**
Run on Linux. Select any theme other than "Modern".

**Comment by Jowan-Spooner** [comment]
This should be fixed now on master, mainly because most other themes have been removed/redone.

**Comment by ivxvm** [comment]
@Jowan-Spooner 
Checked the latest master, all 3 themes present now are working good. Thank you!
