### ISSUE TITLE
Material Maker crashes very badly under Windows with Godot 3.2.RCs

### ISSUE THREAD

**Issue by RodZill4** [RodZill4/material-maker#73]
This project crashes with (at least) 3.2RC2 and 3.2RC3 under Windows. Did not test under Linux (@Calinou ?). Didn't start investigating yet, but I doubt it's a Godot problem (all my other projects just run fine).

**Comment by RodZill4** [comment]
OK, MM 0.7 works perfectly, so just have to dichotomy the problem.

**Comment by Calinou** [comment]
Material Maker works on Linux with Godot at commit b75fff5a5 (roughly RC3).

The Flatpak I'm currently making crashes on start, though. I don't know why, I just get a segmentation fault on startup.

**Comment by RodZill4** [comment]
OK. The problem I have is caused by radiance size in panorama skies. If I set a value above 512 it crashes. It may be a Godot/Windows problem, right ?

**Comment by Calinou** [comment]
@RodZill4 It's likely hardware/driver-specific as there have been many issues related to radiance map generation in the 3.2 RCs. Are you using an AMD graphics card?

Quoting @clayjohn on IRC:

> \<clayjohn\> Calinou: we can't help that. If you run too much in one draw call it will hang the GPU. AMDs are especially sensitive and will usually \[abort\] quite early.
> \<clayjohn\> On my laptop it'll hang on 512 or higher, my desktop uses NVidia so it holds on a lot longer and can do 2048 with with the update.

**Comment by clayjohn** [comment]
@Calinou The default radiance size is 128 right now. There is no real visual difference between 256 and higher. I don't see any reason why a user should use something larger than 256.

**Comment by Calinou** [comment]
@clayjohn I meant the default radiance size in Material Maker :slightly_smiling_face:

**Comment by clayjohn** [comment]
@Calinou Oh, my bad. I followed the link thinking it was to an issue on the Godot github. 

Then yes, I would reduce to at least 256. Unless you have a compelling reason, 128 is probably the best default. With the changes I made, you get very high quality radiance at a very low radiance size compared to 3.1 where you needed a high radiance size to get good quality.

**Comment by RodZill4** [comment]
There's a huge quality difference. 256 is definitely not enough. 512 is OK, but will look worse than Material Maker 0.8. :(

**Comment by RodZill4** [comment]
@Calinou I have an NVidia GeForce GTX 960M. Must test on other PCs... But it works perfectly with 3.1.2.

**Comment by bruvzg** [comment]
macOS 10.15.2, AMD FirePro D300, it works with both 3.2.master and 3.1.2.stable.

With 3.1.2 it starts instantly and works smoothly.
With 3.2 startup takes almost 30 seconds, and it stutters every time node is selected or changed.

**Comment by clayjohn** [comment]
I just did a comparison so that you could see the difference between 1024 (current default) and 256 (suggested default)

**1024:**
![1024](https://user-images.githubusercontent.com/16521339/73102839-8df00780-3ea7-11ea-9601-6b19f2a3e42a.png)

**256:**
![256](https://user-images.githubusercontent.com/16521339/73102855-96484280-3ea7-11ea-99f7-b869cdc98a2c.png)

**128: (Godot default)**
![128](https://user-images.githubusercontent.com/16521339/73102869-9e07e700-3ea7-11ea-9e1a-1319568e9815.png)

**Comment by Calinou** [comment]
Should this issue be considered resolved?

**Comment by RodZill4** [comment]
@Calinou Yes it works now.
