### ISSUE TITLE
Unreal Blueprint Style Group

### ISSUE THREAD

**Issue by MrDiamondGold** [RodZill4/material-maker#75]
Unreal has a group node that goes around an area that has a re-nameable title that I find very useful for organization.

![image](https://user-images.githubusercontent.com/23109906/73476421-055de500-4347-11ea-8008-98833435158d.png)

**Comment by RodZill4** [comment]
Hmm why not, but I prefer using "real" groups, to keep the main graph as small as possible.

**Comment by MrDiamondGold** [comment]
I feel like groups are still a work in progress and I find it to be confusing to navigate the group tree. With the groups they lack editable inputs and outputs after they have been created unless you count remote but that only allows "constant values" in the way that they can't change when generating the material unlike the regular inputs.

**Comment by MrDiamondGold** [comment]
If my problems with groups are fixed then I would use them happily but I still feel like I'm missing that extra bit of organization, especially when looking at a material that you haven't created or haven't touched in a while.

**Comment by RodZill4** [comment]
Of course inputs and outputs are editable. Just select them and hit Ctrl-W, and you can add/remove/reorder ports. And reordering will keep connectivity outside.

**Comment by RodZill4** [comment]
And BTW, the comment node is not that bad for that purpose. Make it possible to edit the title and change the color, maybe ? And make sure comments are always below other nodes.

**Comment by RodZill4** [comment]
@MrDiamondGold Comments with editable title and colors...

![image](https://user-images.githubusercontent.com/6957908/73615489-8bf51980-4608-11ea-8b1a-1db5d5e5ac35.png)
