### ISSUE TITLE
[Proposal] Update theme

### ISSUE THREAD

**Issue by Grumoth** [RodZill4/material-maker#76]
![image](https://user-images.githubusercontent.com/7796648/73543951-fb63e100-442f-11ea-95f1-d721ad44247c.png)
Hi, what about updating the Theme to the modern Godot one? It's only a couple clicks. Shall I make a PR with something like this or you are fine with the current one?
Thanks!

**Comment by RodZill4** [comment]
I really don't like how the treeview looks... but I like the idea of updating the theme. Maybe even provide several themes like Pixelorama...

**Comment by Calinou** [comment]
I'm working on a new theme in this branch: https://github.com/Calinou/godot-procedural-textures/tree/new-theme

**Comment by RodZill4** [comment]
Looks very nice, new default theme! ;)
I pushed (to master) a theme selection menu with 3 fat themes... I'll update them later, based on yours whenever it's ready.

**Comment by Calinou** [comment]
@RodZill4 The current theme I'm working on is hand-made in the Godot theme editor. If we were to add a theme selection menu, we'd have to change all themes manually every time we need to change something :slightly_frowning_face: 

One way to solve this is to generate themes by code so we can have color variants without duplicated work. This is what the Godot editor does.

**Comment by RodZill4** [comment]
I was thinking about using your theme as starting point, and introduce (by script) settings from the others. I tried using a Godot script, but it didn't work as expected, so I guess I will directly process the .tres files. So there will be only 1 "reference theme" (yours), and variations generated from it.

**Comment by RodZill4** [comment]
@Calinou I added a small script to optimize themes generated in Godot (it tries to grab all images and saves them as PNG). It needs to be run twice because it needs Godot to reload resources to create a correct theme.

**Comment by RodZill4** [comment]
@Calinou Any news about your theme? It looks way better than Godot's default (particularly regarding nodes). Looking at your screenshot, maybe make sure nodes are not bigger than they were (seems spacing between parameters is a bit larger) and it would be perfect. I'm really bad at creating themes (and everything art related)...

**Comment by Calinou** [comment]
@RodZill4 I'm currently busy working on other projects, so it will take a few weeks before the new theme can be production-ready.

**Comment by RodZill4** [comment]
@Calinou OK, thanks! Not sure when I'm ready for next release anyway...

**Comment by Jummit** [comment]
Isn't there a new theme in the newest versions?

**Comment by RodZill4** [comment]
There are 3 themes in 0.9, but they're quickly hacked from Godot default themes. Calinou started created an optimized one.

**Comment by Jummit** [comment]
Just for inspiration, this is my current theme:
![image](https://user-images.githubusercontent.com/28286961/82320476-a2ff2200-99d3-11ea-8db2-d78ae99585c1.png)

**Comment by RodZill4** [comment]
There's a pull request for themes: #118
Maybe you could join the theme party. ;)

**Comment by RodZill4** [comment]
Many proposals have been implemented for 0.93
