### ISSUE TITLE
Add more control over randomness

### ISSUE THREAD

**Issue by Panzerschrek** [RodZill4/material-maker#79]
There are some patterns, based on random values - bricks, voronoi, perlin noise, color noise 
truchet, scratchers, etc. Result of such patterns changes after each change of pattern node, even if only position changed.
Sometimes, final result may looks either good or bad, dependent on random seed. So, if you selected good seed, you need to quickly export result, because after any change or after program restart you may not receive good seed again.
To fix such issues, it will be good to control randomness. I see two options how to do this:
* Add one global random seed and allow user to change it and save in result material file.
* Add random seed option to any node, that uses random generator.

**Comment by Panzerschrek** [comment]
Oh, crap. I used old version, version 0.7 and higher have some randomness control.
But it still may be improved. Now i can freeze random seed of some node, but i can not specify it.

**Comment by RodZill4** [comment]
Hmm how would you want to specify random seed ?

**Comment by RodZill4** [comment]
@Panzerschrek Oh, reading your first comment, I see that how randomness works is not clear enough. The random seed ONLY depends on the position. So changing the position IS the way to change the random seed.
Note that when using node groups, moving the hierarchy will influence the seed of its children unless otherwise specified (in each child or in the group). From my point of view, there is already enough control over randomness.

**Comment by Jummit** [comment]
Here is the solution I'd propose:
Make the seed stay the same, and make the dice icon set a new seed.

**Comment by RodZill4** [comment]
@jummit Your solution is possible but gives less control on random seeds, particularly how they are handled in a hierarchical graph: moving a group will (optionally) change the seed of all children except those that are locked. Your solution remove the ability to lock node seeds.

**Comment by Jummit** [comment]
I see the problem with node hirachies, but

> Your solution removes the ability to lock node seeds.

I meant that nodes would always keep their seed and behave like they are locked.

**Comment by RodZill4** [comment]
> > Your solution removes the ability to lock node seeds.
> 
> I meant that nodes would always keep their seed and behave like they are locked.
 
Locking a node makes it immune to shuffling from parent. that way you control exactly which nodes have a fixed seed.

**Comment by Jummit** [comment]
I still think "re-rolling" by clicking the dice is the most intuitive. Maybe re-roll a grouped node would re-roll the children of the node as well, and you could still lock nodes by ctrl clicking the dice.

**Comment by RodZill4** [comment]
If reroll happens by clicking a button, rerolling a group **must** reroll children (unless they are locked or the group does not transmit seed rerolls).

**Comment by Jummit** [comment]
Maybe one could increase the seed with the right mouse button and decrease the seed with the left mouse button, that would make it possible to get the same seed again.

**Comment by RodZill4** [comment]
> 
> 
> Maybe one could increase the seed with the right mouse button and decrease the seed with the left mouse button, that would make it possible to get the same seed again.

Or maybeI should implement f*cking undo/redo instead. ;)
