### ISSUE TITLE
Command line mode export

### ISSUE THREAD

**Issue by Panzerschrek** [RodZill4/material-maker#80]
I store only source materials (*.ptex files) in my project repository, but not generated by export images, because storing them is redundant and consumes a lot of space (several MB against several KB). But if i want to produce material images, i needed to launch Material Designer for every material and manually export it.
It will be better, if Material Designer will have special console mode only for export.
For example:
`MaterialDesigner.exe --export -i in_material.ptex -o output_directory/`
This command opens input material and exports it.
If such options will exist, it will be easy to write script, that automatically exports all materials in project build process.

**Comment by RodZill4** [comment]
Good idea. I guess an extra flag will be necessary to specify an export "flavor" (Godot, Unity, Unreal...).

**Comment by Calinou** [comment]
`--export` is reserved by Godot, so you will have to use another argument name. Something like `--mm-export` (`mm` being Material Maker)?

**Comment by RodZill4** [comment]
@Calinou It seems --export is reserved only by the Godot editor. You can parse it with an exported game/tool. So I'll use another flag to develop and test, and keep --export when releasing Material Maker.

**Comment by RodZill4** [comment]
@Panzerschrek If you are using Godot, next release will have an updated addon that directly imports .ptex files, either by pre-rendering them, or by storing them in your game as .ptex structure and rendering them when needed. There's a demo in the dev-export branch that you can export using the "Windows demo" export profile.

**Comment by Panzerschrek** [comment]
@RodZill4, unfortunately i am using not Godot, but own engine.

**Comment by RodZill4** [comment]
@Panzerschrek The dev-export branch has support for command-line export. It can export for Godot and Unity (generates textures + material files), and generates textures for Unreal (but material has to be put together manually). Please don't hesitate to test this branch and tell me if your engine has specific requirements (adding a new target is just a matter of modifying a JSON file, I can help you for that if needed).

**Comment by Panzerschrek** [comment]
@RodZill4, for me it will be fine to export only image files. Other stuff i can do with my own scripts/build system.
About testing - I tried to test this branch, but i failed to build project, something wrong with export.

**Comment by RodZill4** [comment]
@Panzerschrek OK. Please tell me if you want to test a prerelease of that feature (and tell me if it's Windows or Linux). Not sure when 0.9 will be ready.

**Comment by Jummit** [comment]
Isn't this implemented now? (https://rodzill4.github.io/material-maker/doc/command_line.html)

**Comment by RodZill4** [comment]
Yes it is!

**Comment by Panzerschrek** [comment]
Great! It works now.
