### ISSUE TITLE
2D preview window isn't visible if it's too short or tall, creates several node drawing problems

### ISSUE THREAD

**Issue by DeerTears** [RodZill4/material-maker#81]
This is using Material Maker v0.8. Here's a video demonstrating this: https://youtu.be/VE8qLj2xFQs

**Bug Description**

On startup and whenever the 2D preview window is activated at the divider's default size (at 900p resolution with 100% Windows 10 scaling) the 2D preview window won't show anything inside it.. While it's doing this, some of the text and panels for deselected/inactive nodes are hidden. The 2D preview window needs to be at an incredibly specific window-height relative to the others to show its contents, and it can still create more node-rendering issues even when it *is* visible.

**Current User Fix:**

Turning the 2D preview window into a 3D preview window makes everything in the app display as intended, pretending the 2D preview window doesn't exist.

*Video Timestamps for the demonstration video:* https://youtu.be/VE8qLj2xFQs

0:55: When I stretch the 2D preview window to be taller, the 2D window shows itself for a bit, but making it too high causes the same problem as before. Stretching the 2D preview window's height around changes how much the deselected nodes have their text/panels drawn.

1:12: When the 2D preview window is active but not drawn, it also stops the 3D preview that you can activate in the background of the workspace.

**The good news:**

- All nodes, buttons and sliders are always functional even if they're not visible.
- Adjusting 2D preview window's width doesn't seem to change anything.

**Possibly connected behaviours that could be their own issues:**
- When 2D window is active but not drawn, scrolling all the nodes off-screen hides the file tabs at the top and the background-preview button
- When the 2D window is active and drawn, it will show me a 2D preview of my nodes as I click on them, except for when I click on the final material output

**Desired Fixes/Suggestions:**
- The program lets me know that the 2D preview window needs to be taller to work properly.
- The 2D preview window still draws nodes fully if it's active and too small to be drawn.
- The 2D preview window still draws when it's activated and has more than enough height to display itself, centring the 2D preview in the middle of the extra height it's given.

**My Specs:**
OS Name: Microsoft Windows 10 Home
Version: 10.0.18362 Build 18362
System Type: x64-based PC
Processor: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz, 2904 Mhz, 2 Core(s), 4 Logical Processor(s)

**Comment by RodZill4** [comment]
@DeerTears thanks a lot for this detailed information.
This is a really weird problem, and everything I see on your video should not happen at all. All nodes should always be displayed correctly, as in https://youtu.be/en4THDP3D9k (1:03).
Could you please give me your GPU model and driver?
Would it be possible for you to try to run Material Maker from sources (from this repository, using the Godot game engine)?

**Comment by DeerTears** [comment]
Yeah, here's a screenshot of my graphics panel giving me some system info about my GPU
![image](https://user-images.githubusercontent.com/47726614/74073176-99265580-49c6-11ea-9ed8-cb6735c09fa9.png)

I will try it through Godot using this repo rather than the standalone from itch.io

**Comment by RodZill4** [comment]
OK, it looks like your Intel GPU does not like my 2D preview shader. I had a look at the code and cannot figure what's wrong (was hunting for divide by zero errors or something).

**Comment by DeerTears** [comment]
Oh! You know what, my GPU probably doesn't like your shader because I think the GPU is dying. My laptop is 6 years old, and it's been having some on and off bottlenecking issues lately despite reformatting the whole system. *Just today* I discovered that my GPU has been the culprit at causing these odd, inconsistent lockups where a single Youtube tab or a lightweight offline music player will stutter and cause general system slowness. I know it's not my SSD or my Memory because I've been testing those directly, and Task Manager is only ever pointing the finger at my GPU occasionally hitting 100% as well.

So, my GPU is probably refusing to talk to your shader because my GPU wants to be laid to rest already after 6 years. I've just **never** seen any graphical issues from my GPU, only inconsistent slowness. That's why I thought it was something with the code and not something with my hardware.

I'll replace my GPU by next week and I'll check-in again to see if that fixes this(it probably will!) but in any case, thanks for going with me on this odd issue journey. I can't say much else is needed from you unless a replacement doesn't fix this drawing problem.

**Comment by RodZill4** [comment]
@DeerTears Hmm this is weird. I was really thinking about my shader doing something weird that's accepted on some GPUs and not by others (that could also depend on drivers etc.). It seems you have no other rendering problems, only low performance.

Are you sure your GPU is not just overheating (in which case it could still be damaged)?

One strange thing is that it is one of the simplest shaders in Material Maker. Did you try to load one of the examples to see how it renders? This should involve pretty complex shaders, if you want to test your GPU further...

**Comment by DeerTears** [comment]
Hmm, yeah I did more looking around and actually you may be onto something, it probably wouldn't fail to draw like this if it was damaged. It really could just be that I have an Intel chip and everybody else has something that your style of shader supports better? The examples draw perfectly in 3D, it's just this 2D preview that doesn't seem to work.

Also trying to install your addon in a 3.2 stable version of Godot throws this error: 
![image](https://user-images.githubusercontent.com/47726614/74486874-498ad280-4e7b-11ea-9345-d69f5f055d04.png)

**Comment by RodZill4** [comment]
@DeerTears The release in the assetlib is really old, I will update it when 0.9 is ready. I modified the shader a little bit, not sure it will change anything for you but if you have time to test the current master...

**Comment by DeerTears** [comment]
So after a really long time of trying to find out what the issue was with some Godot games causing problems, the core of this issue is basically that I have an Intel IGP and GLES3 is not well supported with it. Some Godot games cause issues with flickering materials, but as of MM v0.96 I have been able to run things just fine as the standalone app. It just, works. No more glitching. 3D and 2D views work fine, any window size. If anything it just runs slower than I last remember, but now it's much more advanced and at least I can use it now! So I don't know what happened along the way, but thanks for inadvertently fixing this issue!

**Comment by Calinou** [comment]
> the core of this issue is basically that I have an Intel IGP and GLES3 is not well supported with it.

Intel's OpenGL drivers were never that great on Windows, and they will probably never be fixed at this point (especially on older hardware). Vulkan will improve this situation, but switching to Linux will also let you use the superior Mesa drivers.

**Comment by RodZill4** [comment]
I changed the preview shader and removed the part that drew axes (the part I suspected was a problem for your GPU).
Glad to see this worked and that you didn't give up! Please don't hesitate to join our small community on Discord. ;)
