### ISSUE TITLE
Problems connecting nodes

### ISSUE THREAD

**Issue by leonard7e** [RodZill4/material-maker#90]
My PC …
Ubuntu Linux 19.04 (32G memory)
GPU: GeForce GTX 770

This problem occurs suddenly, I am not sure how to reproduce. Normally I can do node connections with a mouse drag from output slot to input slot. But if the problem occurs, this does not work. Instead my clcik-drag moves the whole source node or creates a selection box.

**Comment by Jummit** [comment]
I can confirm this. It sometimes happens when messing with group nodes I think.

**Comment by paulofalcao** [comment]
I also have this problem. It is very common to happen, the only solution now is to save and open again.

**Comment by RodZill4** [comment]
Yes I know of that problem and I didn't find a way of repeating it yet. there is another (maybe related) problem when several tabs are open and 2 graph editors are vosoble at the same time.
If anyone can find a minimal scenario to repeat this issue, please feel free to describe it here. ;)

**Comment by leonard7e** [comment]
Hi. Thank you for your answers. I tried to reproduce issue.

It seems the problem might be linked to node window zoom and number of output slots of affected node. 

I cannot reproduce issue with node which only has one output slot. But I could do with nodes which hase multiple output slots.

A minimal way …
* create Pattern//Beehive node
* zoom out max
* try connect 2nd or 3rd output  of Beehive to Material node
* zoom in again
* try connect Beehive to Material node

After I zoom in max, I was able to connect wood material again. Sometimes I have to repeadingly zoom in and out to get that behaviour.

For some obscure reason I am able to connect first node of beehive, while other 2 dont work. Could you reproduce? Does output slot type matter?

If I use Workflow // Materials // Wood instead of Beehive, the problem affects first output slot of Wood too.
