### ISSUE TITLE
3D SDF Repeat node doesn't seem to work

### ISSUE THREAD

**Issue by varkatope** [RodZill4/material-maker#96]
The 3D SDF Repeat node doesn't seem to work properly as far as I can tell, no matter which 3D SDF node I plug into it. This could be why the included 3D SDF examples, like the Skulls, don't work correctly either since most of them use at least a few Repeat nodes. I also noticed that the output nodes of the nested graphs in Skulls, for example, don't seem to want to connect to anything if you unplug and replug a node into them. That may be a separate issue, though.

**Comment by RodZill4** [comment]
@varkatope Hmm the skull example works perfectly for me, could you give me more details about your OS, your GPU and what happens exactly when using that node? Does it generate anything at all?

**Comment by varkatope** [comment]
Interesting. I'm on Manjaro Linux, Ryzen 5 / Vega 8 graphics, 8GB RAM. No, it doesn't generate anything at all. The skulls example only generates the dirt at first, though I can go into the hierarchy and bypass the Repeat nodes to get it to generate individual skulls or bones (without unplugging what's already plugged into the output node, for the reason I mentioned above). The Circle Repeat node works fine.

**Comment by RodZill4** [comment]
@varkatope Hmm are you familiar with GLSL ? There's probably something in the Repeat node your GPU does not like, and it will be difficult for me to investigate that (only PCs under Windows with NVidia GPUs here).
Otherwise, I can provide a .ptex file with different variants of the Repeat node, so you can tell me which ones work and which don't.

**Comment by varkatope** [comment]
@RodZill4 Unfortunately not, no, but I'm happy to test any variants you might have.

**Comment by varkatope** [comment]
@RodZill4 You'll be glad to know this problem actually resolved itself a while back. I don't know how, but I assume they fixed something in the Mesa drivers at some point that made this work properly. Cheers.
