### ISSUE TITLE
Command line arguments to export specific channel

### ISSUE THREAD

**Issue by Jummit** [RodZill4/material-maker#98]
I need to export only a specific channel of my material.

`-c`: Channel. Could be albedo, normal, ao, roughness etc.

`-o`: Output path. Exports all channels when it's a directory and only the provided channel if it's a png. The default channel could be albedo.

Example:

`material-maker --export -c albedo -o albedo.png material.ptex`

I want this to make a thumbnailer for .ptex files. Currently I use this code which exports everything and uses the albedo as thumbnail:
```sh
material-maker --export --size "${1}" -o /tmp "${2}"
materialname=$(basename $2 .ptex)
albedopath="/tmp/${materialname}_albedo.png"
cp "${albedopath}" "${3}"
```
Result:
![image](https://user-images.githubusercontent.com/28286961/77092283-e9eb8e00-6a09-11ea-8007-304018c7b25b.png)
This is slow because it exports every texture.

**Comment by RodZill4** [comment]
Hmm export does not really export PNG files, it exports materials that consist of PNG files and engine specific text files.
And export profiles can be modified/added in the **material.mmg** file in the **nodes** directory.

Here's a new file with an "albedo" export target. Please tell me if it solves your problem.
[material.zip](https://github.com/RodZill4/material-maker/files/4357079/material.zip)

**Comment by Jummit** [comment]
That works, it's now four times as fast. I would still love to be able to specify the direct export path, but this works for now.
